import { checkAuthor } from "./german-a1-batch-a-check";
// Held-out original arrangements; A asks learners to compose/extract, B to repair/contrast.
// These bounded observations do not certify all mapped skills or free writing.
const { item: i, form: f } = checkAuthor("04", [
  {
    id: "time-v2",
    label: "Time opener and verb position",
    scope: "One complete statement with a reviewed time phrase and finite verb second.",
  },
  {
    id: "changed-plan",
    label: "Read a changed time",
    scope: "Retrieve the current time and distinguish earlier/later in a short update.",
  },
  {
    id: "prefix",
    label: "Keep the action prefix",
    scope: "One complete separable statement or question, retaining the final prefix.",
  },
  {
    id: "possibility",
    label: "Express possibility",
    scope: "A bounded können statement or service question, not permission.",
  },
  {
    id: "request",
    label: "Distinguish a request from intent",
    scope: "Select a polite möchte request rather than will/soll.",
  },
  {
    id: "bracket",
    label: "Keep the modal frame",
    scope: "One taught modal question with the infinitive final.",
  },
  {
    id: "rule",
    label: "Interpret necessity and permission",
    scope: "Distinguish required, permitted and forbidden action in a notice.",
  },
  {
    id: "alternative",
    label: "Give a practical alternative",
    scope: "A two-clause message containing a constraint and a workable plan.",
  },
]);
export const unit4Check = f("A", [
  i(
    "A",
    1,
    "construction",
    "time-v2",
    "You work on Tuesday. Start Am Dienstag and write one full sentence with ich and arbeiten. Dienstag = Tuesday.",
    ["Am Dienstag arbeite ich."],
  ),
  i(
    "A",
    2,
    "reading-extraction",
    "changed-plan",
    "Copy only the new course start, as a time phrase beginning um.",
    ["um zwölf"],
    "Kurs: zuerst 11 Uhr, jetzt 12 Uhr. zuerst = at first; jetzt = now",
  ),
  i(
    "A",
    3,
    "construction",
    "prefix",
    "Ask a friend whether they call Ben at eight. Begin Rufst, use du, and write the full yes/no question.",
    ["Rufst du Ben um acht an?", "Rufst du um acht Ben an?"],
  ),
  i(
    "A",
    4,
    "construction",
    "possibility",
    "You and Ada can come at seven. Write one full statement beginning Wir with können.",
    ["Wir können um sieben kommen."],
  ),
  i(
    "A",
    5,
    "choice",
    "request",
    "At a shop you politely request a book. Select the suitable statement.",
    ["Ich möchte ein Buch kaufen."],
    undefined,
    ["Ich will ein Buch kaufen.", "Ich möchte ein Buch kaufen.", "Ich soll ein Buch kaufen."],
  ),
  i(
    "A",
    6,
    "construction",
    "bracket",
    "Ask what you should buy, as instructed by the office. Use was, sollen, ich and kaufen. Write the whole question.",
    ["Was soll ich kaufen?"],
  ),
  i(
    "A",
    7,
    "choice",
    "rule",
    "Which action is required, rather than merely allowed or forbidden?",
    ["Work at eight."],
    "Du musst um acht arbeiten. Du darfst um zwölf essen. Du darfst um elf nicht essen.",
    ["Work at eight.", "Eat at twelve.", "Eat at eleven."],
  ),
  i(
    "A",
    8,
    "construction",
    "alternative",
    "You must study tomorrow, but can come on Monday. Write two full sentences beginning Ich: first the obligation, then the possible visit.",
    ["Ich muss morgen lernen. Ich kann am Montag kommen."],
  ),
]);
export const unit4CheckB = f("B", [
  i(
    "B",
    1,
    "bounded-text",
    "time-v2",
    "The time must stay first. Repair only the verb/subject order and write the whole sentence.",
    ["Im Mai arbeitet Ada."],
    "Draft: Im Mai Ada arbeitet.",
  ),
  i(
    "B",
    2,
    "choice",
    "changed-plan",
    "Read the update. Is the new call earlier or later? Select one.",
    ["Earlier."],
    "Anruf: alt 12 Uhr, neu 10 Uhr. Anruf = call; alt = old; neu = new",
    ["Earlier.", "Later.", "Unchanged."],
  ),
  i(
    "B",
    3,
    "bounded-text",
    "prefix",
    "The shopping note lost its final prefix. Restore the complete activity and write the whole sentence.",
    ["Wir kaufen um neun im Zentrum ein."],
    "Draft: Wir kaufen um neun im Zentrum. Intended activity: einkaufen.",
  ),
  i(
    "B",
    4,
    "reading-extraction",
    "possibility",
    "Ada says she has time to come. Restate only that possibility about Ada in one complete German sentence. Start Ada kann.",
    ["Ada kann um elf kommen."],
    "Ada: Um elf habe ich Zeit. Ich komme gern. Zeit = time",
  ),
  i(
    "B",
    5,
    "choice",
    "request",
    "Which draft reports an instruction from the office, rather than your own intention or a polite request?",
    ["Ich soll um acht kommen."],
    undefined,
    ["Ich will um acht kommen.", "Ich soll um acht kommen.", "Ich möchte um acht kommen."],
  ),
  i(
    "B",
    6,
    "bounded-text",
    "bracket",
    "This service question has the infinitive in the wrong position. Keep every word and write the corrected whole question.",
    ["Kann ich am Montag kommen?"],
    "Draft: Kann kommen ich am Montag?",
  ),
  i(
    "B",
    7,
    "choice",
    "rule",
    "What does the notice say about eating here? Select one interpretation.",
    ["Forbidden."],
    "Du darfst hier nicht essen.",
    ["Required.", "Allowed.", "Forbidden."],
  ),
  i(
    "B",
    8,
    "construction",
    "alternative",
    "You must work at nine, but can come at twelve. Write two full sentences beginning Ich, first the obligation and then the possible visit.",
    ["Ich muss um neun arbeiten. Ich kann um zwölf kommen."],
  ),
]);
export const unit4CheckForms = [unit4Check, unit4CheckB] as const;
