import type { LessonStep } from "@/lib/curriculum/types";
import { lessonAuthor, G, R, W, V } from "./german-a1-batch-a-lesson";
const frame = G + "PAST.PERFEKT_FRAME",
  regular = G + "PAST.REGULAR_PARTICIPLE",
  email = R + "SHORT_EMAIL";
const a = lessonAuthor("06", 1);
export const pastFrameSteps: readonly LessonStep[] = [
  a.explain(
    "scene",
    "A shopping update",
    "Compare an activity now with an activity already done.",
    "Ich kaufe ein.\nIch habe eingekauft.",
    "The second message says the shopping is done. habe is the changing verb near the start; eingekauft closes the statement. You can learn this whole frame without already knowing separable verbs.",
    [frame, regular],
  ),
  a.choice(
    "meaning",
    "recognize",
    "Find the finished action",
    "Which message says the studying already happened?",
    ["Ich lerne Deutsch.", "Ich habe Deutsch gelernt."],
    "Ich habe Deutsch gelernt.",
    "habe … gelernt presents studying as a recent completed action.",
    [frame],
  ),
  a.explain(
    "bracket",
    "Hold the sentence together",
    "Notice the two positions in each short statement.",
    "Ich habe heute gelernt.\nHeute habe ich gelernt.\nBen hat heute gearbeitet.",
    "habe/hat occupies the second clause position; gelernt/gearbeitet stays at the end. heute = today. A time phrase can come first; then the subject follows the finite verb. For this lesson: ich habe, Ben/er hat.",
    [frame],
  ),
  a.text(
    "order",
    "produce",
    "Send the study update",
    "Use ich, habe, Deutsch and gelernt. Begin Ich and write one complete sentence saying you studied German.",
    ["Ich habe Deutsch gelernt."],
    "Ich habe Deutsch gelernt. The studied subject is inside the habe … gelernt bracket.",
    [frame],
  ),
  a.explain(
    "forms",
    "Three useful completed activities",
    "Learn this small reviewed set.",
    "lernen → gelernt\narbeiten → gearbeitet\neinkaufen → eingekauft",
    "These are regular forms reviewed here: gelernt; gearbeitet (with -et); eingekauft. In einkaufen, ein stays first and ge goes between ein and kauf. No complete list or universal participle rule is needed.",
    [regular],
  ),
  a.text(
    "recall",
    "recall",
    "Recall the work form",
    "Complete Ich habe heute ___. Use the reviewed past form of arbeiten. Type only that form.",
    ["gearbeitet"],
    "gearbeitet is the reviewed form of arbeiten; the extra e makes the ending pronounceable.",
    [regular],
  ),
  a.text(
    "shopping",
    "produce",
    "Report your shopping",
    "You shopped today. Begin Heute; use ich and the reviewed einkaufen frame. Write one complete sentence.",
    ["Heute habe ich eingekauft."],
    "Heute habe ich eingekauft. The finite auxiliary is second and the participle closes the statement.",
    [frame, regular],
  ),
  a.text(
    "mail-time",
    "read",
    "Read the new arrangement",
    "Copy only the new meeting time, including um.",
    ["um sechs"],
    "um sechs is the new meeting time; the work happened today.",
    [email],
    "Hallo Ada! Ich habe heute gearbeitet. Wir treffen uns morgen um sechs. Bitte nicht um fünf kommen. Ben\nwir treffen uns = we meet; morgen = tomorrow",
  ),
  a.choice(
    "mail-purpose",
    "apply",
    "Why did Ben write?",
    "Select the main practical purpose of the email.",
    [
      "Arrange tomorrow's meeting and exclude the old time.",
      "Ask Ada to shop today.",
      "Cancel all meetings.",
    ],
    "Arrange tomorrow's meeting and exclude the old time.",
    "The message sets tomorrow at six and explicitly rules out five.",
    [email],
    "Hallo Ada! Ich habe heute gearbeitet. Wir treffen uns morgen um sechs. Bitte nicht um fünf kommen. Ben",
  ),
  a.text(
    "check",
    "check",
    "A fresh update for a colleague",
    "Ben studied today. Write one complete sentence beginning Ben, using heute and lernen in the reviewed completed-action frame.",
    ["Ben hat heute gelernt."],
    "Ben hat heute gelernt. hat agrees with Ben; gelernt closes this new statement.",
    [frame, regular],
  ),
];
const common = G + "PAST.COMMON_PARTICIPLE",
  auxiliary = G + "PAST.AUXILIARY_CHOICE",
  sequence = W + "SEQUENCE";
const b = lessonAuthor("06", 2);
export const pastActionsSteps: readonly LessonStep[] = [
  b.explain(
    "scene",
    "Tell a friend what happened",
    "Read two completed events as separate messages.",
    "Ich bin zum Bahnhof gegangen. Ich habe gegessen.",
    "I went to the station. I ate. These taught uses take bin … gegangen and habe … gegessen. Both are independent sentences; linking clauses is not necessary.",
    [common, auxiliary, sequence],
  ),
  b.explain(
    "inventory",
    "Four familiar irregular forms",
    "Review only these useful frames.",
    "gehen → gegangen: Ich bin zur Bank gegangen.\nkommen → gekommen: Ada ist gekommen.\nessen → gegessen: Ich habe gegessen.\nsehen → gesehen: Ich habe Ben gesehen.",
    "Learn auxiliary choice with the taught sense: going to a destination and arriving use sein here (ich bin, Ada ist). Eating and seeing someone use haben (ich habe). This is not a rule that every action involving movement uses sein. machen → gemacht and lernen → gelernt remain familiar regular forms.",
    [common, auxiliary],
  ),
  b.choice(
    "aux",
    "classify",
    "Seeing someone is a different frame",
    "Choose the completed message saying you saw Ada.",
    ["Ich habe Ada gesehen.", "Ich bin Ada gesehen."],
    "Ich habe Ada gesehen.",
    "The taught sehen frame uses haben; choose by the reviewed meaning/frame.",
    [auxiliary, common],
  ),
  b.text(
    "recall",
    "recall",
    "Retrieve the arrival form",
    "Complete Ada ist ___. Use the reviewed completed-action form of kommen. Type only the participle.",
    ["gekommen"],
    "gekommen is the reviewed irregular form; gekommen, not gekommt.",
    [common],
  ),
  b.text(
    "eat",
    "produce",
    "Tell your friend you ate",
    "Use ich and essen to report that you ate. Write one complete sentence beginning Ich.",
    ["Ich habe gegessen."],
    "Ich habe gegessen uses the reviewed haben frame.",
    [common, auxiliary],
  ),
  b.text(
    "go",
    "produce",
    "Report the bank visit",
    "Say you went to the bank. Begin Ich and use the reviewed destination chunk zur Bank and gehen.",
    ["Ich bin zur Bank gegangen."],
    "Ich bin zur Bank gegangen. This destination-going frame uses bin.",
    [common, auxiliary],
  ),
  b.explain(
    "sequence",
    "Keep the order visible",
    "The sequence can live in separate sentences.",
    "Zuerst habe ich gelernt. Dann habe ich gegessen.\nIch habe heute gelernt. Morgen kann ich kommen.",
    "zuerst = first; dann = then. These supplied time words make order clear, but are not mandatory for the writing skill. heute … gelernt reports an event; morgen … kann presents a future possibility. Use short independent sentences.",
    [sequence, auxiliary],
  ),
  b.text(
    "events",
    "apply",
    "Two events in order",
    "First you saw Ben, then you went to the station. Write two separate sentences in that order, each beginning Ich. Use Ben and zum Bahnhof.",
    ["Ich habe Ben gesehen. Ich bin zum Bahnhof gegangen."],
    "Each sentence has its own finite auxiliary; the written order communicates the sequence.",
    [sequence, common, auxiliary],
  ),
  b.choice(
    "plan",
    "classify",
    "Past event or new plan?",
    "Which part is a future possibility?",
    ["The studying.", "Coming tomorrow."],
    "Coming tomorrow.",
    "Morgen kann ich kommen describes a possibility; habe gelernt reports the completed studying.",
    [sequence],
    "Ich habe heute gelernt. Morgen kann ich kommen.",
  ),
  b.text(
    "check",
    "check",
    "An unseen two-event update",
    "You arrived first and ate afterwards. Write two separate complete sentences in this order, each beginning Ich. Use kommen and essen; no connector is required.",
    ["Ich bin gekommen. Ich habe gegessen."],
    "Ich bin gekommen. Ich habe gegessen. Arrival and eating keep their separately taught auxiliaries.",
    [sequence, common, auxiliary],
  ),
];
const states = G + "PAST.WAR_HATTE",
  transfer = G + "TRANSFER.CLAUSE_FRAMES",
  purpose = R + "MAIN_PURPOSE",
  change = W + "APOLOGY_CHANGE";
const c = lessonAuthor("06", 3);
export const changedArrangementSteps: readonly LessonStep[] = [
  c.explain(
    "scene",
    "Explain a missed arrangement",
    "Use a short past-state chunk and a new proposal.",
    "Es tut mir leid. Ich hatte keine Zeit. Ich kann morgen kommen.",
    "Es tut mir leid = I'm sorry. hatte keine Zeit = had no time. These three independent sentences apologize, give the earlier constraint and offer a new step. keine Zeit = no time; morgen = tomorrow.",
    [states, change],
  ),
  c.explain(
    "states",
    "A small set of earlier states",
    "Review these chunks, not a full past-tense table.",
    "Ich war krank. Er war müde. Sie war krank.\nIch hatte keine Zeit. Er hatte keine Zeit. Sie hatte keine Zeit.",
    "krank = sick; müde = tired. war reports an earlier state, hatte reports earlier possession/availability. Only these ich/er/sie chunks are taught; present ich bin / ich habe still describes now.",
    [states],
  ),
  c.text(
    "recall",
    "recall",
    "Recall the earlier time constraint",
    "Complete Ich ___ keine Zeit. The lack of time was earlier, not now. Type only the reviewed verb.",
    ["hatte"],
    "hatte makes this the earlier state; habe would describe now.",
    [states],
  ),
  c.text(
    "state",
    "produce",
    "Explain the earlier illness",
    "Say that you were sick. Start Ich and write one complete sentence using the reviewed earlier-state chunk.",
    ["Ich war krank."],
    "Ich war krank uses the bounded earlier-state chunk.",
    [states],
  ),
  c.choice(
    "intent",
    "apply",
    "Choose the useful reply",
    "A friend asks whether you can meet tomorrow. You can. Which reply communicates that possibility?",
    ["Ich kann morgen kommen.", "Ich war krank.", "Ich habe eingekauft."],
    "Ich kann morgen kommen.",
    "The friend needs tomorrow's possibility, not an earlier event or state.",
    [transfer, change],
  ),
  c.choice(
    "purpose",
    "read",
    "What is this message doing?",
    "Select the main purpose, using the explicit proposal.",
    ["Change a meeting and offer another day.", "Request a price.", "Describe a daily routine."],
    "Change a meeting and offer another day.",
    "nicht kommen cancels today's meeting; morgen offers the new arrangement.",
    [purpose],
    "Hallo Ada! Ich kann heute nicht kommen. Ich kann morgen kommen. Ben",
  ),
  c.text(
    "now",
    "classify",
    "Tell a friend about now",
    "You have no time now. Begin Ich; use keine Zeit. Write one complete German sentence about now.",
    ["Ich habe keine Zeit."],
    "Ich habe keine Zeit refers to now; no past auxiliary or earlier-state chunk is needed.",
    [transfer],
  ),
  c.text(
    "event",
    "apply",
    "Report a completed activity instead",
    "A friend asks what you did today: you worked. Begin Ich and include heute. Write one complete sentence.",
    ["Ich habe heute gearbeitet."],
    "Ich habe heute gearbeitet communicates the completed action the friend asked about.",
    [transfer],
  ),
  c.text(
    "message",
    "apply",
    "Write your own change message",
    "You missed a meeting because you had no time. Use three independent sentences: supplied apology Es tut mir leid; then Ich with the earlier no-time constraint; then Ich with the possibility of coming tomorrow. No greeting or copied full model is needed.",
    ["Es tut mir leid. Ich hatte keine Zeit. Ich kann morgen kommen."],
    "All three requested points must be present: apology, earlier constraint and next possibility.",
    [states, change],
  ),
  c.text(
    "check",
    "check",
    "A fresh cancellation and proposal",
    "Cancel today's visit and propose Friday. Write three independent sentences: Es tut mir leid; then Ich with können, heute and nicht kommen; then Ich with können, am Freitag and kommen. Freitag = Friday.",
    ["Es tut mir leid. Ich kann heute nicht kommen. Ich kann am Freitag kommen."],
    "The bounded message states the change and a concrete next step; the clauses remain independent.",
    [change, transfer, purpose],
  ),
];
const relevance = R + "SELECT_RELEVANT_TEXT",
  vocabulary = V + "TRANSFER_SELECTION",
  fulfilment = W + "TASK_FULFILMENT";
const d = lessonAuthor("06", 4);
export const usefulMessageSteps: readonly LessonStep[] = [
  d.explain(
    "scene",
    "Read for a concrete need",
    "A practical message is useful only when its details match what the reader needs.",
    "A: Bank — heute bis 16 Uhr geöffnet.\nB: Büro — morgen ab 9 Uhr geöffnet.",
    "geöffnet = open; bis = until; ab = from. First identify the place and day, then the relevant time. Do not choose a message just because it contains a familiar word.",
    [relevance, vocabulary],
  ),
  d.choice(
    "match",
    "read",
    "Match the whole need",
    "You need the office tomorrow at ten. Which note fits both the place and time?",
    ["A", "B"],
    "B",
    "B is about the office, tomorrow, and it opens before ten. A is the wrong place and day.",
    [relevance],
    "A: Bank — heute bis 16 Uhr geöffnet.\nB: Büro — morgen ab 9 Uhr geöffnet.",
  ),
  d.text(
    "constraint",
    "read",
    "Find one explicit detail",
    "Copy only the closing time after bis, including Uhr.",
    ["16 Uhr"],
    "16 Uhr is the explicit closing time. This is scanning for one requested detail, not guessing from the whole message.",
    [relevance],
    "Bank: heute bis 16 Uhr geöffnet.",
  ),
  d.explain(
    "transport-model",
    "Transport with mit",
    "Learn the whole transport chunk before you have to produce it.",
    "Ich komme mit dem Bus.\nIch bin mit dem Bus gekommen.",
    "mit means ‘with/by’ here. In this taught transport pattern, mit is followed by the dative: der Bus becomes dem Bus. Learn mit dem Bus as a usable chunk; the lesson does not ask you to derive all dative forms at once.",
    [vocabulary, transfer],
  ),
  d.text(
    "transport-controlled",
    "recall",
    "Complete the taught chunk",
    "Complete: Ich komme mit ___ Bus. Type only the article.",
    ["dem"],
    "After mit in this transport pattern, use dem Bus.",
    [vocabulary],
  ),
  d.explain(
    "help-model",
    "Ask who receives the help",
    "helfen needs the person receiving help in the dative.",
    "Kannst du mir helfen?\nKönnen Sie mir helfen?",
    "When you mean ‘help me’, use mir: ich → mir. With an unfamiliar member of staff, use polite Sie: Können Sie mir helfen? Learn helfen together with the person pattern jemandem helfen; it is more precise than memorizing a broad ‘Dative’ label.",
    [transfer, vocabulary, fulfilment],
  ),
  d.text(
    "request-supported",
    "produce",
    "Build the polite request",
    "Use these parts to ask for help on Tuesday at six: Können · Sie · mir · am Dienstag · um sechs · helfen",
    ["Können Sie mir am Dienstag um sechs helfen?"],
    "Können Sie mir am Dienstag um sechs helfen? mir names the person receiving the help; the day and time complete the practical request.",
    [transfer, vocabulary, fulfilment],
  ),
  d.choice(
    "fresh-texts",
    "apply",
    "Choose the matching offer",
    "You need help on Tuesday at six. Which message matches every requested detail?",
    ["A", "B", "C"],
    "C",
    "Only C matches both Tuesday and six.",
    [relevance, vocabulary],
    "A: Ich kann am Montag um sechs helfen.\nB: Ich kann am Dienstag um acht helfen.\nC: Ich kann am Dienstag um sechs helfen.\nDienstag = Tuesday",
  ),
  d.text(
    "reply",
    "apply",
    "Build a useful response",
    "Give these three details in separate sentences: you are at the station now; you came by bus; you can come tomorrow. Begin each sentence Ich. Use am Bahnhof, mit dem Bus and morgen in that order.",
    ["Ich bin am Bahnhof. Ich bin mit dem Bus gekommen. Ich kann morgen kommen."],
    "The reply gives only useful facts: current place, earlier transport and next possibility. mit dem Bus reuses the taught transport chunk.",
    [transfer, fulfilment, vocabulary],
  ),
  d.text(
    "check",
    "check",
    "A fresh practical request",
    "Ask a member of staff if they can help you on Friday at eight. Begin Können Sie and include mir, am Freitag, um acht and helfen.",
    ["Können Sie mir am Freitag um acht helfen?"],
    "The checked response includes the polite request frame, the dative recipient mir, and both practical details.",
    [relevance, transfer, vocabulary, fulfilment],
  ),
];
