import { batchBAuthor } from "./german-a1-batch-b-assessment";
// Original independent prototype families. No lesson-final stimulus is reused.
const { item: i, form: f } = batchBAuthor("U10", [
  {
    id: "reading",
    label: "Read explicit everyday facts",
    scope: "Extract the stated numerical detail.",
  },
  {
    id: "corrected",
    label: "Keep corrected information",
    scope: "Identify current versus excluded information.",
  },
  {
    id: "relevance",
    label: "Select relevant information",
    scope: "Match all explicit constraints.",
  },
  { id: "question", label: "Ask a practical question", scope: "Ask a genuinely missing fact." },
  { id: "response", label: "Give needed information", scope: "Answer the specific question." },
  { id: "object", label: "Express a needed object", scope: "State a supplied familiar need." },
  {
    id: "transfer",
    label: "Select the relevant frame",
    scope: "Communicate event versus possibility.",
  },
  {
    id: "form",
    label: "Complete a simple form",
    scope: "Keep supplied fictional facts in named fields.",
  },
  {
    id: "message",
    label: "Fulfil a practical message",
    scope: "Produce all requested practical points.",
  },
  { id: "revision", label: "Revise a specific problem", scope: "Change only the named issue." },
]);
export const unit10Check = f("A", [
  i(
    "A",
    1,
    "reading",
    "reading-extraction",
    "Copy only the price including Euro.",
    ["6 Euro"],
    "Bus nach Bonn: 6 Euro. Abfahrt 14 Uhr. Abfahrt = departure",
  ),
  i(
    "A",
    2,
    "corrected",
    "reading-extraction",
    "Copy only the current location.",
    ["Bank"],
    "Treffen heute: Bank, nicht Bahnhof. Treffen = meeting",
  ),
  i(
    "A",
    3,
    "relevance",
    "choice",
    "You need a room Friday in Berlin. Choose the matching offer.",
    ["B"],
    "A: Berlin, Montag. B: Berlin, Freitag. C: Bonn, Freitag. Zimmer = room; Freitag = Friday",
    ["A", "B", "C"],
  ),
  i(
    "A",
    4,
    "question",
    "construction",
    "The course place is known but its time is missing. Ask the time in one full question beginning Wann, using der Kurs.",
    ["Wann ist der Kurs?"],
  ),
  i(
    "A",
    5,
    "response",
    "construction",
    "Ben asks where the meeting is. Answer with Das Treffen ist and the supplied place.",
    ["Das Treffen ist im Büro."],
    "Treffen: Büro, 18 Uhr. im Büro = in the office",
  ),
  i(
    "A",
    6,
    "object",
    "construction",
    "You need a table. Say so in one full Ich statement. Tisch = table.",
    ["Ich brauche einen Tisch."],
  ),
  i(
    "A",
    7,
    "transfer",
    "construction",
    "Ada asks what you did yesterday. Say you went to the office, then worked. Write two Ich sentences.",
    ["Ich bin ins Büro gegangen. Ich habe gearbeitet."],
  ),
  i(
    "A",
    8,
    "form",
    "bounded-text",
    "Return exactly Name: …; Ort: …; Uhrzeit: … .",
    ["Name: Ben; Ort: Bonn; Uhrzeit: 13 Uhr"],
    "Fictional registration: Ben, Bonn, 13 Uhr.",
  ),
  i(
    "A",
    9,
    "message",
    "bounded-text",
    "Tell close friend Ada you can come Wednesday at ten to the bank. Write Hallo Ada!, then one Ich kann sentence with all details. Mittwoch = Wednesday.",
    ["Hallo Ada! Ich kann am Mittwoch um zehn zur Bank kommen."],
  ),
  i(
    "A",
    10,
    "revision",
    "bounded-text",
    "The required object is a chair. Correct ONLY the object, preserving the whole message. Stuhl = chair.",
    ["Ich brauche einen Stuhl. Ich kann morgen kommen."],
    "Draft: Ich brauche einen Tisch. Ich kann morgen kommen.",
  ),
]);
export const unit10CheckB = f("B", [
  i(
    "B",
    1,
    "reading",
    "reading-extraction",
    "Copy only the departure time including Uhr.",
    ["11 Uhr"],
    "Zug nach Berlin, 11 Uhr, 8 Euro. Zug = train",
  ),
  i(
    "B",
    2,
    "corrected",
    "choice",
    "Which day is explicitly excluded?",
    ["Sunday."],
    "Bitte am Samstag kommen, nicht am Sonntag. Samstag = Saturday; Sonntag = Sunday",
    ["Saturday.", "Sunday."],
  ),
  i(
    "B",
    3,
    "relevance",
    "reading-extraction",
    "Need: Bonn, Thursday, twelve. Copy only the matching offer label.",
    ["C"],
    "A: Bonn, Donnerstag, 17 Uhr. B: Berlin, Donnerstag, 12 Uhr. C: Bonn, Donnerstag, 12 Uhr. Donnerstag = Thursday",
  ),
  i(
    "B",
    4,
    "question",
    "bounded-text",
    "The visitor already knows when to come but not where the office is. Change only the wh-word.",
    ["Wo ist das Büro?"],
    "Draft: Wann ist das Büro?",
  ),
  i(
    "B",
    5,
    "response",
    "reading-extraction",
    "Ada asks the price. Give one full statement beginning Die Fahrkarte kostet; use the number in words. neun = nine.",
    ["Die Fahrkarte kostet neun Euro."],
    "Fahrkarte: 9 Euro, 12 Uhr.",
  ),
  i(
    "B",
    6,
    "object",
    "construction",
    "You need a ticket. Give this practical need in one complete sentence beginning Ich.",
    ["Ich brauche eine Fahrkarte."],
  ),
  i(
    "B",
    7,
    "transfer",
    "bounded-text",
    "Ben asks about a future possibility, not a completed visit. Replace the full sentence with a possibility reply beginning Ich; keep morgen/kommen.",
    ["Ich kann morgen kommen."],
    "Draft: Ich bin gekommen.",
  ),
  i(
    "B",
    8,
    "form",
    "bounded-text",
    "Repair reversed values and return exactly Name: …; Uhrzeit: …; Ort: … .",
    ["Name: Ada; Uhrzeit: 20 Uhr; Ort: Berlin"],
    "Fictional person: Ada, Berlin, 20 Uhr. Draft: Name: Berlin; Uhrzeit: Ada; Ort: 20 Uhr.",
  ),
  i(
    "B",
    9,
    "message",
    "bounded-text",
    "Tell staff you cannot attend Friday but can come Sunday at seventeen to the office. Write Guten Tag! and two Ich sentences; no closing required. Freitag = Friday; Sonntag = Sunday; siebzehn = seventeen.",
    [
      "Guten Tag! Ich kann am Freitag nicht kommen. Ich kann am Sonntag um siebzehn ins Büro kommen.",
    ],
  ),
  i(
    "B",
    10,
    "revision",
    "bounded-text",
    "Correct ONLY the day to Saturday, retaining the clock time, destination and closing. Samstag = Saturday.",
    ["Ich komme am Samstag um neun zum Bahnhof. Bis bald!"],
    "Draft: Ich komme am Montag um neun zum Bahnhof. Bis bald!",
  ),
]);
export const unit10CheckForms = [unit10Check, unit10CheckB] as const;
