import { batchBAuthor } from "./german-a1-batch-b-assessment";
const { item: i, form: f } = batchBAuthor("U07", [
  {
    id: "detail",
    label: "Retrieve a travel detail",
    scope: "One explicit date or price from an original travel note.",
  },
  {
    id: "change",
    label: "Interpret changed travel information",
    scope: "The new or explicitly excluded clock time.",
  },
  {
    id: "ticket",
    label: "Make a ticket request",
    scope: "One complete polite request with a supplied destination.",
  },
  {
    id: "room",
    label: "Read room availability",
    scope: "An explicit room/date availability statement.",
  },
  {
    id: "enquiry",
    label: "Ask a relevant service question",
    scope: "Ask for the missing arrival fact or a concrete supported possibility.",
  },
  {
    id: "relation",
    label: "Keep location and destination distinct",
    scope: "Use a reviewed location/destination chunk, not general preposition mastery.",
  },
  {
    id: "arrival",
    label: "Ask about arrival",
    scope: "One bounded separable-prefix question for a familiar listener.",
  },
  {
    id: "message",
    label: "Send a usable travel message",
    scope: "Required place/time/change facts with suitable register.",
  },
  {
    id: "transfer",
    label: "Choose a useful clause frame",
    scope: "Produce the familiar frame that answers the stated intention.",
  },
]);
export const unit7Check = f("A", [
  i(
    "A",
    1,
    "detail",
    "reading-extraction",
    "Copy only the travel date in the note's format.",
    ["21. Juni"],
    "Zug nach Bonn: 21. Juni, 14 Uhr. Fahrkarte: 8 Euro. Zug = train; Juni = June",
  ),
  i(
    "A",
    2,
    "change",
    "reading-extraction",
    "Copy only the current departure time, including Uhr.",
    ["16 Uhr"],
    "Abfahrt: vorher 13 Uhr, jetzt 16 Uhr. Abfahrt = departure; vorher/jetzt = before/now",
  ),
  i(
    "A",
    3,
    "ticket",
    "construction",
    "At the counter, politely say you would like to buy a ticket to Bonn. Begin Ich and use eine Fahrkarte, nach Bonn and final kaufen.",
    ["Ich möchte eine Fahrkarte nach Bonn kaufen.", "Ich möchte nach Bonn eine Fahrkarte kaufen."],
  ),
  i(
    "A",
    4,
    "room",
    "reading-extraction",
    "Copy only the complete sentence stating room availability for Wednesday.",
    ["Am Mittwoch gibt es kein Zimmer."],
    "Am Dienstag gibt es ein Zimmer. Am Mittwoch gibt es kein Zimmer. Mittwoch = Wednesday; Zimmer = room",
  ),
  i(
    "A",
    5,
    "enquiry",
    "construction",
    "The host confirms a Saturday room but leaves the arrival time unknown. Ask when you can come, beginning Wann. Use ich and kommen in a complete possibility question.",
    ["Wann kann ich kommen?"],
    "Guten Tag! Am Samstag gibt es ein Zimmer. Samstag = Saturday; Zimmer = room",
  ),
  i(
    "A",
    6,
    "relation",
    "choice",
    "You are travelling to the station, not already there. Choose the useful destination statement.",
    ["Ich gehe zum Bahnhof."],
    undefined,
    ["Ich bin am Bahnhof.", "Ich gehe zum Bahnhof.", "Ich bin bei der Bank."],
  ),
  i(
    "A",
    7,
    "arrival",
    "construction",
    "Ask one friend when they arrive. Use ankommen (the taught arrival frame) and du. Write a complete question beginning Wann.",
    ["Wann kommst du an?"],
  ),
  i(
    "A",
    8,
    "message",
    "construction",
    "Update your friend Ben: you are at the station now and can come at fifteen; the meeting is not at the bank. Begin Hallo Ben!, then three independent sentences beginning Ich, Ich and Das Treffen ist. Use am Bahnhof; um fünfzehn with final kommen; nicht bei der Bank. Close Bis bald! (see you soon). fünfzehn = fifteen; Treffen = meeting.",
    [
      "Hallo Ben! Ich bin am Bahnhof. Ich kann um fünfzehn kommen. Das Treffen ist nicht bei der Bank. Bis bald!",
    ],
  ),
  i(
    "A",
    9,
    "transfer",
    "construction",
    "A friend asks what you already did before travelling: you ate. Report that event in one complete sentence beginning Ich, using essen.",
    ["Ich habe gegessen."],
  ),
]);
export const unit7CheckB = f("B", [
  i(
    "B",
    1,
    "detail",
    "reading-extraction",
    "Copy only the train ticket price, with Euro.",
    ["7 Euro"],
    "Bus: 3 Euro. Zug nach Berlin: 7 Euro, 18 Uhr, 24. Juni. Zug = train; Juni = June",
  ),
  i(
    "B",
    2,
    "change",
    "reading-extraction",
    "Copy only the excluded time phrase, starting um.",
    ["um vierzehn"],
    "Bitte um siebzehn kommen, nicht um vierzehn. siebzehn = seventeen; vierzehn = fourteen",
  ),
  i(
    "B",
    3,
    "ticket",
    "bounded-text",
    "This is a polite ticket request, not an announcement of intention. Correct only the request word; keep all other words and write the full sentence.",
    ["Ich möchte eine Fahrkarte kaufen."],
    "Draft: Ich will eine Fahrkarte kaufen.",
  ),
  i(
    "B",
    4,
    "room",
    "construction",
    "The note confirms a room, not its absence. Write a complete availability statement beginning Es gibt using ein Zimmer. Zimmer = room.",
    ["Es gibt ein Zimmer."],
    "Dienstag: Zimmer frei. frei = available; Dienstag = Tuesday",
  ),
  i(
    "B",
    5,
    "enquiry",
    "bounded-text",
    "You need to check a Friday arrival by bus. Repair only the article in the question; write the complete question. Freitag = Friday.",
    ["Kann ich am Freitag mit dem Bus kommen?"],
    "Draft: Kann ich am Freitag mit den Bus kommen?",
  ),
  i(
    "B",
    6,
    "relation",
    "bounded-text",
    "You are already at the bank. Rewrite only the whole statement so it gives location now, beginning Ich bin and using the reviewed bank-location chunk.",
    ["Ich bin bei der Bank."],
    "Draft: Ich gehe zur Bank.",
  ),
  i(
    "B",
    7,
    "arrival",
    "bounded-text",
    "Restore the missing prefix in the arrival question and write the whole question. Intended action: ankommen (arrive).",
    ["Wann kommt Ada an?"],
    "Draft: Wann kommt Ada ___?",
  ),
  i(
    "B",
    8,
    "message",
    "bounded-text",
    "Correct only the wrong destination in this travel reply. The new meeting is at the bank at sixteen; the station is excluded. Preserve the greeting, time and second sentence. Write the whole message.",
    ["Hallo Ada! Ich komme um sechzehn zur Bank. Das Treffen ist nicht am Bahnhof."],
    "Draft: Hallo Ada! Ich komme um sechzehn zum Bahnhof. Das Treffen ist nicht am Bahnhof.\nsechzehn = sixteen; Treffen = meeting",
  ),
  i(
    "B",
    9,
    "transfer",
    "construction",
    "The friend needs a possibility for tomorrow, not an earlier report. Say you can come tomorrow at seventeen. Begin Morgen, use ich and um siebzehn, ending kommen. siebzehn = seventeen.",
    ["Morgen kann ich um siebzehn kommen."],
  ),
]);
export const unit7CheckForms = [unit7Check, unit7CheckB] as const;
