import type { LessonStep, LessonStage } from "@/lib/curriculum/types";
// Original Karta prototype teaching, pending pedagogical review. No external tasks copied.
const G = "DE.A1.GRAMMAR.",
  R = "DE.A1.READING.",
  W = "DE.A1.WRITING.",
  V = "DE.A1.VOCABULARY.";
const role = G + "CASES.ACCUSATIVE_ROLE",
  definite = G + "CASES.ACCUSATIVE_DEFINITE",
  indefinite = G + "CASES.ACCUSATIVE_INDEFINITE",
  frames = G + "VERBS.ACCUSATIVE_FRAMES",
  sense = V + "CONTEXT_SENSE";
const kein = G + "CASES.ACCUSATIVE_KEIN",
  pronoun = G + "PRONOUNS.ACCUSATIVE",
  contrast = G + "CASES.NOM_ACC_CONTRAST",
  possessive = G + "POSSESSIVES.ACC",
  objectWriting = W + "OBJECT_PHRASE",
  message = R + "SHORT_MESSAGE";
const alternatives = G + "CONNECTORS.ABER_ODER",
  available = G + "CONSTRUCTIONS.ES_GIBT",
  chunk = V + "COLLOCATION",
  details = W + "TASK_FULFILMENT";
const preference = G + "ADVERBS.GERN_SEHR",
  focus = G + "NEGATION.FOCUS",
  frameUse = V + "FRAME_USE",
  contextWord = R + "CONTEXT_WORD";
const base = (
  lesson: number,
  id: string,
  stage: LessonStage,
  label: string,
  prompt: string,
  skillIds: string[],
) => ({
  id: `U03.L0${lesson}.${id}`,
  stage,
  purpose:
    stage === "check"
      ? ("formative-check" as const)
      : stage === "discover" || stage === "understand"
        ? ("teach" as const)
        : ("practice" as const),
  label,
  prompt,
  skillIds,
});
const explain = (
  lesson: number,
  id: string,
  stage: "discover" | "understand",
  label: string,
  prompt: string,
  example: string,
  explanation: string,
  skills: string[],
): LessonStep => ({
  ...base(lesson, id, stage, label, prompt, skills),
  kind: "explanation",
  example,
  explanation,
});
const text = (
  lesson: number,
  id: string,
  stage: LessonStage,
  label: string,
  prompt: string,
  inputLabel: string,
  acceptedAnswers: string[],
  feedback: string,
  skills: string[],
  example?: string,
): LessonStep => ({
  ...base(lesson, id, stage, label, prompt, skills),
  kind: "text",
  answerLanguage: "de",
  inputLabel,
  acceptedAnswers,
  caseSensitive: true,
  feedback,
  ...(example ? { example } : {}),
});
const choice = (
  lesson: number,
  id: string,
  stage: LessonStage,
  label: string,
  prompt: string,
  options: string[],
  correctAnswer: string,
  feedback: string,
  skills: string[],
  example?: string,
): LessonStep => ({
  ...base(lesson, id, stage, label, prompt, skills),
  kind: "choice",
  options,
  correctAnswer,
  feedback,
  ...(example ? { example } : {}),
});
export const shoppingLessonSteps: readonly LessonStep[] = [
  explain(
    1,
    "objects",
    "discover",
    "A small shopping list",
    "Notice who buys and what they buy.",
    "der Stift — pen · das Buch — book · die Tasche — bag\nAda kauft einen Stift. Ich brauche ein Buch.",
    "kaufen means buy; brauchen means need; sehen means see. The subject does the action; the direct object is the person or thing bought, needed or seen. Learn each noun with its gender. Here Tasche means a bag. In a price statement, kostet means costs; Euro is the supplied currency word: Das Buch kostet 3 Euro. Another sense of kosten is taste, but this price states a cost, not a flavour.",
    [role, frames, sense],
  ),
  explain(
    1,
    "articles",
    "understand",
    "Object articles",
    "Compare a known object with a new one.",
    "der Stift → den Stift / einen Stift\ndas Buch → das Buch / ein Buch\ndie Tasche → die Tasche / eine Tasche",
    "In these accusative object frames, masculine der/ein become den/einen. Feminine die/eine and neuter das/ein keep these forms. Compare Der Stift ist klein (subject) with Ada kauft den Stift (object). No adjective endings are needed here.",
    [role, definite, indefinite],
  ),
  choice(
    1,
    "role",
    "recognize",
    "Who buys the pen?",
    "Identify the person doing the buying.",
    ["Ada", "den Stift"],
    "Ada",
    "Ada is the subject. den Stift is the object of kauft.",
    [role],
    "Der Stift ist klein. Ada kauft den Stift.",
  ),
  choice(
    1,
    "sense",
    "recognize",
    "Choose the shopping sense",
    "Read the price. What does kostet mean here?",
    ["Costs", "Tastes"],
    "Costs",
    "The number and Euro give a price. kostet means costs in this sentence, not tastes.",
    [sense],
    "Das Buch kostet 3 Euro.",
  ),
  text(
    1,
    "known",
    "recall",
    "Retrieve the known object",
    "Complete Ich kaufe ___ Stift. It is the particular pen already shown. Type only the article.",
    "Article",
    ["den", "Ich kaufe den Stift."],
    "The known masculine object is den Stift: Ich kaufe den Stift.",
    [definite, frames],
  ),
  text(
    1,
    "new",
    "recall",
    "Name a needed object",
    "Write the German phrase ‘a pen’ as the object of brauchen. Type the article and noun.",
    "Object phrase",
    ["einen Stift", "Ich brauche einen Stift."],
    "brauchen takes the direct object: einen Stift. Masculine ein becomes einen.",
    [indefinite, frames],
  ),
  text(
    1,
    "list",
    "read",
    "Read the actual need",
    "What does Ada need now? Type only the object phrase, with its article.",
    "Needed object",
    ["ein Buch", "Ich brauche ein Buch."],
    "Ada needs ein Buch. She already has the pen; do not return the object after habe.",
    [role, indefinite],
    "Ada: Ich habe einen Stift. Ich brauche ein Buch.",
  ),
  text(
    1,
    "buy",
    "produce",
    "Make the purchase",
    "Say ‘I buy a bag’ in German. Write one complete sentence.",
    "Shopping sentence",
    ["Ich kaufe eine Tasche."],
    "Ich kaufe eine Tasche. Feminine eine remains eine as the object.",
    [indefinite, frames, sense],
  ),
  text(
    1,
    "apply",
    "apply",
    "Your own concrete need",
    "You have a book but need a pen. Say what you need in German. Write one complete sentence; leave out the book.",
    "Need sentence",
    ["Ich brauche einen Stift."],
    "Ich brauche einen Stift. The task asks for the needed object, not the object you already own.",
    [role, indefinite, frames],
  ),
  text(
    1,
    "check",
    "check",
    "A particular book",
    "Tell a friend that you see the particular book. Use ich and sehen. Write one complete German sentence.",
    "Object sentence",
    ["Ich sehe das Buch."],
    "Ich sehe das Buch. das stays das for the neuter direct object.",
    [role, definite, frames],
  ),
];
export const replacementLessonSteps: readonly LessonStep[] = [
  explain(
    2,
    "negation",
    "discover",
    "No object to buy",
    "Notice negated object phrases.",
    "Ich kaufe keinen Stift. Ich kaufe keine Tasche. Ich kaufe kein Buch.",
    "Object kein follows the accusative indefinite pattern: masculine keinen, feminine keine, neuter kein; plural keine. This denies an indefinite object, unlike nicht before a particular named object. The subject ich does not change.",
    [kein, contrast],
  ),
  explain(
    2,
    "reference",
    "understand",
    "Replace an object",
    "Keep the object role when you replace a noun.",
    "den Stift → ihn · die Tasche → sie · das Buch → es\nIch habe den Stift. Ich habe ihn.",
    "Use ihn/sie/es for these familiar singular objects; plural objects use sie. Accusative person forms are mich, dich, ihn, sie, es, uns, euch and sie; polite you is Sie. Ada sieht Ben: Ada sees, Ben is seen. Meaning and the verb's object frame determine the roles, not a guess about a word's position.",
    [pronoun, contrast],
  ),
  explain(
    2,
    "possess",
    "understand",
    "Whose object?",
    "Keep ownership and object form separate.",
    "mein Stift → meinen Stift · deine Tasche → deine Tasche · ihr Buch → ihr Buch\nIch habe deinen Stift.",
    "A taught possessive uses the same object ending pattern: mein/dein/sein/ihr/unser/Ihr gain -en before a masculine singular object, -e before a feminine one and no ending before a neuter one. If Ada says mein Buch, it is dein Buch when you reply to Ada.",
    [possessive, objectWriting],
  ),
  choice(
    2,
    "recognize",
    "recognize",
    "Replace a bag",
    "Complete the second sentence with the object pronoun.",
    ["sie", "es", "ihn"],
    "sie",
    "die Tasche is feminine, so the object replacement is sie.",
    [pronoun],
    "Ich kaufe die Tasche. Ich kaufe ___.",
  ),
  text(
    2,
    "negative",
    "recall",
    "Recall object negation",
    "Complete Ich brauche ___ Stift. You do not need a pen. Type only the negating article.",
    "Negating article",
    ["keinen", "Ich brauche keinen Stift."],
    "Masculine object negation is keinen Stift.",
    [kein],
  ),
  text(
    2,
    "possessive",
    "recall",
    "Recall ownership with an object",
    "Write the object phrase ‘my pen’ after Ich habe. Type the possessive and noun.",
    "Object phrase",
    ["meinen Stift", "Ich habe meinen Stift."],
    "Ich habe meinen Stift. Possession does not remove the masculine object ending -en.",
    [possessive, objectWriting],
  ),
  text(
    2,
    "request",
    "read",
    "Understand a short request",
    "Ada says you have her book and she needs it. What object does Ada need? Type only the phrase from her request.",
    "Requested object",
    ["mein Buch", "Ich brauche mein Buch."],
    "Ada's mein Buch is the requested object. The speaker's ownership matters when you later reply.",
    [message, contrast],
    "Ada: Du hast mein Buch. Ich brauche mein Buch.",
  ),
  text(
    2,
    "replace",
    "produce",
    "Replace the pen",
    "Rewrite Ich habe den Stift. Replace only den Stift with its object pronoun. Write the whole sentence.",
    "Replacement sentence",
    ["Ich habe ihn."],
    "Ich habe ihn. Keep ich as subject; ihn replaces the masculine object.",
    [pronoun, contrast],
  ),
  text(
    2,
    "reply",
    "apply",
    "Reply with the right owner",
    "Reply to Ben: first confirm you have his bag, using the possessive for ‘your’; then repeat that fact using its object pronoun. Write two complete German sentences, both beginning Ich habe.",
    "Two-sentence reply",
    ["Ich habe deine Tasche. Ich habe sie."],
    "Ich habe deine Tasche. Ich habe sie. Ben's meine becomes deine in your reply; feminine Tasche becomes the object pronoun sie.",
    [message, possessive, pronoun, objectWriting],
    "Ben: Du hast meine Tasche. Ich brauche meine Tasche.",
  ),
  text(
    2,
    "check",
    "check",
    "Negate a purchase",
    "Change Ich kaufe einen Stift. to say you do not buy a pen. Write the whole sentence.",
    "Negated shopping sentence",
    ["Ich kaufe keinen Stift."],
    "Ich kaufe keinen Stift. This negates an indefinite masculine object; it does not replace the subject.",
    [kein, contrast, objectWriting],
  ),
];
export const availabilityLessonSteps: readonly LessonStep[] = [
  explain(
    3,
    "available",
    "discover",
    "What is available?",
    "Use the reviewed availability chunk.",
    "Es gibt einen Stift. Es gibt ein Buch. Es gibt eine Tasche.",
    "es gibt means there is/there are in this availability pattern. What is available follows in the accusative: einen Stift, ein Buch, eine Tasche. Learn es gibt as a chunk; do not use es ist to state the shop's stock.",
    [available, chunk],
  ),
  explain(
    3,
    "alternatives",
    "understand",
    "Contrast or offer an alternative",
    "Each complete clause keeps its own verb order.",
    "Es gibt ein Buch, aber es gibt keine Tasche.\nIch kaufe ein Buch oder ich kaufe einen Stift.",
    "aber means but: a contrast. oder means or: an alternative. These connectors do not send the finite verb to the end. Each complete clause keeps its subject and finite verb in the taught order. No subordinate clause is needed.",
    [alternatives, details],
  ),
  choice(
    3,
    "form",
    "recognize",
    "An available pen",
    "Which sentence states that a pen is available?",
    ["Es gibt einen Stift.", "Es gibt ein Stift.", "Es ist einen Stift."],
    "Es gibt einen Stift.",
    "The availability chunk is es gibt and its masculine object is einen Stift.",
    [available, chunk],
  ),
  text(
    3,
    "article",
    "recall",
    "Recall the availability object",
    "Complete Es gibt ___ Buch. Type only the indefinite article.",
    "Article",
    ["ein", "Es gibt ein Buch."],
    "Es gibt ein Buch. Neuter ein stays ein in this accusative pattern.",
    [available],
  ),
  text(
    3,
    "stock",
    "read",
    "Read a shop's stock",
    "Which kind of object is not available? Type only the German noun, without an article.",
    "Unavailable object",
    ["Tasche", "Es gibt keine Tasche."],
    "Tasche is the unavailable object. The book and pen are available.",
    [available, details],
    "Es gibt ein Buch und einen Stift. Es gibt keine Tasche.",
  ),
  text(
    3,
    "chunk",
    "recall",
    "Recall the whole chunk",
    "Say ‘There is a phone’ in German. Write one complete sentence.",
    "Availability sentence",
    ["Es gibt ein Telefon."],
    "Es gibt ein Telefon. Use the fixed availability chunk and the neuter object.",
    [available, chunk],
  ),
  text(
    3,
    "contrast",
    "produce",
    "State a contrast",
    "Say a book is available but a bag is not available. Write one German sentence with two complete clauses joined by aber.",
    "Contrast sentence",
    ["Es gibt ein Buch, aber es gibt keine Tasche.", "Es gibt ein Buch aber es gibt keine Tasche."],
    "Es gibt ein Buch, aber es gibt keine Tasche. Both clauses keep es gibt and their own object.",
    [available, alternatives, details],
  ),
  text(
    3,
    "or",
    "produce",
    "Offer two purchases",
    "Say ‘I buy a book or I buy a pen’. Write one German sentence with two complete clauses joined by oder.",
    "Alternative sentence",
    ["Ich kaufe ein Buch oder ich kaufe einen Stift."],
    "Ich kaufe ein Buch oder ich kaufe einen Stift. oder keeps the second clause's ordinary verb order.",
    [alternatives, chunk],
  ),
  text(
    3,
    "reply",
    "apply",
    "Answer both required details",
    "The shopper asks about phones and bags. The shop has a phone and has no bag. Answer both details in German: two complete availability clauses joined by aber, in the phone-then-bag order.",
    "Stock reply",
    [
      "Es gibt ein Telefon, aber es gibt keine Tasche.",
      "Es gibt ein Telefon aber es gibt keine Tasche.",
    ],
    "Es gibt ein Telefon, aber es gibt keine Tasche. A reply must include both the available phone and the unavailable bag.",
    [available, alternatives, details],
  ),
  text(
    3,
    "check",
    "check",
    "A new availability reply",
    "State that a pen is available. Write one complete German sentence using the availability chunk.",
    "Availability sentence",
    ["Es gibt einen Stift."],
    "Es gibt einen Stift. The chunk takes an accusative masculine object.",
    [available, chunk, details],
  ),
];
export const preferenceLessonSteps: readonly LessonStep[] = [
  explain(
    4,
    "preference",
    "discover",
    "Preference or intensity?",
    "Match the meaning to the pattern.",
    "Ich kaufe gern Bücher.\nDer Stift ist sehr klein.",
    "gern says you enjoy doing an action; sehr strengthens an adjective here. gern does not mean buying many books. sehr klein means very small, not a preference. Keep buying/seeing/needing in their taught object frames.",
    [preference, frameUse],
  ),
  explain(
    4,
    "focus",
    "understand",
    "Correct the intended object",
    "Put nicht before the particular object you deny, then name the intended object.",
    "Ich kaufe nicht den Stift. Ich kaufe das Buch.",
    "This corrects which particular object is being bought: not that pen, but that book. nicht before den Stift focuses the correction on the object. Compare Ich kaufe keinen Stift: no pen as an indefinite category. Use two sentences here; no new connector is required.",
    [focus, frameUse],
  ),
  choice(
    4,
    "meaning",
    "recognize",
    "What does gern add?",
    "Choose the meaning of the whole statement.",
    ["I enjoy buying books.", "I buy very many books."],
    "I enjoy buying books.",
    "gern expresses enjoyment of the action; the statement does not give a quantity.",
    [preference],
    "Ich kaufe gern Bücher.",
  ),
  text(
    4,
    "gern",
    "recall",
    "Recall preference",
    "Complete Ich kaufe ___ Bücher. Say you enjoy buying books. Type only the adverb.",
    "Adverb",
    ["gern", "Ich kaufe gern Bücher."],
    "gern expresses preference for the action.",
    [preference],
  ),
  choice(
    4,
    "context",
    "read",
    "Choose a word sense in context",
    "Read the note. Which meaning of kostet fits the stated shopping detail?",
    ["Costs", "Tastes"],
    "Costs",
    "2 Euro states the price of the bag. In this context kostet is a cost, not a flavour.",
    [contextWord],
    "Die Tasche ist klein. Die Tasche kostet 2 Euro.",
  ),
  text(
    4,
    "sehr",
    "recall",
    "Recall intensity",
    "Complete Der Stift ist ___ klein. Say very small, not a preferred action. Type only the adverb.",
    "Adverb",
    ["sehr", "Der Stift ist sehr klein."],
    "sehr strengthens the description klein.",
    [preference],
  ),
  text(
    4,
    "intensity",
    "produce",
    "Add intensity",
    "Describe the particular pen as very small. Begin with Der Stift. Write one complete German sentence.",
    "Description sentence",
    ["Der Stift ist sehr klein."],
    "Der Stift ist sehr klein. sehr strengthens klein; it does not mark a preferred action.",
    [preference],
  ),
  text(
    4,
    "frame",
    "produce",
    "Use the needed-object frame",
    "Say you need the particular pen, using ich and brauchen. Write one complete German sentence.",
    "Need sentence",
    ["Ich brauche den Stift."],
    "Ich brauche den Stift. brauchen takes the accusative object den Stift.",
    [frameUse],
  ),
  text(
    4,
    "correct",
    "apply",
    "Correct the purchase, keep the preference",
    "Your enjoyment of buying books is unchanged. The draft wrongly names the particular pen as the purchase; you intend the particular book. Write three German sentences: keep the preference statement, explicitly deny buying that pen, then name the actual purchase.",
    "Corrected shopping note",
    ["Ich kaufe gern Bücher. Ich kaufe nicht den Stift. Ich kaufe das Buch."],
    "Keep gern with the action. Deny the particular wrong object using nicht den Stift, then state the actual purchase with das Buch.",
    [preference, focus, frameUse],
    "Draft: Ich kaufe gern Bücher. Ich kaufe den Stift.",
  ),
  text(
    4,
    "check",
    "check",
    "Focus a new correction",
    "You intend the particular phone, not the particular book. Write two full German sentences with ich and kaufen: first deny the named book, then name the intended phone.",
    "Focused correction",
    ["Ich kaufe nicht das Buch. Ich kaufe das Telefon."],
    "Ich kaufe nicht das Buch. Ich kaufe das Telefon. The correction targets the particular object, not your general enjoyment of shopping.",
    [focus, frameUse],
  ),
];
