import type { LessonStep } from "@/lib/curriculum/types";
import { lessonAuthor, G, R, W } from "./german-a1-batch-a-lesson";
const place = G + "PREPOSITIONS.PLACE_CHUNKS",
  frames = G + "PREPOSITIONS.DATIVE_FRAMES",
  articles = G + "CASES.DATIVE_ARTICLES",
  instruction = R + "SIMPLE_INSTRUCTION";
const a = lessonAuthor("05", 1);
export const townLessonSteps: readonly LessonStep[] = [
  a.explain(
    "scene",
    "Find the meeting point",
    "Follow a short route using supported chunks.",
    "Ich fahre mit dem Bus zum Bahnhof.\nAda ist bei der Bank.\nDas Büro ist im Zentrum.",
    "der Bus = bus; der Bahnhof = railway station; die Bank = bank; das Zentrum = centre. fahren = travel (ich fahre). mit dem Bus tells how; zum Bahnhof tells the destination; bei der Bank is near/at the bank. im Zentrum locates the office.",
    [place, frames, instruction],
  ),
  a.choice(
    "route",
    "read",
    "Choose the concrete action",
    "The note gives a transport and a destination. Select the action that follows both.",
    ["Take the bus to the station.", "Stay at the bank.", "Go to the office."],
    "Take the bus to the station.",
    "mit dem Bus is the transport and zum Bahnhof the destination.",
    [instruction, place],
    "Bitte mit dem Bus zum Bahnhof fahren. bitte = please",
  ),
  a.explain(
    "chunks",
    "Leaving and going to places",
    "Compare the meaning of these bounded route chunks.",
    "Ich komme aus dem Büro. Ich komme von der Bank.\nIch gehe zu Ada. Ich fahre nach Berlin.\nIch bin am Bahnhof.",
    "aus dem Büro = out of/from inside the office; von der Bank = from the bank as a starting point. zu Ada = to Ada; nach Berlin = to the city Berlin. am Bahnhof = at the station. Learn these as concrete chunks, not a complete preposition system.",
    [place, frames],
  ),
  a.text(
    "transport",
    "recall",
    "Retrieve the transport chunk",
    "Write the German phrase “by bus”, using the definite article. Type the whole phrase, no sentence.",
    ["mit dem Bus"],
    "mit dem Bus: the reviewed mit frame takes dem with masculine Bus.",
    [frames, articles],
  ),
  a.explain(
    "articles",
    "Articles inside familiar chunks",
    "Notice the articles and the plural noun ending.",
    "der Bus → mit dem Bus\ndie Bank → bei der Bank\ndas Büro → aus dem Büro\ndie Freunde → mit den Freunden",
    "der/das become dem, die singular becomes der; plural die becomes den in these dative frames. der Freund = friend; die Freunde = friends. The taught plural needs -n: mit den Freunden. zum = zu dem, zur = zu der; zum Bahnhof / zur Bank.",
    [frames, articles],
  ),
  a.text(
    "bank",
    "recall",
    "Remember the bank chunk",
    "Complete Ich bin bei ___ Bank. Type only the definite article.",
    ["der"],
    "bei der Bank uses der for the feminine singular noun in this frame.",
    [articles],
  ),
  a.text(
    "friends",
    "produce",
    "Say who travels with you",
    "Say “I travel with the friends”. Start Ich fahre and use the definite plural Freunde. Write one complete sentence.",
    ["Ich fahre mit den Freunden."],
    "Ich fahre mit den Freunden. Include den and the plural noun’s final -n.",
    [frames, articles],
  ),
  a.text(
    "source",
    "read",
    "Read the starting point",
    "Where does Ada come from? Copy only the phrase expressing the starting point.",
    ["aus dem Büro"],
    "aus dem Büro names the starting point; zum Bahnhof is the destination.",
    [frames, instruction],
    "Ada kommt aus dem Büro. Ada geht zum Bahnhof.",
  ),
  a.text(
    "destination",
    "apply",
    "Tell a friend your route",
    "You take the bus to the station. Begin Ich fahre. Include transport first and destination second; write the whole German sentence.",
    ["Ich fahre mit dem Bus zum Bahnhof."],
    "Ich fahre mit dem Bus zum Bahnhof. mit marks transport; zum marks this destination.",
    [place, frames, articles],
  ),
  a.text(
    "check",
    "check",
    "A new bank journey",
    "You walk to the bank. Use ich, gehen and the contracted definite destination chunk. Start Ich and write one sentence.",
    ["Ich gehe zur Bank."],
    "Ich gehe zur Bank. zur contracts zu der for the bank as destination.",
    [place, articles],
  ),
];
const pronouns = G + "PRONOUNS.DATIVE",
  help = G + "VERBS.DATIVE_FRAMES",
  register = W + "REGISTER";
const b = lessonAuthor("05", 2);
export const helpLessonSteps: readonly LessonStep[] = [
  b.explain(
    "scene",
    "Ask for help at a service desk",
    "Compare how you address a friend and a member of staff.",
    "Hallo Ada! Kannst du mir helfen?\nGuten Tag! Können Sie mir helfen?",
    "helfen = help; mir = to me in this frame. A friend is du; a member of staff you do not know is Sie. Hallo and Guten Tag are supplied greetings. Use Tschüss when saying goodbye to a friend. For a short written service request, the supplied closing Vielen Dank! means many thanks. These closings are supported here.",
    [pronouns, help, register],
  ),
  b.choice(
    "address",
    "recognize",
    "Keep the service register",
    "Choose the request to a member of staff you do not know.",
    ["Kannst du mir helfen?", "Können Sie mir helfen?"],
    "Können Sie mir helfen?",
    "Polite Sie uses können; do not mix Sie with kannst.",
    [register, help],
  ),
  b.explain(
    "people",
    "Who receives the help?",
    "Read the whole useful frame, not a pronoun table.",
    "Ich helfe dir. → one friend\nKönnen Sie uns helfen? → help us\nIch helfe euch. → a familiar group\nIch danke Ihnen. → polite thanks\nWie geht es dir? / Wie geht es Ihnen?",
    "dir = to you (du); uns = to us; euch = to you (ihr); Ihnen = to you (polite Sie). danken means thank: Ich danke dir / Ich danke Ihnen are complete natural sentences. Wie geht es …? asks how someone is; it is not a route question.",
    [pronouns, help, register],
  ),
  b.choice(
    "feeling",
    "classify",
    "A personal question",
    "What information does the question ask for?",
    ["How you are.", "Where the station is."],
    "How you are.",
    "Wie geht es Ihnen? asks how someone is, in the polite register.",
    [help, register],
    "Wie geht es Ihnen?",
  ),
  b.text(
    "us",
    "recall",
    "Recall the group receiving help",
    "You and Ada need help. Complete Können Sie ___ helfen? Type only the pronoun for us.",
    ["uns"],
    "uns names you and Ada together; mir would ask for help for you alone.",
    [pronouns, help],
  ),
  b.text(
    "group",
    "recall",
    "Help two friends",
    "Complete Ich helfe ___. You address two friends as ihr. Type only the receiving pronoun.",
    ["euch"],
    "euch refers to the familiar group; dir is one friend.",
    [pronouns, help],
  ),
  b.explain(
    "ownership",
    "Return a phone to its owner",
    "Notice a different meaning with the same kind of pronoun.",
    "Das Telefon gehört mir.\nDas Buch gehört dir.",
    "gehören = belong to. The object is the subject; the owner follows as mir/dir. Das Telefon gehört mir says it is yours, not that the phone helps you. The familiar verb ist can describe it, but belongs to uses gehört.",
    [help, pronouns],
  ),
  b.text(
    "owner",
    "produce",
    "Say the bag is yours",
    "Say “The bag belongs to me”. Use die Tasche and gehören. Start Die Tasche and write one complete sentence.",
    ["Die Tasche gehört mir."],
    "Die Tasche gehört mir. mir identifies the owner, with singular gehört.",
    [help, pronouns],
  ),
  b.text(
    "message",
    "apply",
    "Write a short service request",
    "Address a member of staff politely. Write three parts: the supplied greeting Guten Tag!, a full question asking them to help you, and the supplied closing Vielen Dank! Use Sie.",
    ["Guten Tag! Können Sie mir helfen? Vielen Dank!"],
    "Keep polite können Sie and mir; the greeting and closing complete this supported service message.",
    [help, pronouns, register],
  ),
  b.text(
    "check",
    "check",
    "Thank one friend",
    "Thank Ada directly as du. Start Ich danke and complete one German sentence.",
    ["Ich danke dir."],
    "Ich danke dir. Use dir for the friend receiving thanks, not mich or Ihnen.",
    [help, pronouns, register],
  ),
];
const relation = G + "PREPOSITIONS.LOCATION_DESTINATION",
  fields = R + "FORM_FIELDS",
  message = W + "SHORT_MESSAGE";
const c = lessonAuthor("05", 3);
export const arrivalLessonSteps: readonly LessonStep[] = [
  c.explain(
    "scene",
    "Correct a meeting point",
    "Separate where you are from where you are going.",
    "Ich bin im Zentrum. Ich gehe in die Stadt.\nIch bin am Bahnhof. Ich gehe an den Bahnhof.",
    "die Stadt = town/city. im Zentrum gives a location; in die Stadt gives a destination into town. am Bahnhof locates you at the station; an den Bahnhof describes going to the area beside the station. These are selected phrases, not mastery of all two-way prepositions.",
    [relation, message],
  ),
  c.choice(
    "where",
    "recognize",
    "Which tells your current location?",
    "Select the statement answering Wo bist du? (Where are you?).",
    ["Ich bin am Bahnhof.", "Ich gehe an den Bahnhof."],
    "Ich bin am Bahnhof.",
    "bin am names the current location; gehe an den names a destination.",
    [relation],
  ),
  c.explain(
    "destination",
    "A city or a person?",
    "Use the selected destination chunks from the route lesson.",
    "Ich fahre nach Berlin. Ich gehe zu Ada.",
    "For the city Berlin use nach Berlin; for visiting Ada use zu Ada. This is a bounded contrast, not a rule for every place name. In a note, include a specific place and time so the reader can act.",
    [relation, message],
  ),
  c.text(
    "recall",
    "recall",
    "Retrieve the city relation",
    "Complete Ich fahre ___ Berlin. Type only the destination word.",
    ["nach"],
    "nach Berlin names this city destination; zu Ada is the person chunk.",
    [relation],
  ),
  c.text(
    "destination-build",
    "produce",
    "Going into town",
    "You are going into town. Write one full sentence beginning Ich gehe and using die Stadt as the destination.",
    ["Ich gehe in die Stadt."],
    "Ich gehe in die Stadt. A destination here is in die, not the location contraction im.",
    [relation],
  ),
  c.explain(
    "form",
    "Fill the right field",
    "Read the form labels before copying information.",
    "Name: ___\nOrt: ___\nUhrzeit: ___\nDatum: ___\nAda · Bahnhof · 10 Uhr · 12. Mai",
    "Ort = place, Uhrzeit = clock time, Datum = date. Put Bahnhof under Ort and 10 Uhr under Uhrzeit. A date does not belong in the clock-time field; copying the right fact matters more than knowing a form template.",
    [fields],
  ),
  c.text(
    "field",
    "read",
    "Find the meeting time",
    "What belongs under Uhrzeit? Copy only the time, using digits and Uhr.",
    ["11 Uhr"],
    "11 Uhr is the clock time; Zentrum is the place and 14. Mai the date.",
    [fields],
    "Name: Ben. Treffen: Zentrum, 14. Mai, 11 Uhr. Treffen = meeting",
  ),
  c.choice(
    "place-field",
    "read",
    "Choose the place field",
    "Which fact belongs in Ort? Select one.",
    ["Ada", "Bank", "15 Uhr"],
    "Bank",
    "Bank is the concrete meeting place; Ada is a name and 15 Uhr a time.",
    [fields],
    "Ada: Bank, 15 Uhr.",
  ),
  c.text(
    "sms",
    "apply",
    "Write your own precise arrival note",
    "Tell Ada you are at the station now and are coming at twelve. Choose the German words yourself. Write two full sentences: first start Ich bin and give the station location; then start Um zwölf and use ich and kommen.",
    ["Ich bin am Bahnhof. Um zwölf komme ich."],
    "Ich bin am Bahnhof. Um zwölf komme ich. Give both the current place and the arrival time; do not change location into destination.",
    [relation, message],
  ),
  c.text(
    "check",
    "check",
    "A fresh location correction",
    "Your friend thinks you are going to Ada, but you are already in the centre. State only your actual location. Start Ich bin and write a complete sentence.",
    ["Ich bin im Zentrum."],
    "Ich bin im Zentrum. im gives the actual location in this supported centre chunk.",
    [relation, message],
  ),
];
const du = G + "IMPERATIVE.DU",
  ihr = G + "IMPERATIVE.IHR",
  sie = G + "IMPERATIVE.SIE",
  invite = W + "INVITATION_RESPONSE";
const d = lessonAuthor("05", 4);
export const invitationLessonSteps: readonly LessonStep[] = [
  d.explain(
    "scene",
    "Invite a friend to the centre",
    "Read an invitation with a clear time and place.",
    "Ada, komm bitte um zehn ins Zentrum!\nJa, ich komme um zehn ins Zentrum.",
    "ins Zentrum = into/to the centre, a supported destination chunk (in das). komm asks one friend to come. Ja accepts. A useful invitation and reply retain time and place. These examples introduce only the reviewed kommen and gehen instruction forms.",
    [du, invite],
  ),
  d.explain(
    "addressee",
    "One friend, a group, or a visitor?",
    "Choose the addressee before choosing the instruction.",
    "du: Komm bitte! / Geh bitte!\nihr: Kommt bitte! / Geht bitte!\nSie: Kommen Sie bitte! / Gehen Sie bitte!",
    "du instructions use komm/geh (komme/gehe are also accepted). Familiar group instructions use kommt/geht without ihr. Polite instructions keep Sie after kommen/gehen. bitte softens the request but does not change the addressee.",
    [du, ihr, sie],
  ),
  d.choice(
    "group",
    "classify",
    "Address two friends",
    "Two friends should come at eleven. Select the instruction for ihr, not du or polite Sie.",
    ["Komm bitte um elf!", "Kommt bitte um elf!", "Kommen Sie bitte um elf!"],
    "Kommt bitte um elf!",
    "Kommt addresses the familiar group without an ihr subject.",
    [ihr],
  ),
  d.text(
    "du",
    "recall",
    "Recall the instruction to a friend",
    "Complete ___ bitte! You ask one friend to go. Type only the du instruction form of gehen.",
    ["Geh", "Gehe"],
    "Geh/Gehe is for one friend; Geht is for a familiar group.",
    [du],
  ),
  d.text(
    "ihr",
    "produce",
    "Give a group a practical direction",
    "Tell two friends to go to the station, using bitte. Start with the ihr instruction of gehen, then bitte, then zum Bahnhof. Write one whole sentence.",
    ["Geht bitte zum Bahnhof!"],
    "Geht bitte zum Bahnhof! No ihr subject is needed in this familiar group instruction.",
    [ihr],
  ),
  d.text(
    "sie",
    "produce",
    "Help a visitor politely",
    "Tell a visitor politely to come at eleven. Begin Kommen Sie, then bitte, then the time. Write a complete instruction.",
    ["Kommen Sie bitte um elf!"],
    "Kommen Sie bitte um elf! Keep Sie after the verb; kommt would address familiar friends.",
    [sie],
  ),
  d.explain(
    "reply",
    "Accept or decline with useful detail",
    "A decline can give a workable alternative.",
    "Ja, ich komme um zehn ins Zentrum.\nHeute kann ich nicht kommen. Ich kann morgen um elf kommen.",
    "A yes reply confirms time and place. A no reply makes the constraint explicit and can offer another time. No subordinate clause or new tense is needed. ins Zentrum is supported in all invitation tasks here.",
    [invite],
  ),
  d.text(
    "invite",
    "produce",
    "Make a clear invitation",
    "Invite one friend to the centre at twelve. Start Komm bitte, give the time first and the supported destination ins Zentrum second. Write the complete invitation.",
    ["Komm bitte um zwölf ins Zentrum!", "Komme bitte um zwölf ins Zentrum!"],
    "Komm bitte um zwölf ins Zentrum! Use the singular invitation and include both details.",
    [du, invite],
  ),
  d.text(
    "accept",
    "apply",
    "Accept the actual invitation",
    "Accept Ada’s invitation. Write one full reply starting Ja, ich komme. Preserve both the time and the supplied destination.",
    ["Ja, ich komme um elf ins Zentrum."],
    "Ja, ich komme um elf ins Zentrum. A reply must confirm eleven, not a remembered example time.",
    [invite],
    "Ada: Komm bitte um elf ins Zentrum!",
  ),
  d.text(
    "decline",
    "apply",
    "Offer another time",
    "You cannot come today. Offer tomorrow at ten at the station instead. Write two full sentences: first Heute kann ich nicht kommen; then start Morgen kann ich and include um zehn and zum Bahnhof.",
    ["Heute kann ich nicht kommen. Morgen kann ich um zehn zum Bahnhof kommen."],
    "Keep the refusal plus a usable alternative with both time and station destination.",
    [invite],
  ),
  d.text(
    "check",
    "check",
    "A fresh polite direction",
    "Tell an unfamiliar visitor to go to the bank, politely. Begin Gehen Sie, then bitte, then the destination. Write the complete instruction.",
    ["Gehen Sie bitte zur Bank!"],
    "Gehen Sie bitte zur Bank! Use verb + Sie; zur is the reviewed destination for the bank.",
    [sie],
  ),
];
