import { checkAuthor } from "./german-a1-batch-a-check";
const { item: i, form: f } = checkAuthor("05", [
  {
    id: "route",
    label: "Use place and destination chunks",
    scope: "A bounded route instruction with a concrete destination or location.",
  },
  {
    id: "dative",
    label: "Retrieve selected dative phrases",
    scope: "A taught transport or accompaniment phrase with accurate article and noun form.",
  },
  {
    id: "pronoun",
    label: "Choose who receives help",
    scope: "Select or produce mir/dir/uns/euch/Ihnen in one familiar personal frame.",
  },
  {
    id: "help-register",
    label: "Ask for help appropriately",
    scope: "One complete help request with suitable du/Sie and supported greeting/closing.",
  },
  {
    id: "relation",
    label: "Distinguish location from destination",
    scope: "The selected station/centre/city/person relations, not all two-way prepositions.",
  },
  {
    id: "form",
    label: "Read a form field",
    scope: "Retrieve the correct place or clock-time fact from a short supplied note.",
  },
  {
    id: "instruction",
    label: "Address the right listener",
    scope: "One imperative for du, ihr or polite Sie using reviewed forms.",
  },
  {
    id: "message",
    label: "Send a usable invitation reply",
    scope: "A bounded acceptance/alternative with the requested time and place.",
  },
]);
export const unit5Check = f("A", [
  i(
    "A",
    1,
    "reading-extraction",
    "route",
    "Copy only the destination chunk from the route instruction.",
    ["zur Bank"],
    "Bitte mit dem Bus zur Bank fahren.",
  ),
  i(
    "A",
    2,
    "construction",
    "dative",
    "You come from the office with the friends. Begin Ich komme and include both the accompaniment and the starting point. Write one full sentence.",
    ["Ich komme mit den Freunden aus dem Büro.", "Ich komme aus dem Büro mit den Freunden."],
  ),
  i(
    "A",
    3,
    "bounded-text",
    "pronoun",
    "Complete Ich helfe ___. You address one friend as du. Type only the pronoun.",
    ["dir"],
  ),
  i(
    "A",
    4,
    "construction",
    "help-register",
    "Politely ask a member of staff to help you and Ada together. Write three parts: Guten Tag!, a full Sie question, then Vielen Dank!",
    ["Guten Tag! Können Sie uns helfen? Vielen Dank!"],
  ),
  i(
    "A",
    5,
    "choice",
    "relation",
    "You are already at the station, not travelling there. Select the appropriate statement.",
    ["Ich bin am Bahnhof."],
    undefined,
    ["Ich gehe an den Bahnhof.", "Ich bin am Bahnhof.", "Ich fahre nach Berlin."],
  ),
  i(
    "A",
    6,
    "reading-extraction",
    "form",
    "What belongs in the form field Ort? Copy only the place noun.",
    ["Zentrum"],
    "Name: Ada. Datum: 16. Mai. Treffen: Zentrum, 8 Uhr. Ort = place; Treffen = meeting",
  ),
  i(
    "A",
    7,
    "construction",
    "instruction",
    "Tell two friends to come to the bank at nine. Start Kommt bitte; give the time before the destination. Write one complete instruction.",
    ["Kommt bitte um neun zur Bank!"],
  ),
  i(
    "A",
    8,
    "construction",
    "message",
    "Accept Ben’s invitation. Start Ja, ich komme and confirm both time and destination in one complete sentence.",
    ["Ja, ich komme um acht zum Bahnhof."],
    "Ben: Komm bitte um acht zum Bahnhof!",
  ),
]);
export const unit5CheckB = f("B", [
  i(
    "B",
    1,
    "choice",
    "route",
    "The note says you are near the bank now, not going there. Select its location phrase.",
    ["bei der Bank"],
    undefined,
    ["zur Bank", "nach Berlin", "bei der Bank"],
  ),
  i(
    "B",
    2,
    "bounded-text",
    "dative",
    "Repair both the article and noun form in the accompaniment phrase. Preserve the whole sentence.",
    ["Ada fährt mit den Freunden."],
    "Draft: Ada fährt mit die Freunde. fahren: Ada fährt",
  ),
  i(
    "B",
    3,
    "reading-extraction",
    "pronoun",
    "Who receives the help in the second sentence? Copy only its receiving pronoun.",
    ["euch"],
    "Du und Ada: Wir brauchen Hilfe. Ben: Ich helfe euch. Hilfe = help",
  ),
  i(
    "B",
    4,
    "bounded-text",
    "help-register",
    "You address one friend, not a member of staff. Rewrite only the full question with du; keep the help directed to you.",
    ["Kannst du mir helfen?"],
    "Draft to Ada: Können Sie mir helfen?",
  ),
  i(
    "B",
    5,
    "bounded-text",
    "relation",
    "You are going into town; you are not already there. Complete Ich gehe ___. Type only the destination phrase using die Stadt.",
    ["in die Stadt"],
  ),
  i(
    "B",
    6,
    "reading-extraction",
    "form",
    "Copy only the clock-time fact for Uhrzeit, using digits and Uhr.",
    ["9 Uhr"],
    "Name: Ben. Ort: Bank. Datum: 18. Mai. Termin: 9 Uhr. Termin = appointment; Uhrzeit = clock time",
  ),
  i(
    "B",
    7,
    "bounded-text",
    "instruction",
    "The visitor needs a polite instruction, not a question. Keep bitte and the destination. Write the corrected full sentence starting Gehen Sie.",
    ["Gehen Sie bitte ins Zentrum!"],
    "Draft: Gehst du bitte ins Zentrum? ins Zentrum = into/to the centre",
  ),
  i(
    "B",
    8,
    "construction",
    "message",
    "You cannot come tomorrow. Offer Monday at twelve at the bank instead. Write two full sentences: first Morgen kann ich nicht kommen; then start Am Montag kann ich and include the time before the destination.",
    ["Morgen kann ich nicht kommen. Am Montag kann ich um zwölf zur Bank kommen."],
  ),
]);
export const unit5CheckForms = [unit5Check, unit5CheckB] as const;
