import type { LessonStep } from "@/lib/curriculum/types";
import { lessonAuthor, G, R, W, V } from "./german-a1-batch-a-lesson";
// Original Karta A1 teaching. Small supported lexicon; no external exam material.
const time = G + "PREPOSITIONS.TIME",
  v2 = G + "ORDER.FRONTED_TIME",
  plans = G + "TIME.PRESENT_PLANS",
  recall = V + "ACTIVE_RETRIEVAL",
  sequence = R + "TIME_SEQUENCE";
const a = lessonAuthor("04", 1);
export const timeLessonSteps: readonly LessonStep[] = [
  a.explain(
    "scene",
    "The course time has changed",
    "Read the old time and the new time.",
    "Der Kurs beginnt am Montag um neun.\nNeu: Der Kurs beginnt am Montag um zehn.",
    "der Kurs = course; beginnen = begin (der Kurs beginnt); neu = new. am Montag names the day, um zehn the clock time. The new course starts one hour later. vor = before; nach = after in the supported reading questions here.",
    [time, sequence],
  ),
  a.choice(
    "change",
    "read",
    "Which time is current?",
    "Select the new start time, not the old one.",
    ["Um neun.", "Um zehn."],
    "Um zehn.",
    "Neu marks the changed plan: um zehn, one hour later.",
    [sequence, time],
    "Alt: Montag, 9 Uhr. Neu: Montag, 10 Uhr. alt = old",
  ),
  a.explain(
    "opener",
    "Put the time first",
    "Notice where the verb and subject go.",
    "Am Montag komme ich später.\nUm zehn beginnt der Kurs.\nMorgen arbeite ich.",
    "später = later; morgen = tomorrow. A whole time phrase is one first position. The finite verb stays second; the subject follows it. The present describes a habit with jeden Tag (every day) or a plan with morgen; there is no new tense ending.",
    [v2, plans, recall],
  ),
  a.choice(
    "habit",
    "classify",
    "Routine or one plan?",
    "Select the statement that describes tomorrow’s plan.",
    ["Jeden Tag arbeite ich.", "Morgen arbeite ich."],
    "Morgen arbeite ich.",
    "morgen singles out tomorrow; jeden Tag describes a repeated habit.",
    [plans],
  ),
  a.explain(
    "window",
    "A useful opening window",
    "Read the opening note as familiar time chunks.",
    "Das Büro ist von neun bis zwölf offen.\nIm Mai beginnt der Kurs.",
    "offen = open; Mai = May. von neun bis zwölf gives a start and end time. im Mai names this month. Use these reviewed chunks; this is not a rule for every temporal preposition.",
    [time],
  ),
  a.text(
    "month",
    "recall",
    "Remember the month chunk",
    "Complete ___ Mai beginnt der Kurs. Type only the missing time word.",
    ["Im"],
    "For this month chunk use im Mai; sentence-initial Im is capitalized.",
    [time, recall],
  ),
  a.text(
    "order",
    "produce",
    "Build the changed start",
    "Arrange these chunks into one sentence. Start with Um zehn: der Kurs / beginnt / Um zehn.",
    ["Um zehn beginnt der Kurs."],
    "The whole time phrase comes first; beginnt is second, then der Kurs.",
    [v2, time],
  ),
  a.text(
    "before",
    "read",
    "Check the opening window",
    "The office is open von neun bis zwölf. Ada arrives um acht. Is that before or after opening? Type vor or nach.",
    ["vor"],
    "acht is before neun, so Ada is there vor the opening time.",
    [sequence],
    "Das Büro ist von neun bis zwölf offen. Ada kommt um acht.",
  ),
  a.text(
    "reply",
    "apply",
    "Send the changed plan",
    "You will come later on Monday. Write one complete German sentence beginning Am Montag, using ich, kommen and später.",
    ["Am Montag komme ich später."],
    "Am Montag komme ich später. Time opener → finite komme → subject ich.",
    [v2, time, plans],
  ),
  a.text(
    "check",
    "check",
    "A fresh work plan",
    "Tomorrow you study, rather than work. Write one complete German sentence starting Morgen, using ich and lernen.",
    ["Morgen lerne ich."],
    "Morgen lerne ich. The present and morgen express this plan; the subject follows lerne.",
    [v2, plans, recall],
  ),
];
const meaning = G + "VERBS.SEPARABLE_MEANING",
  main = G + "ORDER.SEPARABLE_MAIN",
  question = G + "ORDER.SEPARABLE_QUESTION",
  transfer = V + "TRANSFER_SELECTION",
  arrangement = W + "TIME_PLACE";
const b = lessonAuthor("04", 2);
export const prefixLessonSteps: readonly LessonStep[] = [
  b.explain(
    "scene",
    "Arrange a short call",
    "Notice the complete action, including its prefix.",
    "Ich rufe Ada um zehn an.\nAda kauft im Zentrum ein.\nIch stehe um sieben auf.",
    "anrufen = call someone; einkaufen = shop; aufstehen = get up. These three actions are enough for this lesson. In a main clause the finite verb is near the start and the prefix is last. im Zentrum = in the town centre, a supplied place chunk.",
    [meaning, main, arrangement],
  ),
  b.choice(
    "meaning",
    "recognize",
    "A call, not shopping",
    "You need to phone Ada. Select the relevant action.",
    ["anrufen", "einkaufen", "aufstehen"],
    "anrufen",
    "anrufen means phone someone; ein belongs to shopping, auf to getting up.",
    [meaning, transfer],
  ),
  b.choice(
    "statement",
    "recognize",
    "Keep the whole call",
    "Select the complete statement about phoning Ada.",
    ["Ich rufe Ada an.", "Ich rufe an Ada.", "Ich Ada anrufe."],
    "Ich rufe Ada an.",
    "rufe is finite and an is the final prefix.",
    [main],
  ),
  b.explain(
    "questions",
    "Ask about an activity",
    "Compare a yes/no question and a time question.",
    "Rufst du Ada an?\nWann rufst du Ada an?",
    "A yes/no question starts with the finite verb. A wh-question starts with Wann (when), then the finite verb and subject. an stays last in both. For shopping: Kaufst du ein? / Wo kaufst du ein?",
    [question, main],
  ),
  b.text(
    "prefix",
    "recall",
    "Retrieve the missing part",
    "You are getting up. Complete Ich stehe um acht ___. Type only the missing prefix.",
    ["auf"],
    "auf belongs to aufstehen and finishes the statement.",
    [meaning, main],
  ),
  b.text(
    "statement-build",
    "produce",
    "State the call time",
    "Arrange ich / Ada / um elf / an / rufe. Start Ich and write the whole sentence.",
    ["Ich rufe Ada um elf an.", "Ich rufe um elf Ada an."],
    "Ich rufe Ada um elf an. Keep an at the end; either reviewed time/object order is accepted.",
    [main, arrangement],
  ),
  b.text(
    "yes-no",
    "produce",
    "Ask about shopping",
    "Ask a friend whether they shop. Use du and einkaufen. Write a complete yes/no question.",
    ["Kaufst du ein?"],
    "Kaufst du ein? The finite verb starts the question; ein stays last.",
    [question],
  ),
  b.text(
    "when",
    "produce",
    "Ask when the call happens",
    "Ask a friend when they call Ada. Begin Wann and use du and anrufen. Write the complete question.",
    ["Wann rufst du Ada an?"],
    "Wann rufst du Ada an? The prefix stays last after Ada.",
    [question, transfer],
  ),
  b.text(
    "plan",
    "apply",
    "Confirm time and place",
    "You shop at eleven in the centre. Start Ich kaufe and write one complete sentence with both details. Use the supported chunk im Zentrum.",
    ["Ich kaufe um elf im Zentrum ein.", "Ich kaufe im Zentrum um elf ein."],
    "Both time and place belong inside the frame Ich kaufe … ein.",
    [main, transfer, arrangement],
  ),
  b.text(
    "check",
    "check",
    "A fresh place question",
    "Ask where a friend shops. Start Wo and use du and einkaufen. Write the complete German question.",
    ["Wo kaufst du ein?"],
    "Wo kaufst du ein? Keep ein after the subject, at the end.",
    [question, meaning],
  ),
];
const can = G + "MODALS.KOENNEN",
  wants = G + "MODALS.WANTS_REQUESTS",
  bracket = G + "ORDER.MODAL_BRACKET",
  enquiry = W + "REQUEST_INFORMATION";
const c = lessonAuthor("04", 3);
export const requestLessonSteps: readonly LessonStep[] = [
  c.explain(
    "scene",
    "At the ticket desk",
    "Distinguish possibility from a polite request.",
    "Ich kann um zehn kommen.\nIch möchte eine Fahrkarte kaufen.",
    "die Fahrkarte = ticket; kaufen is familiar. kann expresses ability or possibility, not a request. möchte makes a polite request. The infinitive kommen/kaufen stays at the end. Reviewed forms: ich kann, du kannst, wir können, Sie können; ich möchte, du möchtest, Sie möchten. With a modal, keep a separable infinitive together at the end: Ich kann einkaufen.",
    [can, wants, bracket],
  ),
  c.choice(
    "possible",
    "recognize",
    "Is it possible?",
    "The service is open and you have time. Select a statement of possibility, not intention.",
    ["Ich kann kommen.", "Ich will kommen."],
    "Ich kann kommen.",
    "kann states possibility; will says what you intend to do.",
    [can, wants],
  ),
  c.explain(
    "contrast",
    "Intention or an instruction?",
    "Notice who decides what to do.",
    "Ich will morgen arbeiten.\nIch soll um neun kommen.\nWas soll ich machen?",
    "will = my intention. soll = an instruction or expectation from someone else: for example, the office tells you a time. machen = do. Useful bounded forms: ich will / du willst; ich soll / du sollst; ich möchte / Sie möchten. Do not use these as interchangeable translations of “want”.",
    [wants, enquiry],
  ),
  c.choice(
    "polite",
    "classify",
    "Request at the desk",
    "Select the polite ticket request to a member of staff.",
    [
      "Ich möchte eine Fahrkarte kaufen.",
      "Ich soll eine Fahrkarte kaufen.",
      "Ich kann eine Fahrkarte kaufen.",
    ],
    "Ich möchte eine Fahrkarte kaufen.",
    "möchte requests the ticket; soll reports an instruction and kann reports possibility.",
    [wants],
  ),
  c.text(
    "ability",
    "recall",
    "Recall a possibility form",
    "Complete Du ___ um zehn kommen. You can come then. Type only the modal verb.",
    ["kannst"],
    "With du the reviewed possibility form is kannst; kommen stays final.",
    [can],
  ),
  c.choice(
    "instruction",
    "recognize",
    "Who set the time?",
    "The office tells you to come at nine. Select the statement reporting its instruction.",
    ["Ich will um neun kommen.", "Ich soll um neun kommen."],
    "Ich soll um neun kommen.",
    "soll reports the office’s instruction, not your own intention.",
    [wants],
  ),
  c.text(
    "bracket",
    "produce",
    "Ask if a service is possible",
    "Arrange ich / eine Fahrkarte / Kann / kaufen. Write a complete yes/no question starting Kann.",
    ["Kann ich eine Fahrkarte kaufen?"],
    "Kann ich eine Fahrkarte kaufen? The finite modal comes first; kaufen stays final.",
    [bracket, can, enquiry],
  ),
  c.text(
    "want",
    "produce",
    "State your intention",
    "You intend to study tomorrow. Use ich, wollen, morgen and lernen. Begin Ich and write one complete sentence.",
    ["Ich will morgen lernen."],
    "Ich will morgen lernen. will is intention; lernen closes the modal frame.",
    [wants, bracket],
  ),
  c.text(
    "apply",
    "apply",
    "Ask the desk about tomorrow",
    "Ask whether you can come tomorrow. Use ich, können, morgen and kommen. Write a full service question starting Kann.",
    ["Kann ich morgen kommen?"],
    "Kann ich morgen kommen? This asks about possibility, with kommen at the end.",
    [can, bracket, enquiry],
  ),
  c.text(
    "check",
    "check",
    "Clarify the instruction",
    "You do not know what the office expects. Ask “What should I do?” Use was, sollen, ich and machen. Write the complete question.",
    ["Was soll ich machen?"],
    "Was soll ich machen? This asks about an instruction, not a preference.",
    [wants, bracket, enquiry],
  ),
];
const must = G + "MODALS.MUESSEN",
  may = G + "MODALS.DUERFEN",
  detail = W + "GIVE_INFORMATION",
  notice = R + "PERMISSION_NOTICE";
const d = lessonAuthor("04", 4);
export const ruleLessonSteps: readonly LessonStep[] = [
  d.explain(
    "scene",
    "A course notice",
    "Read what is required and what is forbidden.",
    "Kurs: Du musst um neun kommen.\nDu darfst hier nicht essen.",
    "hier = here; essen is familiar. musst says an action is necessary. darfst gives permission; darfst nicht forbids it. A prohibition is not the same as “not necessary”. These are original practice notices, not legal advice.",
    [must, may, notice],
  ),
  d.choice(
    "required",
    "read",
    "What is required?",
    "Select the action required by this notice.",
    ["Come at nine.", "Eat here."],
    "Come at nine.",
    "Du musst um neun kommen requires arriving at nine. Food here is forbidden.",
    [must, notice],
    "Du musst um neun kommen. Du darfst hier nicht essen.",
  ),
  d.explain(
    "permission",
    "Permission and necessity",
    "Keep the modal meaning when changing the subject.",
    "Ich muss arbeiten. Du musst arbeiten. Wir müssen arbeiten.\nIch darf hier essen. Du darfst hier essen. Wir dürfen hier essen.",
    "muss/musst/müssen express necessity; darf/darfst/dürfen express permission. The action verb stays final in these taught frames. nicht after hier denies permission: Ich darf hier nicht essen.",
    [must, may],
  ),
  d.choice(
    "meaning",
    "classify",
    "Read permission accurately",
    "What does Du darfst hier essen communicate?",
    ["Eating here is allowed.", "Eating here is required.", "Eating here is forbidden."],
    "Eating here is allowed.",
    "darfst allows the action; it does not require it.",
    [may, notice],
  ),
  d.text(
    "must",
    "recall",
    "Recall necessity",
    "Complete Ich ___ um acht arbeiten. The work is required. Type only the modal.",
    ["muss"],
    "ich muss expresses necessity; darf would only allow it.",
    [must],
  ),
  d.text(
    "may",
    "recall",
    "Recall permission for us",
    "Complete Wir ___ hier essen. Eating here is allowed. Type only the modal.",
    ["dürfen"],
    "wir dürfen means we are allowed to; ü/ue keyboard equivalents are accepted.",
    [may],
  ),
  d.text(
    "prohibit",
    "produce",
    "State the restriction",
    "Address a friend as du. Say they may not eat here. Begin Du and write a whole sentence with dürfen, hier, nicht and essen.",
    ["Du darfst hier nicht essen."],
    "Du darfst hier nicht essen. Keep nicht: leaving it out reverses the rule.",
    [may, notice],
  ),
  d.choice(
    "alternative",
    "read",
    "Choose a workable time",
    "You cannot come before ten. Which offered appointment can you use?",
    ["Um neun.", "Um elf."],
    "Um elf.",
    "Eleven is after ten; nine conflicts with your constraint.",
    [notice, detail],
    "Büro: Du darfst um neun oder um elf kommen. Du musst vorher arbeiten. vorher = before that",
  ),
  d.text(
    "reply",
    "apply",
    "Give a constraint and an alternative",
    "You must work today, but can come tomorrow. Write two full sentences beginning Ich: first the required work with heute, then the possible visit with morgen.",
    ["Ich muss heute arbeiten. Ich kann morgen kommen."],
    "Ich muss heute arbeiten. Ich kann morgen kommen. Include both the constraint and the workable alternative.",
    [must, detail],
    "heute = today; morgen = tomorrow",
  ),
  d.text(
    "check",
    "check",
    "Read a fresh restriction",
    "Write only your permitted plan as one complete German sentence beginning Ich darf. Include the time and activity.",
    ["Ich darf um zwölf essen."],
    "Ich darf um zwölf essen. The notice allows twelve; it does not require eating.",
    [may, notice, detail],
    "Kurs: Du darfst um elf nicht essen. Du darfst um zwölf essen.",
  ),
];
