import type { LessonStep } from "@/lib/curriculum/types";
import { lessonAuthor, G, R, W, V } from "./german-a1-batch-a-lesson";
const numbers = R + "NUMERIC_DETAILS",
  times = R + "TIME_SEQUENCE",
  time = G + "PREPOSITIONS.TIME",
  modal = G + "ORDER.MODAL_BRACKET",
  numeric = V + "NUMERIC_TIME";
const a = lessonAuthor("07", 1);
export const travelTicketSteps: readonly LessonStep[] = [
  a.explain(
    "scene",
    "A departure board",
    "Read the few facts you need for the journey.",
    "Bus nach Bonn — 12. Mai, 9 Uhr. Fahrkarte: 4 Euro.",
    "Bus = bus; nach Bonn = to Bonn; Fahrkarte = ticket. The date, departure time and price are separate facts. No fare-system knowledge is needed.",
    [numbers, numeric],
  ),
  a.text(
    "date",
    "read",
    "Find the travel date",
    "Copy only the date, in the board's format.",
    ["12. Mai"],
    "12. Mai is the date; 9 Uhr is the departure time.",
    [numbers, numeric],
    "Bus nach Bonn — 12. Mai, 9 Uhr. Fahrkarte: 4 Euro.",
  ),
  a.choice(
    "price",
    "read",
    "Find the ticket price",
    "Which value is the ticket price?",
    ["9 Euro", "4 Euro", "12 Euro"],
    "4 Euro",
    "The price follows Fahrkarte, not the departure time.",
    [numbers],
    "Bus nach Bonn — 12. Mai, 9 Uhr. Fahrkarte: 4 Euro.",
  ),
  a.explain(
    "chunks",
    "Keep date and clock time apart",
    "Reuse the time chunks and a polite request frame.",
    "am 12. Mai · um neun\nIch möchte eine Fahrkarte kaufen.",
    "am introduces this calendar date; um introduces a clock time. In the request, möchte stays near the start and kaufen closes the sentence. eine Fahrkarte is a reviewed ticket phrase; you can add a supplied destination.",
    [time, modal, numeric],
  ),
  a.text(
    "recall",
    "recall",
    "Recall the clock-time chunk",
    "Write the reviewed phrase “at ten”, with zehn. Type only the two-word phrase.",
    ["um zehn"],
    "um zehn names a clock time; am is used with the reviewed day/date chunks.",
    [time, numeric],
  ),
  a.text(
    "ticket",
    "produce",
    "Ask at the counter",
    "Politely say you would like to buy a ticket to Berlin. Begin Ich and use möchten, eine Fahrkarte, nach Berlin and final kaufen.",
    [
      "Ich möchte eine Fahrkarte nach Berlin kaufen.",
      "Ich möchte nach Berlin eine Fahrkarte kaufen.",
    ],
    "The supplied destination sits inside the möchte … kaufen frame.",
    [modal],
  ),
  a.text(
    "change",
    "read",
    "Read the departure update",
    "Copy only the new departure time with digits and Uhr.",
    ["11 Uhr"],
    "11 Uhr replaces 9 Uhr; the two times are not two departures.",
    [times, numbers],
    "Bus nach Bonn: vorher 9 Uhr, jetzt 11 Uhr. vorher = before; jetzt = now",
  ),
  a.text(
    "reply",
    "apply",
    "Respond to the new time",
    "You can come at eleven, not nine. Write two separate sentences, each beginning Ich: give the possibility at eleven first, then the excluded time. Use können, um elf/um neun and final kommen.",
    ["Ich kann um elf kommen. Ich kann um neun nicht kommen."],
    "The reply confirms the new time and explicitly excludes the old one.",
    [times, time, modal],
  ),
  a.text(
    "service",
    "apply",
    "A relevant travel question",
    "Ask an unfamiliar member of staff whether you can come on 14 May. Begin Kann ich, use am 14. Mai and final kommen. Write one full question.",
    ["Kann ich am 14. Mai kommen?"],
    "The date belongs after am; kommen stays at the end of this modal question.",
    [time, modal],
  ),
  a.text(
    "check",
    "check",
    "Use a fresh travel note",
    "Read the update. Type the new clock time and the ticket price as two fields, exactly Uhrzeit: …; Preis: … . Use digits and retain Uhr/Euro.",
    ["Uhrzeit: 13 Uhr; Preis: 6 Euro"],
    "The new time is 13 Uhr, and the ticket costs 6 Euro; neither fact comes from the old departure.",
    [numbers, times, numeric],
    "Zug nach Berlin — 16. Mai. Abfahrt: alt 10 Uhr, neu 13 Uhr. Fahrkarte: 6 Euro. Zug = train; Abfahrt = departure; alt/neu = old/new",
  ),
];
const email = R + "SHORT_EMAIL",
  exists = G + "CONSTRUCTIONS.ES_GIBT",
  dative = G + "CASES.DATIVE_ARTICLES",
  enquiry = W + "REQUEST_INFORMATION",
  collocation = V + "COLLOCATION";
const b = lessonAuthor("07", 2);
export const accommodationSteps: readonly LessonStep[] = [
  b.explain(
    "scene",
    "A small accommodation enquiry",
    "Read the availability and one concrete restriction.",
    "Guten Tag! Am Freitag gibt es ein Zimmer. Bitte ab 15 Uhr kommen. Am Donnerstag gibt es kein Zimmer.",
    "Zimmer = room; ab = from. Friday has a room, Thursday does not. The arrival restriction is explicit: from three. This is a short service message, not a hotel-vocabulary list.",
    [email, exists],
  ),
  b.text(
    "day",
    "read",
    "Find the unavailable day",
    "Copy only the unavailable day phrase, including am.",
    ["Am Donnerstag", "am Donnerstag"],
    "Thursday is excluded by kein Zimmer; Friday is available.",
    [email],
    "Am Freitag gibt es ein Zimmer. Am Donnerstag gibt es kein Zimmer. Donnerstag = Thursday; Freitag = Friday",
  ),
  b.choice(
    "constraint",
    "read",
    "Keep the arrival restriction",
    "Which arrival meets the stated restriction?",
    ["At fourteen.", "At sixteen."],
    "At sixteen.",
    "ab 15 Uhr permits arrival from fifteen onwards; fourteen is too early.",
    [email],
    "Bitte ab 15 Uhr kommen. ab = from",
  ),
  b.explain(
    "availability",
    "A familiar availability frame",
    "Reuse a small set of whole phrases.",
    "Es gibt ein Zimmer.\nEs gibt kein Zimmer.\nGibt es ein Zimmer?\nKann ich mit dem Bus kommen?",
    "es gibt states availability. ein/kein Zimmer is the bounded room phrase here; Gibt es … asks about it. mit dem Bus is the already taught transport chunk, with dem. These are useful enquiries, not a new case paradigm.",
    [exists, dative, enquiry, collocation],
  ),
  b.text(
    "recall",
    "recall",
    "Retrieve the transport chunk",
    "Write the familiar phrase “by bus” with its definite article. Type only the phrase.",
    ["mit dem Bus"],
    "mit dem Bus is the reviewed transport collocation with its dative article.",
    [dative, collocation],
  ),
  b.text(
    "room",
    "produce",
    "Ask about a room",
    "Ask whether there is a room. Use es gibt as a yes/no question with ein Zimmer. Write one complete question.",
    ["Gibt es ein Zimmer?"],
    "Gibt goes first in this availability question; ein Zimmer names the requested thing.",
    [exists, enquiry],
  ),
  b.text(
    "unavailable",
    "produce",
    "Tell a friend the result",
    "Say there is no room. Begin Es gibt and use Zimmer in one full statement.",
    ["Es gibt kein Zimmer."],
    "kein Zimmer explicitly denies room availability.",
    [exists],
  ),
  b.text(
    "question",
    "apply",
    "Ask what the message leaves open",
    "The message gives a room but no arrival time. Ask when you can come. Begin Wann and use können, ich and kommen. Write one full question.",
    ["Wann kann ich kommen?"],
    "The question requests the genuinely missing time rather than repeating a stated fact.",
    [email, enquiry],
    "Guten Tag! Am Montag gibt es ein Zimmer.",
  ),
  b.text(
    "bus",
    "apply",
    "Check your arrival plan",
    "Ask whether you can arrive by bus on Friday. Begin Kann ich and place am Freitag before mit dem Bus, ending kommen.",
    ["Kann ich am Freitag mit dem Bus kommen?"],
    "The enquiry combines a reviewed date, transport chunk and possibility frame.",
    [dative, enquiry, collocation],
  ),
  b.text(
    "check",
    "check",
    "Reply to a new accommodation message",
    "The room is available on Tuesday. Ask whether you can come at seventeen on that day. Begin Kann ich, then am Dienstag, um siebzehn and final kommen. Dienstag = Tuesday.",
    ["Kann ich am Dienstag um siebzehn kommen?", "Kann ich am Dienstag um siebzehn Uhr kommen?"],
    "The new question respects Tuesday and the explicit from-sixteen constraint.",
    [email, enquiry],
    "Guten Tag! Am Dienstag gibt es ein Zimmer. Bitte ab 16 Uhr kommen. ab = from; Dienstag = Tuesday",
  ),
];
const negated = R + "NEGATED_INFORMATION",
  notice = R + "PERMISSION_NOTICE",
  prefix = G + "ORDER.SEPARABLE_QUESTION",
  place = G + "PREPOSITIONS.LOCATION_DESTINATION",
  details = W + "TIME_PLACE",
  message = W + "SHORT_MESSAGE";
const c = lessonAuthor("07", 3);
export const routeChangeSteps: readonly LessonStep[] = [
  c.explain(
    "scene",
    "A new meeting point",
    "Read what changed before choosing a route.",
    "Treffen: nicht am Bahnhof, bei der Bank. Jetzt um zwölf, nicht um zehn.",
    "Treffen = meeting. The bank replaces the station; twelve replaces ten. Both negated facts matter. am Bahnhof and bei der Bank describe location, while zum Bahnhof and zur Bank describe a destination in our reviewed frames.",
    [negated, place, details],
  ),
  c.text(
    "where",
    "read",
    "Retrieve the correct place",
    "Copy only the current location phrase, including its preposition/article.",
    ["bei der Bank"],
    "nicht am Bahnhof excludes the old place; bei der Bank is the new one.",
    [negated, place],
    "Treffen: nicht am Bahnhof, bei der Bank.",
  ),
  c.choice(
    "access",
    "read",
    "Read an access notice",
    "Which action is allowed?",
    ["Come to the bank at twelve.", "Come to the station at ten."],
    "Come to the bank at twelve.",
    "The notice explicitly forbids the old station plan and permits the bank plan.",
    [notice],
    "Du darfst um zehn nicht zum Bahnhof kommen. Du darfst um zwölf zur Bank kommen.",
  ),
  c.explain(
    "question",
    "A familiar prefix in a travel question",
    "Reuse a taught separable question frame.",
    "Wann kommst du an?\nWo kaufst du ein?",
    "ankommen = arrive; taught here as kommst … an in a question. an keeps the same final prefix position as the known einkaufen question. Only this supported arrival chunk is needed; no full new verb table.",
    [prefix],
  ),
  c.text(
    "recall",
    "recall",
    "Recall the shopping prefix",
    "Complete Wo kaufst du ___? Type only the prefix of einkaufen.",
    ["ein"],
    "ein remains at the end of the familiar place question.",
    [prefix],
  ),
  c.text(
    "arrival",
    "produce",
    "Ask a friend about arrival",
    "Ask when one friend arrives. Begin Wann and use the supported du arrival frame with ankommen. Write one full question.",
    ["Wann kommst du an?"],
    "The finite verb is second; the separable prefix closes the question.",
    [prefix],
  ),
  c.choice(
    "relation",
    "classify",
    "Place now or destination?",
    "You are already at the bank. Choose the correct update.",
    ["Ich bin bei der Bank.", "Ich gehe zur Bank."],
    "Ich bin bei der Bank.",
    "bin bei states a location now; gehe zur describes going there.",
    [place],
  ),
  c.text(
    "destination",
    "produce",
    "State the changed destination",
    "You are going to the bank at twelve. Begin Ich gehe, give the time before the destination, using um zwölf and zur Bank.",
    ["Ich gehe um zwölf zur Bank."],
    "This is a destination update, with the explicit new time.",
    [place, details],
  ),
  c.text(
    "update",
    "apply",
    "Tell a friend both changes",
    "Use the update below to correct the friend's plan. Write two independent sentences: begin Ich komme for the new time and destination; then Das Treffen ist for the excluded location. Put um elf before zur Bank.",
    ["Ich komme um elf zur Bank. Das Treffen ist nicht am Bahnhof."],
    "The first sentence states the new usable plan; the second explicitly removes the wrong place.",
    [negated, details, message, place],
    "Update: Bank, 11 Uhr. Old plan: Bahnhof, 9 Uhr. Treffen = meeting",
  ),
  c.text(
    "check",
    "check",
    "A fresh arrival message",
    "Tell Ada where and when you can come, and what changed. Write two sentences: Ich kann with um dreizehn, zum Bahnhof, final kommen; then Das Treffen ist with nicht bei der Bank. dreizehn = thirteen.",
    ["Ich kann um dreizehn zum Bahnhof kommen. Das Treffen ist nicht bei der Bank."],
    "The message preserves the new time/destination and explicitly excludes the old bank location.",
    [details, message, place, negated],
    "New plan: Bahnhof, 13 Uhr. Old place: Bank. Treffen = meeting",
  ),
];
const fulfil = W + "TASK_FULFILMENT",
  register = W + "REGISTER",
  sequence = W + "SEQUENCE",
  transfer = G + "TRANSFER.CLAUSE_FRAMES";
const d = lessonAuthor("07", 4);
export const travelMessageSteps: readonly LessonStep[] = [
  d.explain(
    "scene",
    "An update for a friend",
    "Choose the information the reader actually needs.",
    "Ada needs to know: your earlier arrival, your place now, and tomorrow's next step.",
    "Use separate short sentences. A completed event, a current location and a future possibility need different familiar frames. No subordinate clause or elaborate email template is necessary.",
    [fulfil, sequence, transfer],
  ),
  d.choice(
    "intent",
    "recognize",
    "Pick the useful past report",
    "Which sentence reports that you arrived earlier?",
    ["Ich bin gekommen.", "Ich kann morgen kommen.", "Ich bin am Bahnhof."],
    "Ich bin gekommen.",
    "bin … gekommen reports an arrival event; bin am Bahnhof gives location now.",
    [transfer, sequence],
  ),
  d.explain(
    "register",
    "Sound natural to your reader",
    "Use only a suitable opening and closing.",
    "Friend: Hallo Ada! … Bis morgen!\nStaff: Guten Tag! … Vielen Dank!",
    "Bis morgen = see you tomorrow; use it only with a tomorrow plan. A friend can receive Hallo; an unfamiliar member of staff can receive Guten Tag. The sentences in between must answer the actual request.",
    [register, message],
  ),
  d.text(
    "recall",
    "recall",
    "Retrieve a useful location",
    "You are already at the station. Recall the reviewed location phrase, starting am. Type only the phrase.",
    ["am Bahnhof"],
    "am Bahnhof describes a place now; zum Bahnhof is the destination chunk.",
    [transfer],
  ),
  d.text(
    "sequence",
    "produce",
    "Report two events in order",
    "You went to the bank, then ate. Write two independent completed-action sentences, each beginning Ich, in that order. Use zur Bank and essen.",
    ["Ich bin zur Bank gegangen. Ich habe gegessen."],
    "Each event has its own reviewed auxiliary; the sentence order communicates sequence.",
    [sequence, transfer],
  ),
  d.text(
    "constraint",
    "produce",
    "Give today's constraint",
    "You have no time today. Begin Heute and use ich and keine Zeit. Write one full statement.",
    ["Heute habe ich keine Zeit."],
    "This states current availability; no past frame is needed.",
    [transfer],
  ),
  d.choice(
    "complete",
    "apply",
    "Check the reader's requirements",
    "Ben asked where you are and when you can come. Which draft includes BOTH facts?",
    ["Ich bin im Büro. Ich kann um acht kommen.", "Ich habe gegessen. Ich habe gelernt."],
    "Ich bin im Büro. Ich kann um acht kommen.",
    "The first draft supplies place now and a next time; the second only lists events.",
    [fulfil, message],
  ),
  d.text(
    "guided",
    "apply",
    "A bounded reply to an unfamiliar host",
    "Tell the host you went to the station earlier and can come tomorrow. Use Guten Tag!, then two independent sentences starting Ich, with zum Bahnhof/gehen first and morgen/können/kommen second; close Vielen Dank!.",
    ["Guten Tag! Ich bin zum Bahnhof gegangen. Ich kann morgen kommen. Vielen Dank!"],
    "The factual sentences and the polite opening/closing serve this host, not a memorized complete template.",
    [register, sequence, transfer, fulfil],
  ),
  {
    id: "U07.L04.own",
    stage: "apply",
    purpose: "practice",
    kind: "original",
    label: "Your own wording",
    prompt:
      "Write a short update for a fictional friend: an earlier activity, your place now and a next step. Use your own words. This response is unassessed; the next task is the bounded final observation.",
    skillIds: [fulfil, message, sequence],
    maxLength: 160,
    inputLabel: "Your unassessed message",
  },
  d.text(
    "check",
    "check",
    "A new travel reply for Ada",
    "Write a fresh message with these facts: you came by bus earlier; you are at the bank now; you can come on Monday. Begin Hallo Ada!, give three independent sentences beginning Ich in that order, using mit dem Bus, bei der Bank and am Montag; close Bis bald! (see you soon).",
    [
      "Hallo Ada! Ich bin mit dem Bus gekommen. Ich bin bei der Bank. Ich kann am Montag kommen. Bis bald!",
    ],
    "All three facts and the natural friend register are present. The bounded response, not the unassessed free wording, is checked.",
    [fulfil, register, message, sequence, transfer],
  ),
];
