import type { LessonStep } from "@/lib/curriculum/types";

// Original Karta fictional form/office lesson revised to Lesson Standard v2.
// No personal data or external exam items.
const G03 = "DE.A1.GRAMMAR.VERBS.HABEN_PRESENT";
const G50 = "DE.A1.GRAMMAR.ADJECTIVES.PREDICATIVE";
const V04 = "DE.A1.VOCABULARY.NOUN_BUNDLE";
const W03 = "DE.A1.WRITING.FORM_COMPLETION";
const R03 = "DE.A1.READING.EXPLICIT_FACT";
const id = "DE.A1.U01.L04";

export const informationLessonSteps: readonly LessonStep[] = [
  {
    id: `${id}.context`,
    stage: "discover",
    purpose: "teach",
    kind: "explanation",
    label: "Give useful information",
    prompt: "At the same desk, you now need to say what you have and describe a place.",
    example: "Ich habe ein Telefon.\nDas Büro ist klein.",
    explanation:
      "Ich habe ein Telefon means ‘I have a telephone.’ Das Büro ist klein means ‘The office is small.’ You will use both patterns in short office information.",
    skillIds: [G03, G50, V04],
  },
  {
    id: `${id}.model`,
    stage: "understand",
    purpose: "teach",
    kind: "explanation",
    label: "Have and describe",
    prompt: "Notice which verb belongs to each meaning.",
    example: "Ich habe ein Telefon.\nNora hat zwei Telefone.\nDas Büro ist klein.\nDas Büro ist groß.",
    explanation:
      "Use habe with ich and hat with Nora/she when you mean ‘have’. Use ist with klein or groß to describe the office. klein means small; groß means large.",
    skillIds: [G03, G50, V04],
  },
  {
    id: `${id}.notice`,
    stage: "recognize",
    purpose: "practice",
    kind: "choice",
    label: "Choose the right meaning",
    prompt: "Which sentence says that the office is small?",
    options: ["Das Büro ist klein.", "Das Büro ist groß.", "Ich habe ein Telefon."],
    correctAnswer: "Das Büro ist klein.",
    feedback: "klein means small, so Das Büro ist klein. is the matching description.",
    skillIds: [G50],
  },
  {
    id: `${id}.controlled-have`,
    stage: "recall",
    purpose: "practice",
    kind: "text",
    answerLanguage: "de",
    label: "Complete the possession frame",
    prompt: "Complete: Ich ___ ein Telefon.",
    inputLabel: "Missing German word",
    acceptedAnswers: ["habe", "Ich habe ein Telefon."],
    feedback: "With ich, use habe: Ich habe ein Telefon.",
    skillIds: [G03],
  },
  {
    id: `${id}.read`,
    stage: "read",
    purpose: "practice",
    kind: "text",
    answerLanguage: "de",
    label: "Read an explicit fact",
    prompt: "How many telephones does Nora have? Write digits.",
    example: "Ich bin Nora. Ich habe zwei Telefone. Das Büro ist klein.",
    inputLabel: "Number",
    acceptedAnswers: ["2"],
    feedback: "zwei Telefone means two telephones. The note states the fact directly.",
    skillIds: [R03, V04],
  },
  {
    id: `${id}.supported-description`,
    stage: "produce",
    purpose: "practice",
    kind: "text",
    answerLanguage: "de",
    label: "Build a description",
    prompt: "Use all three parts to write ‘The office is large’: Das Büro · ist · groß",
    inputLabel: "German sentence",
    acceptedAnswers: ["Das Büro ist groß."],
    feedback: "Das Büro ist groß. uses ist to connect the office with the description groß.",
    skillIds: [G50, V04],
  },
  {
    id: `${id}.form-model`,
    stage: "understand",
    purpose: "teach",
    kind: "explanation",
    label: "Read a simple form before filling it",
    prompt: "Each field asks for one kind of information.",
    example: "Name: Mira\nDatum: 12.03.\nTelefone: 2",
    explanation:
      "Name asks for the person's name, Datum for the date, and Telefone for the number of telephones. Read the field label first, then copy only the matching information.",
    skillIds: [W03, R03],
  },
  {
    id: `${id}.form-name`,
    stage: "apply",
    purpose: "practice",
    kind: "text",
    answerLanguage: "de",
    label: "Fill one field",
    prompt: "Fill the Name field.",
    example: "Name: Mira\nDatum: 12.03.\nTelefone: 2",
    inputLabel: "Name",
    acceptedAnswers: ["Mira"],
    feedback: "The Name field takes Mira.",
    skillIds: [W03],
  },
  {
    id: `${id}.form-date`,
    stage: "apply",
    purpose: "practice",
    kind: "text",
    answerLanguage: "de",
    label: "Fill the next field",
    prompt: "Fill the Datum field in day.month format.",
    example: "Name: Mira\nDatum: 12.03.\nTelefone: 2",
    inputLabel: "Datum",
    acceptedAnswers: ["12.03.", "12.3."],
    feedback: "The Datum field takes 12.03.",
    skillIds: [W03],
  },
  {
    id: `${id}.independent`,
    stage: "produce",
    purpose: "practice",
    kind: "text",
    answerLanguage: "de",
    label: "Produce one useful fact",
    prompt: "Write ‘I have a telephone’ in German without a word bank.",
    inputLabel: "German sentence",
    acceptedAnswers: ["Ich habe ein Telefon."],
    feedback: "Ich habe ein Telefon. uses the possession frame from this lesson.",
    skillIds: [G03, V04],
  },
  {
    id: `${id}.transfer`,
    stage: "apply",
    purpose: "practice",
    kind: "original",
    label: "Create a short profile",
    prompt: "Write two short German sentences about a fictional person or office using patterns from this unit.",
    inputLabel: "Your two sentences",
    maxLength: 180,
    explanation:
      "For example, introduce a fictional person and add a simple possession or office description. This open writing is unassessed practice.",
    skillIds: [G03, G50, V04, W03],
  },
  {
    id: `${id}.check`,
    stage: "check",
    purpose: "formative-check",
    kind: "text",
    answerLanguage: "de",
    label: "Quick lesson check",
    prompt: "Who has a telephone? Write the name from the note.",
    example: "Ich bin Leo. Ich habe ein Telefon. Das Büro ist groß.",
    inputLabel: "Name",
    acceptedAnswers: ["Leo"],
    feedback:
      "Leo gives his name and says he has a telephone. This checks lesson reading, not proficiency.",
    skillIds: [R03, G03],
  },
];
