import { lessonAuthor } from "./german-a1-batch-a-lesson";
// Original bounded prototype practice; final assessment families are authored separately.
const a1 = lessonAuthor("10", 1);
const skills1 = [
  "DE.A1.READING.NUMERIC_DETAILS",
  "DE.A1.READING.EXPLICIT_FACT",
  "DE.A1.READING.NEGATED_INFORMATION",
  "DE.A1.READING.CONTEXT_WORD",
  "DE.A1.READING.SELECT_RELEVANT_TEXT",
];
export const unit10Lesson1Steps = [
  a1.explain(
    "scene",
    "Select useful information",
    "Read three original notes for different purposes.",
    "A: Bus nach Bonn, 8 Euro. B: Kurs in Berlin, 18 Uhr. C: Büro morgen geschlossen.",
    "geschlossen = closed. Facts are stated explicitly; do not infer an unstated service or route.",
    [skills1[0], skills1[1], skills1[4]],
  ),
  a1.choice(
    "s2",
    "recognize",
    "Match a need",
    "You need a bus price. Which note is relevant?",
    ["A", "B", "C"],
    "A",
    "Only A gives a bus price.",
    [skills1[4]],
  ),
  a1.text(
    "s3",
    "recall",
    "Retrieve a price phrase",
    "Recall the German currency word in acht … . Type only the word.",
    ["Euro"],
    "The familiar price bundle is acht Euro.",
    [skills1[0]],
  ),
  a1.text(
    "s4",
    "produce",
    "Give the needed detail",
    "From note A, say the ticket costs eight Euro. Begin Die Fahrkarte kostet.",
    ["Die Fahrkarte kostet acht Euro."],
    "A whole price statement from an explicit fact.",
    [skills1[0], skills1[1]],
  ),
  a1.choice(
    "s5",
    "classify",
    "Read a correction",
    "What is the current time?",
    ["14 Uhr", "16 Uhr"],
    "14 Uhr",
    "The former time is excluded.",
    [skills1[2]],
    "Treffen: jetzt 14 Uhr, nicht 16 Uhr.",
  ),
  a1.text(
    "s6",
    "apply",
    "Extract a new fact",
    "Copy only the place.",
    ["Bonn"],
    "Read the given fact, not the earlier lesson city.",
    [skills1[1]],
    "Kurs: Bonn. Montag, 19 Uhr.",
  ),
  a1.choice(
    "s7",
    "classify",
    "Read a familiar word in context",
    "What does frei mean in this note?",
    ["Available.", "Free of charge."],
    "Available.",
    "The note states availability; it gives no price.",
    [skills1[3]],
    "Zimmer am Dienstag frei. Zimmer = room",
  ),
  a1.text(
    "s8",
    "apply",
    "Read an excluded date",
    "Copy only the excluded day phrase beginning am.",
    ["am Freitag"],
    "Keep the explicit exclusion.",
    [skills1[2]],
    "Bitte am Samstag kommen, nicht am Freitag.",
  ),
  a1.choice(
    "s9",
    "apply",
    "Choose the complete match",
    "Need: Berlin, Wednesday, seventeen. Which note fits?",
    ["A", "B", "C"],
    "C",
    "All three requested details must match.",
    [skills1[4]],
    "A: Bonn, Mittwoch, 17 Uhr. B: Berlin, Mittwoch, 12 Uhr. C: Berlin, Mittwoch, 17 Uhr. Mittwoch = Wednesday",
  ),
  a1.text(
    "s10",
    "check",
    "Fresh reading and response",
    "New note: Bus nach Berlin, 7 Euro, Abfahrt 15 Uhr. Complete exactly Preis: …; Abfahrt: … using digits. Abfahrt = departure.",
    ["Preis: 7 Euro; Abfahrt: 15 Uhr"],
    "The two fresh facts stay in their proper fields.",
    [skills1[0], skills1[1]],
  ),
];
const a2 = lessonAuthor("10", 2);
const skills2 = [
  "DE.A1.WRITING.SIMPLE_SENTENCE",
  "DE.A1.WRITING.OBJECT_PHRASE",
  "DE.A1.WRITING.REQUEST_INFORMATION",
  "DE.A1.WRITING.GIVE_INFORMATION",
  "DE.A1.GRAMMAR.TRANSFER.CLAUSE_FRAMES",
  "DE.A1.VOCABULARY.ACTIVE_RETRIEVAL",
];
export const unit10Lesson2Steps = [
  a2.explain(
    "scene",
    "Tell, ask, respond",
    "Read the communicative situation.",
    "Ben fragt: Was brauchst du? Ada antwortet: Ich brauche einen Tisch.",
    "Tisch = table. Your aim is to give the needed object or information. There are no grammar-topic labels to select.",
    [skills2[0], skills2[1]],
  ),
  a2.choice(
    "s2",
    "recognize",
    "Find the response purpose",
    "What does Ada communicate?",
    ["A needed object.", "An earlier trip."],
    "A needed object.",
    "She states what she needs now.",
    [skills2[1]],
  ),
  a2.text(
    "s3",
    "recall",
    "Retrieve a familiar question",
    "Ask one friend when they are coming. Write a full question.",
    ["Wann kommst du?"],
    "Retrieve a useful question without a topic cue.",
    [skills2[2], skills2[5]],
  ),
  a2.text(
    "s4",
    "produce",
    "Name a needed object",
    "You need a chair. Begin Ich and use Stuhl.",
    ["Ich brauche einen Stuhl."],
    "A practical object request. Stuhl = chair.",
    [skills2[1], skills2[5]],
  ),
  a2.choice(
    "s5",
    "classify",
    "Choose the relevant time",
    "A friend asks what you did yesterday. Which reply answers?",
    ["Ich habe gelernt.", "Ich kann lernen."],
    "Ich habe gelernt.",
    "Report the completed activity, not a possibility.",
    [skills2[4]],
  ),
  a2.text(
    "s6",
    "produce",
    "Give a useful fact",
    "Tell Ben the meeting is at the bank. Begin Das Treffen ist.",
    ["Das Treffen ist bei der Bank."],
    "Give the asked-for location rather than an unrelated time.",
    [skills2[3]],
  ),
  a2.text(
    "s7",
    "apply",
    "Ask staff a missing fact",
    "The staff gives a day but no time. Ask when you can come, beginning Wann.",
    ["Wann kann ich kommen?"],
    "The question seeks the missing practical detail.",
    [skills2[2]],
  ),
  a2.text(
    "s8",
    "apply",
    "Report earlier actions",
    "Tell Ada you went to the station, then studied. Use two Ich sentences.",
    ["Ich bin zum Bahnhof gegangen. Ich habe gelernt."],
    "Both earlier activities are stated with familiar frames.",
    [skills2[4]],
  ),
  a2.text(
    "s9",
    "apply",
    "Offer a future possibility",
    "You can help tomorrow. Begin Morgen and use ich.",
    ["Morgen kann ich helfen."],
    "Time and intention determine the selected familiar frame.",
    [skills2[0], skills2[4]],
  ),
  a2.text(
    "s10",
    "check",
    "Fresh request and answer",
    "Ask a close friend if they can come Monday. Then say you need a table. Write a full Kannst du question followed by an Ich statement.",
    ["Kannst du am Montag kommen? Ich brauche einen Tisch."],
    "Independent question and object statement, with no new grammar.",
    [skills2[0], skills2[1], skills2[2], skills2[5]],
  ),
];
const a3 = lessonAuthor("10", 3);
const skills3 = [
  "DE.A1.WRITING.FORM_COMPLETION",
  "DE.A1.WRITING.TASK_FULFILMENT",
  "DE.A1.WRITING.REGISTER",
  "DE.A1.WRITING.SHORT_MESSAGE",
  "DE.A1.WRITING.SEQUENCE",
  "DE.A1.VOCABULARY.TRANSFER_SELECTION",
];
export const unit10Lesson3Steps = [
  a3.explain(
    "scene",
    "Two separate tasks",
    "Read a fictional community-course registration.",
    "Learner: Ada. City: Berlin. Meeting: Tuesday at 18 Uhr, office.",
    "Ort = place; Uhrzeit = time. The form and the message will be separate practice observations. Never use real personal details here.",
    [skills3[0], skills3[5]],
  ),
  a3.text(
    "s2",
    "produce",
    "Complete the first fields",
    "Type exactly Name: …; Ort: … from the supplied registration.",
    ["Name: Ada; Ort: Berlin"],
    "The form records supplied facts; this does not assess a message.",
    [skills3[0]],
  ),
  a3.choice(
    "s3",
    "recognize",
    "Separate the purposes",
    "Which task confirms attending?",
    ["A message.", "A name field."],
    "A message.",
    "A correctly completed form does not communicate attendance.",
    [skills3[1], skills3[3]],
  ),
  a3.text(
    "s4",
    "recall",
    "Retrieve a polite opening",
    "Recall the familiar daytime greeting for staff.",
    ["Guten Tag!"],
    "The greeting is support for register, not a reply template.",
    [skills3[2]],
  ),
  a3.text(
    "s5",
    "produce",
    "Complete a time field",
    "For the Tuesday office meeting, type only Uhrzeit: … using digits.",
    ["Uhrzeit: 18 Uhr"],
    "This is an independent time-field observation.",
    [skills3[0]],
  ),
  a3.text(
    "s6",
    "produce",
    "Give all message points",
    "Tell the staff you can come Tuesday at eighteen to the office. Begin Ich kann.",
    [
      "Ich kann am Dienstag um achtzehn ins Büro kommen.",
      "Ich kann am Dienstag um achtzehn ins Buero kommen.",
    ],
    "Day, time and destination are all required. achtzehn = eighteen.",
    [skills3[1], skills3[3]],
  ),
  a3.choice(
    "s7",
    "classify",
    "Read a missing point",
    "Which detail is missing in Ich kann am Dienstag ins Büro kommen?",
    ["Clock time.", "Day.", "Place."],
    "Clock time.",
    "The time must be supplied; form correctness cannot replace it.",
    [skills3[1]],
  ),
  a3.text(
    "s8",
    "apply",
    "Report a sequence",
    "Tell a friend you first went to the bank and then worked. Use two Ich sentences.",
    ["Ich bin zur Bank gegangen. Ich habe gearbeitet."],
    "Two completed events in the requested order.",
    [skills3[4]],
  ),
  a3.text(
    "s9",
    "apply",
    "Repair only the form",
    "Fictional person: Ben, Bonn. Fix only the reversed fields; return Name: …; Ort: … .",
    ["Name: Ben; Ort: Bonn"],
    "The revision concerns the form, not a message.",
    [skills3[0], skills3[5]],
    "Draft: Name: Bonn; Ort: Ben.",
  ),
  a3.text(
    "s10",
    "check",
    "A fresh independent message",
    "New staff meeting: Friday, eleven, bank. You can come. Write Guten Tag!, then Ich komme with all three details, and Vielen Dank!. Freitag = Friday.",
    ["Guten Tag! Ich komme am Freitag um elf zur Bank. Vielen Dank!"],
    "A new message has its own assessed points; no form result substitutes for them.",
    [skills3[1], skills3[2], skills3[3]],
  ),
];
const a4 = lessonAuthor("10", 4);
const skills4 = [
  "DE.A1.WRITING.SELF_REVISION",
  "DE.A1.GRAMMAR.TRANSFER.CLAUSE_FRAMES",
  "DE.A1.READING.MAIN_PURPOSE",
  "DE.A1.VOCABULARY.TRANSFER_SELECTION",
];
export const unit10Lesson4Steps = [
  a4.explain(
    "scene",
    "Prepare with an actual task",
    "Read this new note, then decide what needs practice.",
    "Hallo Ada! Das Treffen ist am Montag um zwölf am Bahnhof, nicht bei der Bank. Kannst du kommen?",
    "The task concerns an invitation with changed location. Reflection describes a practice need; it never supplies certification evidence.",
    [skills4[2]],
  ),
  a4.choice(
    "s2",
    "recognize",
    "Find the purpose",
    "What does Ben want?",
    ["An attendance response.", "A ticket price."],
    "An attendance response.",
    "The final question asks whether you can come.",
    [skills4[2]],
  ),
  a4.text(
    "s3",
    "recall",
    "Retrieve a location chunk",
    "From memory, give the familiar station-location phrase beginning am.",
    ["am Bahnhof"],
    "This is recall of a known location, not a new place rule.",
    [skills4[3]],
  ),
  a4.choice(
    "s4",
    "classify",
    "Match the situation",
    "You are asked about a possible future visit. Choose the useful frame.",
    ["Ich kann kommen.", "Ich bin gekommen."],
    "Ich kann kommen.",
    "Answer possibility rather than describe a completed event.",
    [skills4[1]],
  ),
  a4.text(
    "s5",
    "produce",
    "Confirm the whole plan",
    "You can come Monday at twelve to the station. Begin Ja, ich kann.",
    [
      "Ja, ich kann am Montag um zwölf zum Bahnhof kommen.",
      "Ja, ich kann am Montag um zwoelf zum Bahnhof kommen.",
    ],
    "A full reply keeps time and destination.",
    [skills4[1], skills4[3]],
  ),
  a4.text(
    "s6",
    "apply",
    "Fix the explicitly wrong time",
    "The confirmed time is twelve. Change only the wrong time; preserve everything else.",
    ["Ich komme am Montag um zwölf zum Bahnhof.", "Ich komme am Montag um zwoelf zum Bahnhof."],
    "Only the named issue changes.",
    [skills4[0]],
    "Draft: Ich komme am Montag um zehn zum Bahnhof.",
  ),
  a4.choice(
    "s7",
    "apply",
    "Locate the practice need",
    "A reply gives day/place but omits time. What should you practise?",
    ["Include the required time.", "Add medical vocabulary."],
    "Include the required time.",
    "A concrete task issue guides practice; it is not a mastery self-rating.",
    [skills4[0], skills4[3]],
  ),
  a4.text(
    "s8",
    "apply",
    "Keep a different recent event",
    "Your friend asks about yesterday: say you had no time. Begin Gestern.",
    ["Gestern hatte ich keine Zeit."],
    "Choose the familiar earlier-event frame from intention.",
    [skills4[1]],
  ),
  a4.choice(
    "s9",
    "apply",
    "Truthful checkpoint preparation",
    "Does finishing this reflection prove all final outcomes?",
    ["No. Independent observations are still needed.", "Yes. Reflection proves full A1."],
    "No. Independent observations are still needed.",
    "Practice milestones and final assessment evidence stay separate.",
    [skills4[3]],
  ),
  a4.text(
    "s10",
    "check",
    "A fresh targeted revision",
    "New confirmed visit: Wednesday at fifteen to the bank. Correct ONLY the time in the draft, keeping every other word. Mittwoch = Wednesday; fünfzehn = fifteen.",
    [
      "Ja, ich komme am Mittwoch um fünfzehn zur Bank.",
      "Ja, ich komme am Mittwoch um fuenfzehn zur Bank.",
    ],
    "This observes the concrete revision, not your self-rating.",
    [skills4[0], skills4[1]],
    "Draft: Ja, ich komme am Mittwoch um vierzehn zur Bank.",
  ),
];
