import { batchBAuthor } from "./german-a1-batch-b-assessment";
const { item: i, form: f } = batchBAuthor("U06", [
  {
    id: "frame",
    label: "Report a completed action",
    scope: "One finite auxiliary with a reviewed participle in final position.",
  },
  {
    id: "participle",
    label: "Recall a reviewed participle",
    scope: "A familiar irregular form, not an unrestricted past inventory.",
  },
  {
    id: "auxiliary",
    label: "Use a taught auxiliary frame",
    scope: "A reviewed arrival or seeing frame; no universal motion rule.",
  },
  {
    id: "email",
    label: "Read a short email",
    scope: "One explicit new arrangement or constraint.",
  },
  {
    id: "sequence",
    label: "Sequence two events",
    scope: "Two independent completed-action sentences in the requested order.",
  },
  { id: "state", label: "Explain an earlier state", scope: "A bounded war/hatte chunk." },
  {
    id: "purpose",
    label: "Recognize a changed arrangement",
    scope: "The main purpose of an explicit cancellation and alternative.",
  },
  {
    id: "transfer",
    label: "Choose the relevant frame",
    scope: "A present, completed-action or possibility frame for the stated intent.",
  },
  {
    id: "message",
    label: "Send a usable change message",
    scope: "The requested constraint and next step, in independent clauses.",
  },
  {
    id: "relevance",
    label: "Select the useful text",
    scope: "Match both the stated place and time to explicit information.",
  },
]);
export const unit6Check = f("A", [
  i(
    "A",
    1,
    "frame",
    "construction",
    "Say Ada shopped yesterday. Begin Ada, include gestern (yesterday), and use the reviewed einkaufen frame. Write one full sentence.",
    ["Ada hat gestern eingekauft."],
  ),
  i(
    "A",
    2,
    "participle",
    "bounded-text",
    "Complete Ich habe Ben ___. Use the reviewed completed-action form of sehen. Type only the participle.",
    ["gesehen"],
  ),
  i(
    "A",
    3,
    "auxiliary",
    "construction",
    "Report that Ben arrived. Begin Ben and use kommen. Write one full sentence.",
    ["Ben ist gekommen."],
  ),
  i(
    "A",
    4,
    "email",
    "reading-extraction",
    "Copy only the newly proposed meeting time, including um.",
    ["um neun"],
    "Hallo Ada! Ich habe gelernt. Ich kann morgen um neun kommen, nicht um acht. Ben",
  ),
  i(
    "A",
    5,
    "sequence",
    "construction",
    "First you worked, then you saw Ada. Write two independent completed-action sentences, each beginning Ich, in that order. Use arbeiten and sehen.",
    ["Ich habe gearbeitet. Ich habe Ada gesehen."],
  ),
  i(
    "A",
    6,
    "state",
    "construction",
    "Ben had no time earlier. Begin Er and write the reviewed earlier-state sentence with keine Zeit.",
    ["Er hatte keine Zeit."],
  ),
  i(
    "A",
    7,
    "purpose",
    "choice",
    "What is the main purpose of this note?",
    ["Cancel today and offer Thursday."],
    "Hallo Ben! Ich kann heute nicht kommen. Ich kann am Donnerstag kommen. Ada\nDonnerstag = Thursday",
    ["Report yesterday's shopping.", "Cancel today and offer Thursday.", "Ask for a book."],
  ),
  i(
    "A",
    8,
    "transfer",
    "construction",
    "A friend asks whether you can visit on Monday. You can. Begin Ich and use am Montag and kommen. Write one full sentence.",
    ["Ich kann am Montag kommen."],
  ),
  i(
    "A",
    9,
    "message",
    "construction",
    "Write a change message with three separate sentences: Es tut mir leid; then Ich with the earlier state tired; then Ich with the possibility of coming on Tuesday. müde = tired; Dienstag = Tuesday.",
    ["Es tut mir leid. Ich war müde. Ich kann am Dienstag kommen."],
  ),
  i(
    "A",
    10,
    "relevance",
    "choice",
    "You need the bank today at eleven. Which notice meets both conditions?",
    ["B"],
    "A: Bank — morgen ab 10 Uhr. B: Bank — heute ab 10 Uhr. C: Büro — heute ab 10 Uhr. ab = from",
    ["A", "B", "C"],
  ),
]);
export const unit6CheckB = f("B", [
  i(
    "B",
    1,
    "frame",
    "bounded-text",
    "Repair the word order, preserving all words. Start Heute and write the whole statement.",
    ["Heute hat Ben gelernt."],
    "Draft: Heute Ben hat gelernt.",
  ),
  i(
    "B",
    2,
    "participle",
    "bounded-text",
    "Complete Ada ist ___. Use the reviewed past form of gehen. Type only the participle.",
    ["gegangen"],
  ),
  i(
    "B",
    3,
    "auxiliary",
    "bounded-text",
    "Correct only the auxiliary and preserve the full statement.",
    ["Ada hat Ben gesehen."],
    "Draft: Ada ist Ben gesehen.",
  ),
  i(
    "B",
    4,
    "email",
    "reading-extraction",
    "Which day is explicitly excluded? Copy only the day phrase beginning am.",
    ["am Freitag"],
    "Hallo Ben! Ich kann am Donnerstag kommen. Bitte nicht am Freitag kommen. Ada\nDonnerstag = Thursday; Freitag = Friday",
  ),
  i(
    "B",
    5,
    "sequence",
    "bounded-text",
    "The order in this draft is wrong: eating happened first, arriving second. Rewrite both complete sentences in the correct order.",
    ["Ich habe gegessen. Ich bin gekommen."],
    "Draft: Ich bin gekommen. Ich habe gegessen.",
  ),
  i(
    "B",
    6,
    "state",
    "bounded-text",
    "The illness was earlier, not now. Correct only the verb and write the whole sentence.",
    ["Sie war krank."],
    "Draft: Sie ist krank. krank = sick",
  ),
  i(
    "B",
    7,
    "purpose",
    "choice",
    "Which message changes an arrangement and provides a next possibility?",
    ["A"],
    "A: Heute kann ich nicht kommen. Morgen kann ich kommen. B: Ich habe heute gegessen. C: Ich bin im Büro.",
    ["A", "B", "C"],
  ),
  i(
    "B",
    8,
    "transfer",
    "bounded-text",
    "A colleague asks what you already did yesterday. Repair the draft to report the completed work, not a possibility. Begin Gestern and preserve ich and arbeiten. gestern = yesterday.",
    ["Gestern habe ich gearbeitet."],
    "Draft: Gestern kann ich arbeiten.",
  ),
  i(
    "B",
    9,
    "message",
    "construction",
    "You cannot meet today but can visit the bank on Thursday. Write two sentences: first Heute kann ich nicht kommen; then begin Am Donnerstag kann ich and include zur Bank before kommen. Donnerstag = Thursday.",
    ["Heute kann ich nicht kommen. Am Donnerstag kann ich zur Bank kommen."],
  ),
  i(
    "B",
    10,
    "relevance",
    "choice",
    "You need the office tomorrow at ten. Select the suitable notice.",
    ["C"],
    "A: Büro — morgen ab 11 Uhr. B: Bank — morgen ab 9 Uhr. C: Büro — morgen ab 9 Uhr. ab = from",
    ["A", "B", "C"],
  ),
]);
export const unit6CheckForms = [unit6Check, unit6CheckB] as const;
