import { batchBAuthor } from "./german-a1-batch-b-assessment";
// Original independent prototype families. No lesson-final stimulus is reused.
const { item: i, form: f } = batchBAuthor("U09", [
  {
    id: "need",
    label: "Describe an everyday need",
    scope: "State a supplied ordinary need; no medical knowledge.",
  },
  { id: "notice", label: "Interpret a notice", scope: "Identify an explicitly requested action." },
  {
    id: "permission",
    label: "Read permission and prohibition",
    scope: "Preserve the stated access meaning.",
  },
  {
    id: "instruction",
    label: "Give a practical instruction",
    scope: "One correct du/Sie instruction.",
  },
  {
    id: "invite",
    label: "Invite or change a plan",
    scope: "Supply a requested invitation or alternative.",
  },
  { id: "details", label: "Keep time and place", scope: "Fulfil explicitly supplied details." },
  {
    id: "purpose",
    label: "Find a message purpose",
    scope: "Identify the sender’s requested next step.",
  },
  {
    id: "register",
    label: "Address the listener",
    scope: "A bounded response in suitable register.",
  },
  {
    id: "next",
    label: "Respond with a practical next step",
    scope: "Communicate all required response points.",
  },
]);
export const unit9Check = f("A", [
  i(
    "A",
    1,
    "need",
    "construction",
    "You need help and have no time. Write two sentences beginning Ich, with Hilfe then keine Zeit.",
    ["Ich brauche Hilfe. Ich habe keine Zeit."],
  ),
  i(
    "A",
    2,
    "notice",
    "reading-extraction",
    "Copy only the action instruction, including Sie.",
    ["Warten Sie bitte draußen!"],
    "Warten Sie bitte draußen! Das Büro öffnet um neun. draußen = outside; öffnet = opens",
  ),
  i(
    "A",
    3,
    "permission",
    "choice",
    "Which action is permitted now?",
    ["Wait at the station."],
    "Sie dürfen am Bahnhof warten. Sie dürfen jetzt nicht ins Büro gehen.",
    ["Wait at the station.", "Go into the office."],
  ),
  i(
    "A",
    4,
    "instruction",
    "construction",
    "New scenario: ask an unfamiliar visitor to go to the office politely. Begin Gehen Sie and include bitte ins Büro.",
    ["Gehen Sie bitte ins Büro!"],
  ),
  i(
    "A",
    5,
    "invite",
    "construction",
    "Invite a close friend to come tomorrow. Write a full question beginning Kannst du.",
    ["Kannst du morgen kommen?"],
  ),
  i(
    "A",
    6,
    "details",
    "bounded-text",
    "Confirm the visit: Thursday at seventeen to the station. Begin Ja, ich komme and include all three details. Donnerstag = Thursday; siebzehn = seventeen.",
    ["Ja, ich komme am Donnerstag um siebzehn zum Bahnhof."],
  ),
  i(
    "A",
    7,
    "purpose",
    "choice",
    "What response does the sender request?",
    ["Say whether you can attend."],
    "Hallo! Das Treffen ist am Dienstag um neun bei der Bank. Kannst du kommen?",
    ["Say whether you can attend.", "Give your name.", "Give a ticket price."],
  ),
  i(
    "A",
    8,
    "register",
    "construction",
    "Ask an unfamiliar member of staff to help you today. Write Guten Tag!, a full Sie question using mir/heute/helfen, then Vielen Dank!.",
    ["Guten Tag! Können Sie mir heute helfen? Vielen Dank!"],
  ),
  i(
    "A",
    9,
    "next",
    "bounded-text",
    "Tell your friend Ada you cannot come Saturday, but can come Sunday at eleven to the office. Write two Ich sentences with am Samstag / am Sonntag respectively. Samstag = Saturday; Sonntag = Sunday.",
    ["Ich kann am Samstag nicht kommen. Ich kann am Sonntag um elf ins Büro kommen."],
  ),
]);
export const unit9CheckB = f("B", [
  i(
    "B",
    1,
    "need",
    "bounded-text",
    "The ordinary need is more time, not help. Change only the noun and preserve the full statement.",
    ["Ich brauche Zeit."],
    "Draft: Ich brauche Hilfe.",
  ),
  i(
    "B",
    2,
    "notice",
    "choice",
    "What action does this sign request?",
    ["Come tomorrow."],
    "Kommen Sie bitte morgen! Heute ist das Büro geschlossen. geschlossen = closed",
    ["Come tomorrow.", "Wait inside today."],
  ),
  i(
    "B",
    3,
    "permission",
    "reading-extraction",
    "Copy only the prohibited destination phrase beginning ins.",
    ["ins Büro"],
    "Sie dürfen hier sitzen, aber Sie dürfen nicht ins Büro gehen. sitzen = sit",
  ),
  i(
    "B",
    4,
    "instruction",
    "construction",
    "Tell one close friend to wait here politely. Use a complete instruction beginning Warte; include bitte and hier.",
    ["Warte bitte hier!"],
  ),
  i(
    "B",
    5,
    "invite",
    "bounded-text",
    "Today is impossible; tomorrow is possible. Correct only the second modal, keeping both whole sentences.",
    ["Ich kann heute nicht kommen. Ich kann morgen kommen."],
    "Draft: Ich kann heute nicht kommen. Ich muss morgen kommen.",
  ),
  i(
    "B",
    6,
    "details",
    "reading-extraction",
    "Return exactly Tag: …; Ort: … from the new arrangement. Freitag = Friday.",
    ["Tag: Freitag; Ort: Bank"],
    "Treffen: Freitag, Bank, 16 Uhr. Alt: Montag, Büro. Treffen = meeting; alt = old",
  ),
  i(
    "B",
    7,
    "purpose",
    "reading-extraction",
    "Which fact is the sender asking for? Type only time or place in English.",
    ["time"],
    "Guten Tag! Der Kurs ist in Berlin. Wann können Sie kommen? Vielen Dank!",
  ),
  i(
    "B",
    8,
    "register",
    "bounded-text",
    "You are writing to close friend Ben. Change only the greeting to Hallo Ben!, preserving the full message.",
    ["Hallo Ben! Ich kann morgen kommen."],
    "Draft: Guten Tag! Ich kann morgen kommen.",
  ),
  i(
    "B",
    9,
    "next",
    "bounded-text",
    "The new visit is Monday at nineteen to the bank. Fix only the destination in the reply; preserve all other words. neunzehn = nineteen.",
    ["Guten Tag! Ich komme am Montag um neunzehn zur Bank. Vielen Dank!"],
    "Draft: Guten Tag! Ich komme am Montag um neunzehn zum Bahnhof. Vielen Dank!",
  ),
]);
export const unit9CheckForms = [unit9Check, unit9CheckB] as const;
