import {
  timeLessonSteps,
  prefixLessonSteps,
  requestLessonSteps,
  ruleLessonSteps,
} from "./german-a1-unit4";
import {
  townLessonSteps,
  helpLessonSteps,
  arrivalLessonSteps,
  invitationLessonSteps,
} from "./german-a1-unit5";
import {
  shoppingLessonSteps,
  replacementLessonSteps,
  availabilityLessonSteps,
  preferenceLessonSteps,
} from "./german-a1-unit3";
import {
  routineLessonSteps,
  belongingsLessonSteps,
  negationLessonSteps,
  revisionLessonSteps,
} from "./german-a1-unit2";
import { detailsLessonSteps } from "./german-a1-details";
import { informationLessonSteps } from "./german-a1-information";
import type { CurriculumRelease } from "@/lib/curriculum/types";
import { entityLessonSteps } from "./german-a1-entities";
import { identityLessonSteps } from "./german-a1-lesson";

/** Approved registry metadata; all twenty U01–U05 lessons have original prototype content.
 * English support is a placeholder, not a complete source-language overlay. */
export const germanA1: CurriculumRelease = {
  id: "DE.A1.CURRICULUM.PROTOTYPE.1B",
  version: "1.0.0-prototype.2",
  targetLanguage: "de",
  level: "A1",
  title: "German A1",
  status: "prototype",
  provenance: {
    origin: "Original Karta blueprint and prototype lesson; no external questions copied.",
    reviewStatus: "prototype-review",
  },
  supportLanguages: ["en"],
  skills: [
    {
      id: "DE.A1.GRAMMAR.PRONOUNS.SUBJECT",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Choose subject person/number including polite Sie",
      hardPrerequisites: [],
    },
    {
      id: "DE.A1.GRAMMAR.VERBS.SEIN_PRESENT",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Produce present sein for personal statements",
      hardPrerequisites: ["DE.A1.GRAMMAR.PRONOUNS.SUBJECT"],
    },
    {
      id: "DE.A1.GRAMMAR.VERBS.HABEN_PRESENT",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Produce present haben for possession/basic needs",
      hardPrerequisites: ["DE.A1.GRAMMAR.PRONOUNS.SUBJECT"],
    },
    {
      id: "DE.A1.GRAMMAR.VERBS.REGULAR_SINGULAR",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Produce regular ich/du/er-sie-es present forms",
      hardPrerequisites: ["DE.A1.GRAMMAR.PRONOUNS.SUBJECT"],
    },
    {
      id: "DE.A1.GRAMMAR.VERBS.PLURAL_POLITE",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Produce wir/ihr/sie/Sie present forms",
      hardPrerequisites: ["DE.A1.GRAMMAR.PRONOUNS.SUBJECT", "DE.A1.GRAMMAR.VERBS.REGULAR_SINGULAR"],
    },
    {
      id: "DE.A1.GRAMMAR.VERBS.SUBJECT_AGREEMENT",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Match finite verb to noun/pronoun subject",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.VERBS.SEIN_PRESENT",
        "DE.A1.GRAMMAR.VERBS.REGULAR_SINGULAR",
        "DE.A1.GRAMMAR.VERBS.PLURAL_POLITE",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.VERBS.STEM_CHANGE",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Use a reviewed small set of common stem-changing verbs",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.VERBS.REGULAR_SINGULAR",
        "DE.A1.GRAMMAR.VERBS.SUBJECT_AGREEMENT",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.NOUNS.GENDER",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Retrieve lexical gender, accepting unresolved/ambiguous senses",
      hardPrerequisites: [],
    },
    {
      id: "DE.A1.GRAMMAR.ARTICLES.DEFINITE_NOM",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Select der/die/das/die in subject noun phrases",
      hardPrerequisites: ["DE.A1.GRAMMAR.NOUNS.GENDER"],
    },
    {
      id: "DE.A1.GRAMMAR.ARTICLES.INDEFINITE_NOM",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Choose ein/eine/zero for familiar noun phrases",
      hardPrerequisites: ["DE.A1.GRAMMAR.NOUNS.GENDER", "DE.A1.GRAMMAR.ARTICLES.DEFINITE_NOM"],
    },
    {
      id: "DE.A1.GRAMMAR.NOUNS.PLURAL",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Use learned noun plural with appropriate agreement context",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.VERBS.PLURAL_POLITE",
        "DE.A1.GRAMMAR.NOUNS.GENDER",
        "DE.A1.GRAMMAR.ARTICLES.DEFINITE_NOM",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.CASES.NOMINATIVE_ROLE",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Identify who/what is the clause subject, without “first noun” shortcut",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.PRONOUNS.SUBJECT",
        "DE.A1.GRAMMAR.VERBS.SEIN_PRESENT",
        "DE.A1.GRAMMAR.ARTICLES.DEFINITE_NOM",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.ORDER.DECLARATIVE_V2",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Build a simple subject-first main clause with finite verb second",
      hardPrerequisites: ["DE.A1.GRAMMAR.PRONOUNS.SUBJECT", "DE.A1.GRAMMAR.VERBS.SEIN_PRESENT"],
    },
    {
      id: "DE.A1.GRAMMAR.QUESTIONS.YES_NO",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Build a yes/no question with finite verb first",
      hardPrerequisites: ["DE.A1.GRAMMAR.ORDER.DECLARATIVE_V2"],
    },
    {
      id: "DE.A1.GRAMMAR.QUESTIONS.WH",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Ask who/what/where/how with question word plus finite verb",
      hardPrerequisites: ["DE.A1.GRAMMAR.QUESTIONS.YES_NO"],
    },
    {
      id: "DE.A1.GRAMMAR.ORDER.FRONTED_TIME",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Keep V2 after a taught time phrase, moving subject after verb",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.VERBS.SUBJECT_AGREEMENT",
        "DE.A1.GRAMMAR.ORDER.DECLARATIVE_V2",
        "DE.A1.GRAMMAR.PREPOSITIONS.TIME",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.NEGATION.NICHT_CLAUSE",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Negate simple predicates/actions with nicht in taught patterns",
      hardPrerequisites: ["DE.A1.GRAMMAR.ORDER.DECLARATIVE_V2"],
    },
    {
      id: "DE.A1.GRAMMAR.NEGATION.KEIN_NOM",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Negate indefinite/zero-article subject or predicate noun phrase",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.ARTICLES.INDEFINITE_NOM",
        "DE.A1.GRAMMAR.CASES.NOMINATIVE_ROLE",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.NEGATION.NICHT_KEIN",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Select noun-phrase versus predicate negation by meaning",
      hardPrerequisites: ["DE.A1.GRAMMAR.NEGATION.NICHT_CLAUSE", "DE.A1.GRAMMAR.NEGATION.KEIN_NOM"],
    },
    {
      id: "DE.A1.GRAMMAR.POSSESSIVES.NOM",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Use mein/dein/sein/ihr/unser/Ihr in bounded nominative phrases",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.ARTICLES.DEFINITE_NOM",
        "DE.A1.GRAMMAR.ARTICLES.INDEFINITE_NOM",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.CASES.ACCUSATIVE_ROLE",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Identify a direct object in familiar reviewed verb frames",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.CASES.NOMINATIVE_ROLE",
        "DE.A1.GRAMMAR.ORDER.DECLARATIVE_V2",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.CASES.ACCUSATIVE_DEFINITE",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Produce accusative definite article, including masculine den",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.ARTICLES.DEFINITE_NOM",
        "DE.A1.GRAMMAR.CASES.ACCUSATIVE_ROLE",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.CASES.ACCUSATIVE_INDEFINITE",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Produce accusative ein/eine/einen in object phrases",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.ARTICLES.INDEFINITE_NOM",
        "DE.A1.GRAMMAR.CASES.ACCUSATIVE_ROLE",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.CASES.ACCUSATIVE_KEIN",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Produce kein/keine/keinen for negated object phrases",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.NEGATION.KEIN_NOM",
        "DE.A1.GRAMMAR.CASES.ACCUSATIVE_INDEFINITE",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.PRONOUNS.ACCUSATIVE",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Replace familiar objects with mich/dich/ihn/sie/es/uns/euch",
      hardPrerequisites: ["DE.A1.GRAMMAR.PRONOUNS.SUBJECT", "DE.A1.GRAMMAR.CASES.ACCUSATIVE_ROLE"],
    },
    {
      id: "DE.A1.GRAMMAR.CASES.NOM_ACC_CONTRAST",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Distinguish subject/object function when both nouns are present",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.CASES.NOMINATIVE_ROLE",
        "DE.A1.GRAMMAR.CASES.ACCUSATIVE_DEFINITE",
        "DE.A1.GRAMMAR.CASES.ACCUSATIVE_INDEFINITE",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.VERBS.ACCUSATIVE_FRAMES",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Use reviewed kaufen/brauchen/sehen/besuchen-type object frames",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.VERBS.HABEN_PRESENT",
        "DE.A1.GRAMMAR.VERBS.REGULAR_SINGULAR",
        "DE.A1.GRAMMAR.CASES.ACCUSATIVE_DEFINITE",
        "DE.A1.GRAMMAR.CASES.ACCUSATIVE_INDEFINITE",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.POSSESSIVES.ACC",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Inflect taught possessives in accusative noun phrases",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.POSSESSIVES.NOM",
        "DE.A1.GRAMMAR.CASES.ACCUSATIVE_INDEFINITE",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.CONNECTORS.UND",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Link words/simple complete clauses without changing V2",
      hardPrerequisites: ["DE.A1.GRAMMAR.ORDER.DECLARATIVE_V2"],
    },
    {
      id: "DE.A1.GRAMMAR.CONNECTORS.ABER_ODER",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Express simple contrast/alternatives in independent clauses",
      hardPrerequisites: ["DE.A1.GRAMMAR.CONNECTORS.UND"],
    },
    {
      id: "DE.A1.GRAMMAR.PREPOSITIONS.TIME",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Use reviewed am/um/im/von-bis time chunks",
      hardPrerequisites: ["DE.A1.GRAMMAR.ORDER.DECLARATIVE_V2"],
    },
    {
      id: "DE.A1.GRAMMAR.MODALS.KOENNEN",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Express ability/possibility with present können forms",
      hardPrerequisites: ["DE.A1.GRAMMAR.VERBS.SUBJECT_AGREEMENT"],
    },
    {
      id: "DE.A1.GRAMMAR.MODALS.MUESSEN",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Express necessity with present müssen forms",
      hardPrerequisites: ["DE.A1.GRAMMAR.VERBS.SUBJECT_AGREEMENT"],
    },
    {
      id: "DE.A1.GRAMMAR.MODALS.DUERFEN",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Express permission/prohibition with present dürfen",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.VERBS.SUBJECT_AGREEMENT",
        "DE.A1.GRAMMAR.NEGATION.NICHT_CLAUSE",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.MODALS.WANTS_REQUESTS",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Distinguish wollen intent, möchten requests and sollen instructions",
      hardPrerequisites: ["DE.A1.GRAMMAR.VERBS.SUBJECT_AGREEMENT"],
    },
    {
      id: "DE.A1.GRAMMAR.ORDER.MODAL_BRACKET",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Use finite modal plus final infinitive, including questions",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.QUESTIONS.YES_NO",
        "DE.A1.GRAMMAR.MODALS.KOENNEN",
        "DE.A1.GRAMMAR.MODALS.WANTS_REQUESTS",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.VERBS.SEPARABLE_MEANING",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Recognize reviewed separable verb and its intended meaning",
      hardPrerequisites: ["DE.A1.GRAMMAR.VERBS.REGULAR_SINGULAR"],
    },
    {
      id: "DE.A1.GRAMMAR.ORDER.SEPARABLE_MAIN",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Produce finite verb plus final prefix in main clauses",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.ORDER.DECLARATIVE_V2",
        "DE.A1.GRAMMAR.VERBS.SEPARABLE_MEANING",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.ORDER.SEPARABLE_QUESTION",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Keep prefix placement in yes/no and wh questions",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.QUESTIONS.YES_NO",
        "DE.A1.GRAMMAR.QUESTIONS.WH",
        "DE.A1.GRAMMAR.ORDER.SEPARABLE_MAIN",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.IMPERATIVE.DU",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Give a familiar singular instruction using reviewed du forms",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.VERBS.REGULAR_SINGULAR",
        "DE.A1.GRAMMAR.VERBS.STEM_CHANGE",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.IMPERATIVE.IHR",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Address a familiar group with ihr imperative",
      hardPrerequisites: ["DE.A1.GRAMMAR.VERBS.PLURAL_POLITE", "DE.A1.GRAMMAR.IMPERATIVE.DU"],
    },
    {
      id: "DE.A1.GRAMMAR.IMPERATIVE.SIE",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Make a polite instruction with verb plus Sie/bitte",
      hardPrerequisites: ["DE.A1.GRAMMAR.VERBS.PLURAL_POLITE", "DE.A1.GRAMMAR.QUESTIONS.YES_NO"],
    },
    {
      id: "DE.A1.GRAMMAR.PREPOSITIONS.PLACE_CHUNKS",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Understand/produce selected im/am/bei/nach/zu location/destination chunks",
      hardPrerequisites: ["DE.A1.GRAMMAR.ORDER.DECLARATIVE_V2", "DE.A1.GRAMMAR.PREPOSITIONS.TIME"],
    },
    {
      id: "DE.A1.GRAMMAR.PREPOSITIONS.DATIVE_FRAMES",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Use selected mit/von/zu/aus/bei frames, not every preposition",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.CASES.ACCUSATIVE_ROLE",
        "DE.A1.GRAMMAR.PREPOSITIONS.PLACE_CHUNKS",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.CASES.DATIVE_ARTICLES",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Produce dem/der/den plus required noun form in taught phrases",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.ARTICLES.DEFINITE_NOM",
        "DE.A1.GRAMMAR.NOUNS.PLURAL",
        "DE.A1.GRAMMAR.PREPOSITIONS.DATIVE_FRAMES",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.PRONOUNS.DATIVE",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Use mir/dir/uns/euch/Ihnen in selected personal/service frames",
      hardPrerequisites: ["DE.A1.GRAMMAR.PRONOUNS.SUBJECT", "DE.A1.GRAMMAR.CASES.DATIVE_ARTICLES"],
    },
    {
      id: "DE.A1.GRAMMAR.VERBS.DATIVE_FRAMES",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Use selected helfen/danken/gehören/es-geht frames by meaning",
      hardPrerequisites: ["DE.A1.GRAMMAR.VERBS.REGULAR_SINGULAR", "DE.A1.GRAMMAR.PRONOUNS.DATIVE"],
    },
    {
      id: "DE.A1.GRAMMAR.PREPOSITIONS.LOCATION_DESTINATION",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Distinguish taught im/in-die, am/an-den, nach/zu uses by relation",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.CASES.ACCUSATIVE_DEFINITE",
        "DE.A1.GRAMMAR.PREPOSITIONS.PLACE_CHUNKS",
        "DE.A1.GRAMMAR.CASES.DATIVE_ARTICLES",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.CONSTRUCTIONS.ES_GIBT",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Describe available things with es gibt plus accusative",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.CASES.ACCUSATIVE_DEFINITE",
        "DE.A1.GRAMMAR.CASES.ACCUSATIVE_INDEFINITE",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.ADJECTIVES.PREDICATIVE",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Describe people/things after sein without adjective declension",
      hardPrerequisites: ["DE.A1.GRAMMAR.VERBS.SEIN_PRESENT", "DE.A1.GRAMMAR.ORDER.DECLARATIVE_V2"],
    },
    {
      id: "DE.A1.GRAMMAR.ADVERBS.GERN_SEHR",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Express preference/intensity in reviewed simple predicates",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.VERBS.REGULAR_SINGULAR",
        "DE.A1.GRAMMAR.ORDER.DECLARATIVE_V2",
        "DE.A1.GRAMMAR.ADJECTIVES.PREDICATIVE",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.QUANTITY.NUMBER_NOUN",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Use familiar count expressions with supplied noun forms; distinguish one/several",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.ARTICLES.DEFINITE_NOM",
        "DE.A1.GRAMMAR.ARTICLES.INDEFINITE_NOM",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.TIME.PRESENT_PLANS",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Distinguish present habit/plan via taught time expressions",
      hardPrerequisites: ["DE.A1.GRAMMAR.ORDER.FRONTED_TIME", "DE.A1.GRAMMAR.PREPOSITIONS.TIME"],
    },
    {
      id: "DE.A1.GRAMMAR.NEGATION.FOCUS",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Place nicht for a taught correction/contrast without changing intent",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.NEGATION.NICHT_KEIN",
        "DE.A1.GRAMMAR.CASES.NOM_ACC_CONTRAST",
        "DE.A1.GRAMMAR.CONNECTORS.ABER_ODER",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.PAST.PERFEKT_FRAME",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Identify auxiliary/participle and produce simple Perfekt bracket",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.VERBS.SEIN_PRESENT",
        "DE.A1.GRAMMAR.VERBS.HABEN_PRESENT",
        "DE.A1.GRAMMAR.ORDER.DECLARATIVE_V2",
        "DE.A1.GRAMMAR.ORDER.MODAL_BRACKET",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.PAST.REGULAR_PARTICIPLE",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Produce reviewed regular participles including known prefix patterns",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.VERBS.SEPARABLE_MEANING",
        "DE.A1.GRAMMAR.PAST.PERFEKT_FRAME",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.PAST.COMMON_PARTICIPLE",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Recall a limited reviewed inventory of common irregular participles",
      hardPrerequisites: ["DE.A1.GRAMMAR.VERBS.STEM_CHANGE", "DE.A1.GRAMMAR.PAST.PERFEKT_FRAME"],
    },
    {
      id: "DE.A1.GRAMMAR.PAST.AUXILIARY_CHOICE",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Choose haben/sein for taught senses/frames; avoid “all motion” rule",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.PAST.PERFEKT_FRAME",
        "DE.A1.GRAMMAR.PAST.REGULAR_PARTICIPLE",
        "DE.A1.GRAMMAR.PAST.COMMON_PARTICIPLE",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.PAST.WAR_HATTE",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Use selected ich/er-sie war/hatte chunks for earlier states",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.VERBS.SEIN_PRESENT",
        "DE.A1.GRAMMAR.VERBS.HABEN_PRESENT",
        "DE.A1.GRAMMAR.PREPOSITIONS.TIME",
      ],
    },
    {
      id: "DE.A1.GRAMMAR.TRANSFER.CLAUSE_FRAMES",
      targetLanguage: "de",
      level: "A1",
      domain: "grammar",
      outcome: "Choose present/modal/Perfekt frame from an unfamiliar simple intention",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.NEGATION.NICHT_CLAUSE",
        "DE.A1.GRAMMAR.CASES.NOM_ACC_CONTRAST",
        "DE.A1.GRAMMAR.ORDER.MODAL_BRACKET",
        "DE.A1.GRAMMAR.ORDER.SEPARABLE_MAIN",
        "DE.A1.GRAMMAR.PAST.PERFEKT_FRAME",
        "DE.A1.GRAMMAR.PAST.AUXILIARY_CHOICE",
        "DE.A1.GRAMMAR.PAST.WAR_HATTE",
      ],
    },
    {
      id: "DE.A1.READING.PERSON_ENTITIES",
      targetLanguage: "de",
      level: "A1",
      domain: "reading",
      outcome: "Labels/simple personal descriptions: identify name/person/place",
      hardPrerequisites: ["DE.A1.VOCABULARY.PERSONAL_CORE"],
    },
    {
      id: "DE.A1.READING.NUMERIC_DETAILS",
      targetLanguage: "de",
      level: "A1",
      domain: "reading",
      outcome: "Signs/timetables/prices: retrieve dates, times, prices or numbers",
      hardPrerequisites: ["DE.A1.READING.PERSON_ENTITIES", "DE.A1.VOCABULARY.NUMERIC_TIME"],
    },
    {
      id: "DE.A1.READING.EXPLICIT_FACT",
      targetLanguage: "de",
      level: "A1",
      domain: "reading",
      outcome: "Very short familiar text: retrieve an explicitly stated fact",
      hardPrerequisites: ["DE.A1.READING.PERSON_ENTITIES", "DE.A1.GRAMMAR.ORDER.DECLARATIVE_V2"],
    },
    {
      id: "DE.A1.READING.REFERENCE",
      targetLanguage: "de",
      level: "A1",
      domain: "reading",
      outcome: "Short description/message: resolve an unambiguous subject/possessive reference",
      hardPrerequisites: [
        "DE.A1.READING.EXPLICIT_FACT",
        "DE.A1.GRAMMAR.PRONOUNS.SUBJECT",
        "DE.A1.GRAMMAR.POSSESSIVES.NOM",
      ],
    },
    {
      id: "DE.A1.READING.NEGATED_INFORMATION",
      targetLanguage: "de",
      level: "A1",
      domain: "reading",
      outcome: "Message/sign: distinguish a negated or corrected fact",
      hardPrerequisites: ["DE.A1.READING.EXPLICIT_FACT", "DE.A1.GRAMMAR.NEGATION.NICHT_KEIN"],
    },
    {
      id: "DE.A1.READING.SHORT_MESSAGE",
      targetLanguage: "de",
      level: "A1",
      domain: "reading",
      outcome: "Note/SMS: identify sender purpose and requested action",
      hardPrerequisites: ["DE.A1.READING.NUMERIC_DETAILS", "DE.A1.READING.EXPLICIT_FACT"],
    },
    {
      id: "DE.A1.READING.CONTEXT_WORD",
      targetLanguage: "de",
      level: "A1",
      domain: "reading",
      outcome: "Familiar sentence: select a contextually supported word sense",
      hardPrerequisites: ["DE.A1.READING.EXPLICIT_FACT", "DE.A1.VOCABULARY.CONTEXT_SENSE"],
    },
    {
      id: "DE.A1.READING.TIME_SEQUENCE",
      targetLanguage: "de",
      level: "A1",
      domain: "reading",
      outcome: "Schedule/message: distinguish before/after and a simple changed plan",
      hardPrerequisites: ["DE.A1.READING.NUMERIC_DETAILS", "DE.A1.GRAMMAR.PREPOSITIONS.TIME"],
    },
    {
      id: "DE.A1.READING.PERMISSION_NOTICE",
      targetLanguage: "de",
      level: "A1",
      domain: "reading",
      outcome: "Notice/sign: identify permitted, required or forbidden action",
      hardPrerequisites: [
        "DE.A1.READING.NEGATED_INFORMATION",
        "DE.A1.GRAMMAR.MODALS.DUERFEN",
        "DE.A1.GRAMMAR.ORDER.MODAL_BRACKET",
      ],
    },
    {
      id: "DE.A1.READING.SIMPLE_INSTRUCTION",
      targetLanguage: "de",
      level: "A1",
      domain: "reading",
      outcome: "Short familiar instruction: identify required concrete action",
      hardPrerequisites: ["DE.A1.READING.EXPLICIT_FACT", "DE.A1.GRAMMAR.PREPOSITIONS.PLACE_CHUNKS"],
    },
    {
      id: "DE.A1.READING.FORM_FIELDS",
      targetLanguage: "de",
      level: "A1",
      domain: "reading",
      outcome: "Simple form: identify which requested detail belongs in each field",
      hardPrerequisites: ["DE.A1.READING.PERSON_ENTITIES", "DE.A1.READING.NUMERIC_DETAILS"],
    },
    {
      id: "DE.A1.READING.SHORT_EMAIL",
      targetLanguage: "de",
      level: "A1",
      domain: "reading",
      outcome: "Simple email: retrieve purpose, arrangement and explicit constraint",
      hardPrerequisites: ["DE.A1.READING.SHORT_MESSAGE", "DE.A1.READING.TIME_SEQUENCE"],
    },
    {
      id: "DE.A1.READING.MAIN_PURPOSE",
      targetLanguage: "de",
      level: "A1",
      domain: "reading",
      outcome: "Very short message/notice: identify overall purpose without broad inference",
      hardPrerequisites: ["DE.A1.READING.SHORT_MESSAGE", "DE.A1.READING.SHORT_EMAIL"],
    },
    {
      id: "DE.A1.READING.SELECT_RELEVANT_TEXT",
      targetLanguage: "de",
      level: "A1",
      domain: "reading",
      outcome: "Small set of simple ads/signs: choose text satisfying a stated need",
      hardPrerequisites: [
        "DE.A1.READING.NUMERIC_DETAILS",
        "DE.A1.READING.NEGATED_INFORMATION",
        "DE.A1.READING.MAIN_PURPOSE",
      ],
    },
    {
      id: "DE.A1.WRITING.PERSONAL_FACT",
      targetLanguage: "de",
      level: "A1",
      domain: "writing",
      outcome: "Write own name/basic identity phrase independently",
      hardPrerequisites: ["DE.A1.VOCABULARY.PERSONAL_CORE", "DE.A1.GRAMMAR.VERBS.SEIN_PRESENT"],
    },
    {
      id: "DE.A1.WRITING.ORTHOGRAPHY",
      targetLanguage: "de",
      level: "A1",
      domain: "writing",
      outcome: "Use basic sentence capitals, noun capitals and readable spelling in short phrases",
      hardPrerequisites: ["DE.A1.WRITING.PERSONAL_FACT", "DE.A1.GRAMMAR.ARTICLES.DEFINITE_NOM"],
    },
    {
      id: "DE.A1.WRITING.FORM_COMPLETION",
      targetLanguage: "de",
      level: "A1",
      domain: "writing",
      outcome: "Fill simple identity/contact/date fields from a new scenario",
      hardPrerequisites: ["DE.A1.WRITING.PERSONAL_FACT", "DE.A1.READING.NUMERIC_DETAILS"],
    },
    {
      id: "DE.A1.WRITING.SIMPLE_SENTENCE",
      targetLanguage: "de",
      level: "A1",
      domain: "writing",
      outcome: "Produce a simple statement with subject/finite verb agreement",
      hardPrerequisites: [
        "DE.A1.GRAMMAR.VERBS.SUBJECT_AGREEMENT",
        "DE.A1.GRAMMAR.ORDER.DECLARATIVE_V2",
        "DE.A1.WRITING.ORTHOGRAPHY",
      ],
    },
    {
      id: "DE.A1.WRITING.DESCRIPTION",
      targetLanguage: "de",
      level: "A1",
      domain: "writing",
      outcome: "Write simple personal/home/routine description, not a memorized paragraph",
      hardPrerequisites: [
        "DE.A1.WRITING.SIMPLE_SENTENCE",
        "DE.A1.GRAMMAR.POSSESSIVES.NOM",
        "DE.A1.GRAMMAR.ADJECTIVES.PREDICATIVE",
      ],
    },
    {
      id: "DE.A1.WRITING.OBJECT_PHRASE",
      targetLanguage: "de",
      level: "A1",
      domain: "writing",
      outcome: "Use article/case and vocabulary appropriately in a needed object phrase",
      hardPrerequisites: [
        "DE.A1.WRITING.SIMPLE_SENTENCE",
        "DE.A1.GRAMMAR.CASES.NOM_ACC_CONTRAST",
        "DE.A1.GRAMMAR.POSSESSIVES.ACC",
      ],
    },
    {
      id: "DE.A1.WRITING.TASK_FULFILMENT",
      targetLanguage: "de",
      level: "A1",
      domain: "writing",
      outcome: "Communicate all requested basic details without copying a template",
      hardPrerequisites: ["DE.A1.WRITING.SIMPLE_SENTENCE", "DE.A1.READING.SHORT_MESSAGE"],
    },
    {
      id: "DE.A1.WRITING.TIME_PLACE",
      targetLanguage: "de",
      level: "A1",
      domain: "writing",
      outcome: "State a practical time/place arrangement unambiguously",
      hardPrerequisites: [
        "DE.A1.WRITING.SIMPLE_SENTENCE",
        "DE.A1.GRAMMAR.PREPOSITIONS.TIME",
        "DE.A1.GRAMMAR.PREPOSITIONS.PLACE_CHUNKS",
      ],
    },
    {
      id: "DE.A1.WRITING.REQUEST_INFORMATION",
      targetLanguage: "de",
      level: "A1",
      domain: "writing",
      outcome: "Ask a simple relevant question/request about a service or plan",
      hardPrerequisites: [
        "DE.A1.WRITING.SIMPLE_SENTENCE",
        "DE.A1.GRAMMAR.QUESTIONS.WH",
        "DE.A1.GRAMMAR.MODALS.WANTS_REQUESTS",
        "DE.A1.GRAMMAR.ORDER.MODAL_BRACKET",
      ],
    },
    {
      id: "DE.A1.WRITING.GIVE_INFORMATION",
      targetLanguage: "de",
      level: "A1",
      domain: "writing",
      outcome: "Respond with needed detail and a simple constraint or alternative",
      hardPrerequisites: [
        "DE.A1.WRITING.TASK_FULFILMENT",
        "DE.A1.GRAMMAR.CONNECTORS.ABER_ODER",
        "DE.A1.GRAMMAR.ORDER.MODAL_BRACKET",
      ],
    },
    {
      id: "DE.A1.WRITING.REGISTER",
      targetLanguage: "de",
      level: "A1",
      domain: "writing",
      outcome: "Use suitable du/Sie address, greeting and closing in a short message",
      hardPrerequisites: [
        "DE.A1.WRITING.TASK_FULFILMENT",
        "DE.A1.GRAMMAR.POSSESSIVES.NOM",
        "DE.A1.GRAMMAR.IMPERATIVE.SIE",
      ],
    },
    {
      id: "DE.A1.WRITING.SHORT_MESSAGE",
      targetLanguage: "de",
      level: "A1",
      domain: "writing",
      outcome: "Compose a short original practical note/SMS for a stated recipient",
      hardPrerequisites: ["DE.A1.WRITING.TASK_FULFILMENT", "DE.A1.WRITING.TIME_PLACE"],
    },
    {
      id: "DE.A1.WRITING.INVITATION_RESPONSE",
      targetLanguage: "de",
      level: "A1",
      domain: "writing",
      outcome: "Invite/accept/decline with needed time/place, using simple taught forms",
      hardPrerequisites: [
        "DE.A1.WRITING.REQUEST_INFORMATION",
        "DE.A1.WRITING.GIVE_INFORMATION",
        "DE.A1.WRITING.SHORT_MESSAGE",
      ],
    },
    {
      id: "DE.A1.WRITING.SEQUENCE",
      targetLanguage: "de",
      level: "A1",
      domain: "writing",
      outcome: "Convey simple order/past-versus-plan across short independent sentences",
      hardPrerequisites: [
        "DE.A1.WRITING.SIMPLE_SENTENCE",
        "DE.A1.GRAMMAR.TIME.PRESENT_PLANS",
        "DE.A1.GRAMMAR.PAST.PERFEKT_FRAME",
        "DE.A1.GRAMMAR.PAST.AUXILIARY_CHOICE",
      ],
    },
    {
      id: "DE.A1.WRITING.APOLOGY_CHANGE",
      targetLanguage: "de",
      level: "A1",
      domain: "writing",
      outcome: "Apologize/cancel/change an arrangement and offer a relevant next step",
      hardPrerequisites: [
        "DE.A1.WRITING.GIVE_INFORMATION",
        "DE.A1.WRITING.REGISTER",
        "DE.A1.WRITING.SHORT_MESSAGE",
      ],
    },
    {
      id: "DE.A1.WRITING.SELF_REVISION",
      targetLanguage: "de",
      level: "A1",
      domain: "writing",
      outcome: "Improve an identified error using a bounded checklist without copying the answer",
      hardPrerequisites: [
        "DE.A1.WRITING.SIMPLE_SENTENCE",
        "DE.A1.GRAMMAR.NEGATION.NICHT_KEIN",
        "DE.A1.GRAMMAR.CONNECTORS.UND",
      ],
    },
    {
      id: "DE.A1.VOCABULARY.PERSONAL_CORE",
      targetLanguage: "de",
      level: "A1",
      domain: "vocabulary",
      outcome: "Understand/use a reviewed core of identity/greeting/contact senses",
      hardPrerequisites: [],
    },
    {
      id: "DE.A1.VOCABULARY.ENTITY_CATEGORIES",
      targetLanguage: "de",
      level: "A1",
      domain: "vocabulary",
      outcome: "Recognize person/place/object meanings in familiar language",
      hardPrerequisites: ["DE.A1.VOCABULARY.PERSONAL_CORE"],
    },
    {
      id: "DE.A1.VOCABULARY.NUMERIC_TIME",
      targetLanguage: "de",
      level: "A1",
      domain: "vocabulary",
      outcome: "Understand/use taught numbers, prices, dates and everyday time labels",
      hardPrerequisites: ["DE.A1.VOCABULARY.PERSONAL_CORE"],
    },
    {
      id: "DE.A1.VOCABULARY.NOUN_BUNDLE",
      targetLanguage: "de",
      level: "A1",
      domain: "vocabulary",
      outcome: "Retrieve taught noun sense with gender/plural metadata when relevant",
      hardPrerequisites: ["DE.A1.VOCABULARY.ENTITY_CATEGORIES"],
    },
    {
      id: "DE.A1.VOCABULARY.ACTION_SENSE",
      targetLanguage: "de",
      level: "A1",
      domain: "vocabulary",
      outcome: "Choose taught everyday action sense rather than translation alone",
      hardPrerequisites: ["DE.A1.VOCABULARY.ENTITY_CATEGORIES"],
    },
    {
      id: "DE.A1.VOCABULARY.CONTEXT_SENSE",
      targetLanguage: "de",
      level: "A1",
      domain: "vocabulary",
      outcome: "Distinguish familiar competing senses/glosses in a concrete context",
      hardPrerequisites: ["DE.A1.VOCABULARY.ACTION_SENSE"],
    },
    {
      id: "DE.A1.VOCABULARY.COLLOCATION",
      targetLanguage: "de",
      level: "A1",
      domain: "vocabulary",
      outcome: "Use a reviewed common word partnership/chunk appropriately",
      hardPrerequisites: ["DE.A1.VOCABULARY.NOUN_BUNDLE", "DE.A1.VOCABULARY.ACTION_SENSE"],
    },
    {
      id: "DE.A1.VOCABULARY.FRAME_USE",
      targetLanguage: "de",
      level: "A1",
      domain: "vocabulary",
      outcome: "Supply a taught verb/preposition/object frame for a needed meaning",
      hardPrerequisites: ["DE.A1.VOCABULARY.CONTEXT_SENSE", "DE.A1.VOCABULARY.COLLOCATION"],
    },
    {
      id: "DE.A1.VOCABULARY.ACTIVE_RETRIEVAL",
      targetLanguage: "de",
      level: "A1",
      domain: "vocabulary",
      outcome: "Recall taught lexical material without visible choices/answer hints",
      hardPrerequisites: [
        "DE.A1.VOCABULARY.NUMERIC_TIME",
        "DE.A1.VOCABULARY.NOUN_BUNDLE",
        "DE.A1.VOCABULARY.ACTION_SENSE",
      ],
    },
    {
      id: "DE.A1.VOCABULARY.TRANSFER_SELECTION",
      targetLanguage: "de",
      level: "A1",
      domain: "vocabulary",
      outcome: "Choose relevant familiar words in a new situation and avoid distracting senses",
      hardPrerequisites: [
        "DE.A1.VOCABULARY.CONTEXT_SENSE",
        "DE.A1.VOCABULARY.FRAME_USE",
        "DE.A1.VOCABULARY.ACTIVE_RETRIEVAL",
      ],
    },
  ],
  units: [
    {
      id: "DE.A1.U01",
      title: "Foundations and identity",
      description:
        "Introduce yourself, name people and things, ask for details, and give basic information.",
      lessonIds: ["DE.A1.U01.L01", "DE.A1.U01.L02", "DE.A1.U01.L03", "DE.A1.U01.L04"],
    },
    {
      id: "DE.A1.U02",
      title: "People, home and routine",
      description:
        "Describe everyday routines and belongings, correct a home detail, and revise a short description.",
      lessonIds: ["DE.A1.U02.L01", "DE.A1.U02.L02", "DE.A1.U02.L03", "DE.A1.U02.L04"],
    },
    {
      id: "DE.A1.U03",
      title: "Shopping and objects",
      description:
        "Identify shopping needs, describe available objects and correct a purchase without losing the intended meaning.",
      lessonIds: ["DE.A1.U03.L01", "DE.A1.U03.L02", "DE.A1.U03.L03", "DE.A1.U03.L04"],
    },
    {
      id: "DE.A1.U04",
      title: "Time and plans",
      description:
        "Read changed times, arrange activities, ask about services and offer workable alternatives.",
      lessonIds: ["DE.A1.U04.L01", "DE.A1.U04.L02", "DE.A1.U04.L03", "DE.A1.U04.L04"],
    },
    {
      id: "DE.A1.U05",
      title: "Town and services",
      description: "Find places, ask for help, send arrival notes and handle invitations politely.",
      lessonIds: ["DE.A1.U05.L01", "DE.A1.U05.L02", "DE.A1.U05.L03", "DE.A1.U05.L04"],
    },
    {
      id: "DE.A1.U06",
      title: "Recent experiences",
      lessonIds: ["DE.A1.U06.L01", "DE.A1.U06.L02", "DE.A1.U06.L03", "DE.A1.U06.L04"],
    },
    {
      id: "DE.A1.U07",
      title: "Travel",
      lessonIds: ["DE.A1.U07.L01", "DE.A1.U07.L02", "DE.A1.U07.L03", "DE.A1.U07.L04"],
    },
    {
      id: "DE.A1.U08",
      title: "Work and study",
      lessonIds: ["DE.A1.U08.L01", "DE.A1.U08.L02", "DE.A1.U08.L03", "DE.A1.U08.L04"],
    },
    {
      id: "DE.A1.U09",
      title: "Community and health",
      lessonIds: ["DE.A1.U09.L01", "DE.A1.U09.L02", "DE.A1.U09.L03", "DE.A1.U09.L04"],
    },
    {
      id: "DE.A1.U10",
      title: "Independent communication",
      lessonIds: ["DE.A1.U10.L01", "DE.A1.U10.L02", "DE.A1.U10.L03", "DE.A1.U10.L04"],
    },
  ],
  lessons: [
    {
      id: "DE.A1.U01.L01",
      resumeContractVersion: 1,
      unitId: "DE.A1.U01",
      title: "Meet and identify: introduce yourself",
      outcome: "One original identity statement; guided production",
      description: "Introduce yourself with one simple German sentence.",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.PRONOUNS.SUBJECT",
        "DE.A1.GRAMMAR.VERBS.SEIN_PRESENT",
        "DE.A1.GRAMMAR.ORDER.DECLARATIVE_V2",
        "DE.A1.VOCABULARY.PERSONAL_CORE",
        "DE.A1.WRITING.PERSONAL_FACT",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      steps: identityLessonSteps,
    },
    {
      id: "DE.A1.U01.L02",
      resumeContractVersion: 1,
      unitId: "DE.A1.U01",
      title: "Name people and things",
      outcome: "Match pictured/labeled entities then write a familiar noun phrase",
      description: "Read a few workplace labels, then write a short German phrase.",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.NOUNS.GENDER",
        "DE.A1.GRAMMAR.ARTICLES.DEFINITE_NOM",
        "DE.A1.GRAMMAR.ARTICLES.INDEFINITE_NOM",
        "DE.A1.GRAMMAR.CASES.NOMINATIVE_ROLE",
        "DE.A1.VOCABULARY.ENTITY_CATEGORIES",
        "DE.A1.WRITING.ORTHOGRAPHY",
        "DE.A1.READING.PERSON_ENTITIES",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      steps: entityLessonSteps,
    },
    {
      id: "DE.A1.U01.L03",
      resumeContractVersion: 1,
      unitId: "DE.A1.U01",
      title: "Ask for personal details",
      description: "Ask who someone is, then read a registration number and date.",
      outcome: "Ask a new person's detail and extract number/date",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.QUESTIONS.YES_NO",
        "DE.A1.GRAMMAR.QUESTIONS.WH",
        "DE.A1.GRAMMAR.QUANTITY.NUMBER_NOUN",
        "DE.A1.VOCABULARY.NUMERIC_TIME",
        "DE.A1.READING.NUMERIC_DETAILS",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      steps: detailsLessonSteps,
    },
    {
      id: "DE.A1.U01.L04",
      resumeContractVersion: 1,
      unitId: "DE.A1.U01",
      title: "Give basic information",
      description: "Read an office note, fill a fictional form, and describe a place.",
      outcome: "Supported registration form and simple description",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.VERBS.HABEN_PRESENT",
        "DE.A1.GRAMMAR.ADJECTIVES.PREDICATIVE",
        "DE.A1.VOCABULARY.NOUN_BUNDLE",
        "DE.A1.WRITING.FORM_COMPLETION",
        "DE.A1.READING.EXPLICIT_FACT",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      steps: informationLessonSteps,
    },
    {
      id: "DE.A1.U02.L01",
      resumeContractVersion: 1,
      unitId: "DE.A1.U02",
      title: "Everyday actions and routine",
      outcome: "Produce simple routine statements with different subjects",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.VERBS.REGULAR_SINGULAR",
        "DE.A1.GRAMMAR.VERBS.PLURAL_POLITE",
        "DE.A1.GRAMMAR.VERBS.SUBJECT_AGREEMENT",
        "DE.A1.VOCABULARY.ACTION_SENSE",
        "DE.A1.WRITING.SIMPLE_SENTENCE",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      steps: routineLessonSteps,
    },
    {
      id: "DE.A1.U02.L02",
      resumeContractVersion: 1,
      unitId: "DE.A1.U02",
      title: "People, belongings and plurals",
      outcome: "Explain whose objects they are; resolve simple reference",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.NOUNS.PLURAL",
        "DE.A1.GRAMMAR.POSSESSIVES.NOM",
        "DE.A1.READING.REFERENCE",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      steps: belongingsLessonSteps,
    },
    {
      id: "DE.A1.U02.L03",
      resumeContractVersion: 1,
      unitId: "DE.A1.U02",
      title: "Say what is not true",
      outcome: "Contrast a real/incorrect personal or home detail",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.NEGATION.NICHT_CLAUSE",
        "DE.A1.GRAMMAR.NEGATION.KEIN_NOM",
        "DE.A1.GRAMMAR.NEGATION.NICHT_KEIN",
        "DE.A1.WRITING.DESCRIPTION",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      steps: negationLessonSteps,
    },
    {
      id: "DE.A1.U02.L04",
      resumeContractVersion: 1,
      unitId: "DE.A1.U02",
      title: "Combine and revise statements",
      outcome: "Read a corrected fact and revise own short description",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.VERBS.STEM_CHANGE",
        "DE.A1.GRAMMAR.CONNECTORS.UND",
        "DE.A1.READING.NEGATED_INFORMATION",
        "DE.A1.WRITING.SELF_REVISION",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      steps: revisionLessonSteps,
    },
    {
      id: "DE.A1.U03.L01",
      unitId: "DE.A1.U03",
      title: "Shopping: identify what is needed",
      outcome: "Unaided object phrases for a concrete purchase",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.CASES.ACCUSATIVE_ROLE",
        "DE.A1.GRAMMAR.CASES.ACCUSATIVE_DEFINITE",
        "DE.A1.GRAMMAR.CASES.ACCUSATIVE_INDEFINITE",
        "DE.A1.GRAMMAR.VERBS.ACCUSATIVE_FRAMES",
        "DE.A1.VOCABULARY.CONTEXT_SENSE",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      resumeContractVersion: 1,
      steps: shoppingLessonSteps,
    },
    {
      id: "DE.A1.U03.L02",
      unitId: "DE.A1.U03",
      title: "Replace, negate and possess objects",
      outcome: "Interpret a short request, then answer with appropriate forms",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.CASES.ACCUSATIVE_KEIN",
        "DE.A1.GRAMMAR.PRONOUNS.ACCUSATIVE",
        "DE.A1.GRAMMAR.CASES.NOM_ACC_CONTRAST",
        "DE.A1.GRAMMAR.POSSESSIVES.ACC",
        "DE.A1.WRITING.OBJECT_PHRASE",
        "DE.A1.READING.SHORT_MESSAGE",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      resumeContractVersion: 1,
      steps: replacementLessonSteps,
    },
    {
      id: "DE.A1.U03.L03",
      unitId: "DE.A1.U03",
      title: "Availability and alternatives",
      outcome: "State what's available and communicate required details",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.CONNECTORS.ABER_ODER",
        "DE.A1.GRAMMAR.CONSTRUCTIONS.ES_GIBT",
        "DE.A1.VOCABULARY.COLLOCATION",
        "DE.A1.WRITING.TASK_FULFILMENT",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      resumeContractVersion: 1,
      steps: availabilityLessonSteps,
    },
    {
      id: "DE.A1.U03.L04",
      unitId: "DE.A1.U03",
      title: "Preference and focused correction",
      outcome: "Contrast intended meaning and choose word sense in context",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.ADVERBS.GERN_SEHR",
        "DE.A1.GRAMMAR.NEGATION.FOCUS",
        "DE.A1.VOCABULARY.FRAME_USE",
        "DE.A1.READING.CONTEXT_WORD",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      resumeContractVersion: 1,
      steps: preferenceLessonSteps,
    },
    {
      id: "DE.A1.U04.L01",
      unitId: "DE.A1.U04",
      title: "Time and plans",
      outcome: "Read changed times and write a main clause with a time opener",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.PREPOSITIONS.TIME",
        "DE.A1.GRAMMAR.ORDER.FRONTED_TIME",
        "DE.A1.GRAMMAR.TIME.PRESENT_PLANS",
        "DE.A1.VOCABULARY.ACTIVE_RETRIEVAL",
        "DE.A1.READING.TIME_SEQUENCE",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      resumeContractVersion: 1,
      steps: timeLessonSteps,
    },
    {
      id: "DE.A1.U04.L02",
      unitId: "DE.A1.U04",
      title: "Daily actions with prefixes",
      outcome: "Ask about an activity and state time/place with supported place chunks",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.VERBS.SEPARABLE_MEANING",
        "DE.A1.GRAMMAR.ORDER.SEPARABLE_MAIN",
        "DE.A1.GRAMMAR.ORDER.SEPARABLE_QUESTION",
        "DE.A1.VOCABULARY.TRANSFER_SELECTION",
        "DE.A1.WRITING.TIME_PLACE",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      resumeContractVersion: 1,
      steps: prefixLessonSteps,
    },
    {
      id: "DE.A1.U04.L03",
      unitId: "DE.A1.U04",
      title: "Ability, wants and requests",
      outcome: "Ask a simple service question using a taught modal/request frame",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.MODALS.KOENNEN",
        "DE.A1.GRAMMAR.MODALS.WANTS_REQUESTS",
        "DE.A1.GRAMMAR.ORDER.MODAL_BRACKET",
        "DE.A1.WRITING.REQUEST_INFORMATION",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      resumeContractVersion: 1,
      steps: requestLessonSteps,
    },
    {
      id: "DE.A1.U04.L04",
      unitId: "DE.A1.U04",
      title: "Necessity and permission",
      outcome: "Interpret a rule and give a relevant alternative plan",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.MODALS.MUESSEN",
        "DE.A1.GRAMMAR.MODALS.DUERFEN",
        "DE.A1.WRITING.GIVE_INFORMATION",
        "DE.A1.READING.PERMISSION_NOTICE",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      resumeContractVersion: 1,
      steps: ruleLessonSteps,
    },
    {
      id: "DE.A1.U05.L01",
      unitId: "DE.A1.U05",
      title: "Around town: place and transport",
      outcome: "Follow simple directions; produce reviewed location/dative phrases",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.PREPOSITIONS.PLACE_CHUNKS",
        "DE.A1.GRAMMAR.PREPOSITIONS.DATIVE_FRAMES",
        "DE.A1.GRAMMAR.CASES.DATIVE_ARTICLES",
        "DE.A1.READING.SIMPLE_INSTRUCTION",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      resumeContractVersion: 1,
      steps: townLessonSteps,
    },
    {
      id: "DE.A1.U05.L02",
      unitId: "DE.A1.U05",
      title: "Personal help and service interaction",
      outcome: "Ask/give help; greeting/closing supported until G42 review",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.PRONOUNS.DATIVE",
        "DE.A1.GRAMMAR.VERBS.DATIVE_FRAMES",
        "DE.A1.WRITING.REGISTER",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      resumeContractVersion: 1,
      steps: helpLessonSteps,
    },
    {
      id: "DE.A1.U05.L03",
      unitId: "DE.A1.U05",
      title: "Location, destination and forms",
      outcome: "Read field labels; send a short arrival/place note",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.PREPOSITIONS.LOCATION_DESTINATION",
        "DE.A1.READING.FORM_FIELDS",
        "DE.A1.WRITING.SHORT_MESSAGE",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      resumeContractVersion: 1,
      steps: arrivalLessonSteps,
    },
    {
      id: "DE.A1.U05.L04",
      unitId: "DE.A1.U05",
      title: "Polite instructions and invitations",
      outcome: "Give a practical instruction and accept/decline an invitation",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.IMPERATIVE.DU",
        "DE.A1.GRAMMAR.IMPERATIVE.IHR",
        "DE.A1.GRAMMAR.IMPERATIVE.SIE",
        "DE.A1.WRITING.INVITATION_RESPONSE",
      ],
      consolidatedSkillIds: [],
      availability: "prototype",
      resumeContractVersion: 1,
      steps: invitationLessonSteps,
    },
    {
      id: "DE.A1.U06.L01",
      unitId: "DE.A1.U06",
      title: "Recent experiences: the past frame",
      outcome: "Interpret short email detail; controlled past statement",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.PAST.PERFEKT_FRAME",
        "DE.A1.GRAMMAR.PAST.REGULAR_PARTICIPLE",
        "DE.A1.READING.SHORT_EMAIL",
      ],
      consolidatedSkillIds: [],
      availability: "not-authored",
      steps: [],
    },
    {
      id: "DE.A1.U06.L02",
      unitId: "DE.A1.U06",
      title: "Familiar past actions and auxiliaries",
      outcome: "Sequence two short events with reviewed participles",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.PAST.COMMON_PARTICIPLE",
        "DE.A1.GRAMMAR.PAST.AUXILIARY_CHOICE",
        "DE.A1.WRITING.SEQUENCE",
      ],
      consolidatedSkillIds: [],
      availability: "not-authored",
      steps: [],
    },
    {
      id: "DE.A1.U06.L03",
      unitId: "DE.A1.U06",
      title: "Earlier states and changed arrangements",
      outcome: "Original cancellation/change using independent simple clauses",
      introducedSkillIds: [
        "DE.A1.GRAMMAR.PAST.WAR_HATTE",
        "DE.A1.GRAMMAR.TRANSFER.CLAUSE_FRAMES",
        "DE.A1.READING.MAIN_PURPOSE",
        "DE.A1.WRITING.APOLOGY_CHANGE",
      ],
      consolidatedSkillIds: [],
      availability: "not-authored",
      steps: [],
    },
    {
      id: "DE.A1.U06.L04",
      unitId: "DE.A1.U06",
      title: "Choose the useful message",
      outcome: "Match a concrete need to short texts; original response",
      introducedSkillIds: ["DE.A1.READING.SELECT_RELEVANT_TEXT"],
      consolidatedSkillIds: [
        "DE.A1.GRAMMAR.TRANSFER.CLAUSE_FRAMES",
        "DE.A1.VOCABULARY.TRANSFER_SELECTION",
        "DE.A1.WRITING.TASK_FULFILMENT",
      ],
      availability: "not-authored",
      steps: [],
    },
    {
      id: "DE.A1.U07.L01",
      unitId: "DE.A1.U07",
      title: "Travel: dates and tickets",
      outcome: "New timetable/price retrieval and ticket request",
      introducedSkillIds: [],
      consolidatedSkillIds: [
        "DE.A1.READING.NUMERIC_DETAILS",
        "DE.A1.READING.TIME_SEQUENCE",
        "DE.A1.GRAMMAR.PREPOSITIONS.TIME",
        "DE.A1.GRAMMAR.ORDER.MODAL_BRACKET",
        "DE.A1.VOCABULARY.NUMERIC_TIME",
      ],
      availability: "not-authored",
      steps: [],
    },
    {
      id: "DE.A1.U07.L02",
      unitId: "DE.A1.U07",
      title: "Accommodation: availability",
      outcome: "Read room/service detail and ask a relevant question",
      introducedSkillIds: [],
      consolidatedSkillIds: [
        "DE.A1.READING.SHORT_EMAIL",
        "DE.A1.GRAMMAR.CONSTRUCTIONS.ES_GIBT",
        "DE.A1.GRAMMAR.CASES.DATIVE_ARTICLES",
        "DE.A1.WRITING.REQUEST_INFORMATION",
        "DE.A1.VOCABULARY.COLLOCATION",
      ],
      availability: "not-authored",
      steps: [],
    },
    {
      id: "DE.A1.U07.L03",
      unitId: "DE.A1.U07",
      title: "Arrival and route changes",
      outcome: "Correct a changed plan, with explicit location/destination",
      introducedSkillIds: [],
      consolidatedSkillIds: [
        "DE.A1.READING.NEGATED_INFORMATION",
        "DE.A1.READING.PERMISSION_NOTICE",
        "DE.A1.GRAMMAR.ORDER.SEPARABLE_QUESTION",
        "DE.A1.GRAMMAR.PREPOSITIONS.LOCATION_DESTINATION",
        "DE.A1.WRITING.TIME_PLACE",
        "DE.A1.WRITING.SHORT_MESSAGE",
      ],
      availability: "not-authored",
      steps: [],
    },
    {
      id: "DE.A1.U07.L04",
      unitId: "DE.A1.U07",
      title: "A travel message in your own words",
      outcome: "Guided → free original practical message in new context",
      introducedSkillIds: [],
      consolidatedSkillIds: [
        "DE.A1.WRITING.TASK_FULFILMENT",
        "DE.A1.WRITING.REGISTER",
        "DE.A1.WRITING.SHORT_MESSAGE",
        "DE.A1.WRITING.SEQUENCE",
        "DE.A1.GRAMMAR.TRANSFER.CLAUSE_FRAMES",
      ],
      availability: "not-authored",
      steps: [],
    },
    {
      id: "DE.A1.U08.L01",
      unitId: "DE.A1.U08",
      title: "Work/study: course information",
      outcome: "Select suitable short course information and fill a form",
      introducedSkillIds: [],
      consolidatedSkillIds: [
        "DE.A1.READING.FORM_FIELDS",
        "DE.A1.READING.SELECT_RELEVANT_TEXT",
        "DE.A1.WRITING.FORM_COMPLETION",
        "DE.A1.GRAMMAR.QUESTIONS.WH",
        "DE.A1.VOCABULARY.CONTEXT_SENSE",
      ],
      availability: "not-authored",
      steps: [],
    },
    {
      id: "DE.A1.U08.L02",
      unitId: "DE.A1.U08",
      title: "Schedule and obligations",
      outcome: "State a constraint and suggest an alternative time",
      introducedSkillIds: [],
      consolidatedSkillIds: [
        "DE.A1.READING.TIME_SEQUENCE",
        "DE.A1.GRAMMAR.ORDER.FRONTED_TIME",
        "DE.A1.GRAMMAR.MODALS.MUESSEN",
        "DE.A1.GRAMMAR.ORDER.MODAL_BRACKET",
        "DE.A1.WRITING.GIVE_INFORMATION",
      ],
      availability: "not-authored",
      steps: [],
    },
    {
      id: "DE.A1.U08.L03",
      unitId: "DE.A1.U08",
      title: "Ask and give practical information",
      outcome: "New service enquiry/reply; no canned email template",
      introducedSkillIds: [],
      consolidatedSkillIds: [
        "DE.A1.WRITING.REQUEST_INFORMATION",
        "DE.A1.WRITING.GIVE_INFORMATION",
        "DE.A1.WRITING.REGISTER",
        "DE.A1.GRAMMAR.MODALS.WANTS_REQUESTS",
        "DE.A1.VOCABULARY.FRAME_USE",
      ],
      availability: "not-authored",
      steps: [],
    },
    {
      id: "DE.A1.U08.L04",
      unitId: "DE.A1.U08",
      title: "Read, act, then revise",
      outcome: "Respond to a new note and revise a targeted error",
      introducedSkillIds: [],
      consolidatedSkillIds: [
        "DE.A1.READING.SHORT_MESSAGE",
        "DE.A1.READING.SHORT_EMAIL",
        "DE.A1.WRITING.TASK_FULFILMENT",
        "DE.A1.WRITING.SELF_REVISION",
        "DE.A1.GRAMMAR.NEGATION.FOCUS",
      ],
      availability: "not-authored",
      steps: [],
    },
    {
      id: "DE.A1.U09.L01",
      unitId: "DE.A1.U09",
      title: "Health/community: describe a need",
      outcome: "Describe a basic problem; no medical knowledge grading",
      introducedSkillIds: [],
      consolidatedSkillIds: [
        "DE.A1.WRITING.DESCRIPTION",
        "DE.A1.GRAMMAR.VERBS.HABEN_PRESENT",
        "DE.A1.GRAMMAR.ADJECTIVES.PREDICATIVE",
        "DE.A1.GRAMMAR.PAST.WAR_HATTE",
        "DE.A1.VOCABULARY.NOUN_BUNDLE",
      ],
      availability: "not-authored",
      steps: [],
    },
    {
      id: "DE.A1.U09.L02",
      unitId: "DE.A1.U09",
      title: "Notices and simple instructions",
      outcome: "Interpret everyday notices and produce a polite instruction",
      introducedSkillIds: [],
      consolidatedSkillIds: [
        "DE.A1.READING.PERMISSION_NOTICE",
        "DE.A1.READING.SIMPLE_INSTRUCTION",
        "DE.A1.GRAMMAR.MODALS.DUERFEN",
        "DE.A1.GRAMMAR.IMPERATIVE.DU",
        "DE.A1.GRAMMAR.IMPERATIVE.SIE",
      ],
      availability: "not-authored",
      steps: [],
    },
    {
      id: "DE.A1.U09.L03",
      unitId: "DE.A1.U09",
      title: "Invitation and change",
      outcome: "Invite or change a plan with all necessary details",
      introducedSkillIds: [],
      consolidatedSkillIds: [
        "DE.A1.WRITING.INVITATION_RESPONSE",
        "DE.A1.WRITING.APOLOGY_CHANGE",
        "DE.A1.WRITING.TIME_PLACE",
        "DE.A1.GRAMMAR.CONNECTORS.ABER_ODER",
        "DE.A1.VOCABULARY.TRANSFER_SELECTION",
      ],
      availability: "not-authored",
      steps: [],
    },
    {
      id: "DE.A1.U09.L04",
      unitId: "DE.A1.U09",
      title: "Independent short correspondence",
      outcome: "Read an unfamiliar simple message and communicate next step",
      introducedSkillIds: [],
      consolidatedSkillIds: [
        "DE.A1.WRITING.TASK_FULFILMENT",
        "DE.A1.WRITING.REGISTER",
        "DE.A1.WRITING.SHORT_MESSAGE",
        "DE.A1.WRITING.APOLOGY_CHANGE",
        "DE.A1.READING.MAIN_PURPOSE",
      ],
      availability: "not-authored",
      steps: [],
    },
    {
      id: "DE.A1.U10.L01",
      unitId: "DE.A1.U10",
      title: "Independent everyday reading",
      outcome: "Held-out practice families, not final-assessment bank",
      introducedSkillIds: [],
      consolidatedSkillIds: [
        "DE.A1.READING.NUMERIC_DETAILS",
        "DE.A1.READING.EXPLICIT_FACT",
        "DE.A1.READING.NEGATED_INFORMATION",
        "DE.A1.READING.CONTEXT_WORD",
        "DE.A1.READING.SELECT_RELEVANT_TEXT",
      ],
      availability: "not-authored",
      steps: [],
    },
    {
      id: "DE.A1.U10.L02",
      unitId: "DE.A1.U10",
      title: "Tell, ask and respond",
      outcome: "Select structures without topic names or answer templates",
      introducedSkillIds: [],
      consolidatedSkillIds: [
        "DE.A1.WRITING.SIMPLE_SENTENCE",
        "DE.A1.WRITING.OBJECT_PHRASE",
        "DE.A1.WRITING.REQUEST_INFORMATION",
        "DE.A1.WRITING.GIVE_INFORMATION",
        "DE.A1.GRAMMAR.TRANSFER.CLAUSE_FRAMES",
        "DE.A1.VOCABULARY.ACTIVE_RETRIEVAL",
      ],
      availability: "not-authored",
      steps: [],
    },
    {
      id: "DE.A1.U10.L03",
      unitId: "DE.A1.U10",
      title: "A form and a message",
      outcome: "Independent practice portfolio with separate outcomes",
      introducedSkillIds: [],
      consolidatedSkillIds: [
        "DE.A1.WRITING.FORM_COMPLETION",
        "DE.A1.WRITING.TASK_FULFILMENT",
        "DE.A1.WRITING.REGISTER",
        "DE.A1.WRITING.SHORT_MESSAGE",
        "DE.A1.WRITING.SEQUENCE",
        "DE.A1.VOCABULARY.TRANSFER_SELECTION",
      ],
      availability: "not-authored",
      steps: [],
    },
    {
      id: "DE.A1.U10.L04",
      unitId: "DE.A1.U10",
      title: "Reflect and prepare for checkpoint",
      outcome: "Explain next practice need in plain copy; no mastery from reflection",
      introducedSkillIds: [],
      consolidatedSkillIds: [
        "DE.A1.WRITING.SELF_REVISION",
        "DE.A1.GRAMMAR.TRANSFER.CLAUSE_FRAMES",
        "DE.A1.READING.MAIN_PURPOSE",
        "DE.A1.VOCABULARY.TRANSFER_SELECTION",
      ],
      availability: "not-authored",
      steps: [],
    },
  ],
};
