import type { LessonStep } from "@/lib/curriculum/types";
import { lessonAuthor, G, R, W, V } from "./german-a1-batch-a-lesson";
const fields = R + "FORM_FIELDS",
  relevant = R + "SELECT_RELEVANT_TEXT",
  form = W + "FORM_COMPLETION",
  wh = G + "QUESTIONS.WH",
  sense = V + "CONTEXT_SENSE";
const a = lessonAuthor("08", 1);
export const courseInformationSteps: readonly LessonStep[] = [
  a.explain(
    "scene",
    "Choose a course that fits",
    "Read the city and clock time as separate constraints.",
    "A: Deutschkurs — Bonn, Montag, 9 Uhr.\nB: Deutschkurs — Bonn, Montag, 18 Uhr.",
    "Deutschkurs = German course. Here Kurs means a class, not a financial rate. If you need Bonn in the evening at eighteen, only B fits. This is explicit relevance matching, not hidden inference.",
    [relevant, sense],
  ),
  a.choice(
    "select",
    "read",
    "Meet both stated needs",
    "You need Bonn on Monday at eighteen. Which offer fits?",
    ["A", "B"],
    "B",
    "B matches both city and time; A is the morning offer.",
    [relevant],
    "A: Deutschkurs — Bonn, Montag, 9 Uhr. B: Deutschkurs — Bonn, Montag, 18 Uhr.",
  ),
  a.explain(
    "fields",
    "Put the right fact in the right field",
    "Use fictional details only.",
    "Name = person's name; Ort = place; Uhrzeit = clock time; Kurs = selected course.\nAda · Bonn · 18 Uhr · B",
    "A city goes in Ort, not Name; a clock time goes in Uhrzeit. Completing these fields means placing the information correctly. Do not provide personal information.",
    [fields, form],
  ),
  a.text(
    "extract",
    "read",
    "Find the place field",
    "From the course note, copy only the value for Ort.",
    ["Bonn"],
    "Bonn is the place; 18 Uhr is the time and Ada the name.",
    [fields],
    "Name: Ada. Kurs: B. Ort: Bonn. Uhrzeit: 18 Uhr.",
  ),
  a.text(
    "recall",
    "recall",
    "Recall the time question word",
    "Complete ___ ist der Kurs? You ask at what time the course takes place. Type only the familiar wh-word.",
    ["Wann"],
    "Wann asks about time; Wo would ask about place.",
    [wh],
  ),
  a.text(
    "question",
    "produce",
    "Ask for the course location",
    "Ask where the course is. Use der Kurs (the course) in one full wh-question beginning Wo.",
    ["Wo ist der Kurs?"],
    "Wo asks for the missing place; ist follows the wh-word.",
    [wh, sense],
  ),
  a.text(
    "form",
    "produce",
    "Fill two actual fields",
    "Use the fictional registration details below. Type exactly Name: …; Ort: … with the correct values.",
    ["Name: Ada; Ort: Berlin"],
    "The name and place are correctly assigned; no inferred facts are added.",
    [fields, form],
    "Fictional learner: Ada. City: Berlin.",
  ),
  a.choice(
    "context",
    "classify",
    "Keep the contextual sense",
    "What does Kurs mean in this announcement?",
    ["A class to attend.", "The price of a currency."],
    "A class to attend.",
    "Deutsch and the named room/time make the class sense explicit.",
    [sense],
    "Deutschkurs im Büro, Montag, 19 Uhr. im Büro = in the office",
  ),
  a.text(
    "fresh-match",
    "apply",
    "Find an explicit evening option",
    "You need Berlin at nineteen. Copy only the label of the matching course.",
    ["C"],
    "Only C meets both stated requirements; A and B each miss one.",
    [relevant],
    "A: Berlin, 8 Uhr. B: Bonn, 19 Uhr. C: Berlin, 19 Uhr.",
  ),
  a.text(
    "check",
    "check",
    "Complete a fresh registration",
    "Ben needs a course in Bonn on Tuesday at eighteen. Select the offer and fill four fields in this exact order: Kurs: …; Name: …; Ort: …; Uhrzeit: … . Use only the supplied facts.",
    ["Kurs: A; Name: Ben; Ort: Bonn; Uhrzeit: 18 Uhr"],
    "A meets city, day and time; Ben is the fictional learner. Each fact belongs in its named field.",
    [relevant, fields, form, sense],
    "A: Bonn, Dienstag, 18 Uhr. B: Berlin, Dienstag, 18 Uhr. C: Bonn, Dienstag, 9 Uhr. Dienstag = Tuesday",
  ),
];
const times = R + "TIME_SEQUENCE",
  front = G + "ORDER.FRONTED_TIME",
  must = G + "MODALS.MUESSEN",
  bracket = G + "ORDER.MODAL_BRACKET",
  info = W + "GIVE_INFORMATION";
const b = lessonAuthor("08", 2);
export const obligationSteps: readonly LessonStep[] = [
  b.explain(
    "scene",
    "A course time has changed",
    "Read the change before offering a new arrangement.",
    "Deutschkurs: vorher 18 Uhr, jetzt 17 Uhr.\nAm Montag muss ich arbeiten. Um neunzehn kann ich kommen.",
    "Deutschkurs = German course; vorher/jetzt = before/now. The new course time is earlier. The two separate sentences state a work obligation and a possible alternative time. No complex work vocabulary is needed.",
    [times, info],
  ),
  b.text(
    "new-time",
    "read",
    "Retrieve the updated time",
    "Copy only the current course time, with digits and Uhr.",
    ["17 Uhr"],
    "jetzt 17 Uhr replaces the earlier plan of 18 Uhr.",
    [times],
    "Deutschkurs: vorher 18 Uhr, jetzt 17 Uhr.",
  ),
  b.choice(
    "change",
    "read",
    "Interpret the direction of change",
    "Is the new appointment earlier or later?",
    ["Earlier.", "Later."],
    "Later.",
    "Ten follows eight on the same day; this is a later appointment.",
    [times],
    "Termin: alt 8 Uhr, neu 10 Uhr. Termin = appointment; alt/neu = old/new",
  ),
  b.explain(
    "order",
    "One time phrase, one finite position",
    "Reuse the bracket instead of adding new grammar.",
    "Ich muss heute arbeiten.\nHeute muss ich arbeiten.\nUm zehn kann ich kommen.",
    "A fronted time phrase takes the first clause position; muss/kann stays second, then ich. The action stays last: arbeiten/kommen. müssen communicates a requirement, not permission.",
    [front, must, bracket],
  ),
  b.text(
    "recall",
    "recall",
    "Recall the obligation form",
    "Complete Ich ___ arbeiten. The work is required. Use the reviewed ich form of müssen; type only that word.",
    ["muss"],
    "muss states a requirement; darf would describe permission.",
    [must],
  ),
  b.text(
    "work",
    "produce",
    "Tell your colleague Monday's constraint",
    "You must work on Monday. Begin Am Montag and use ich and arbeiten. Write one full statement.",
    ["Am Montag muss ich arbeiten."],
    "muss follows the fronted day phrase; arbeiten closes the bracket.",
    [front, must, bracket, info],
  ),
  b.text(
    "repair",
    "apply",
    "Keep the time first",
    "Repair only the order, keeping every word and Um zwölf first.",
    ["Um zwölf kann ich kommen."],
    "The finite modal is second; the subject follows it.",
    [front, bracket],
    "Draft: Um zwölf ich kann kommen.",
  ),
  b.text(
    "alternative",
    "produce",
    "Give a useful alternative",
    "You must study at nine but can come at eleven. Write two sentences, starting Um neun and Um elf respectively. Use ich, lernen/kommen and the appropriate reviewed modals.",
    ["Um neun muss ich lernen. Um elf kann ich kommen."],
    "The two independent sentences distinguish a requirement from a workable possibility.",
    [front, must, bracket, info],
  ),
  b.text(
    "reply",
    "apply",
    "Respond to a changed course time",
    "You must work at sixteen. Offer coming at eighteen instead. Begin each sentence Ich, state the constraint first, using um sechzehn/um achtzehn and arbeiten/kommen. sechzehn = sixteen; achtzehn = eighteen.",
    ["Ich muss um sechzehn arbeiten. Ich kann um achtzehn kommen."],
    "The reply supplies both the conflict and an explicit next time.",
    [must, bracket, info, times],
    "Kurs: vorher 18 Uhr, jetzt 16 Uhr. Kurs = course; vorher/jetzt = before/now",
  ),
  b.text(
    "check",
    "check",
    "An unseen schedule reply",
    "The new meeting is Tuesday at eight, when you must work. You can come Tuesday at twelve instead. Write two sentences beginning Am Dienstag and Um zwölf; use ich, arbeiten/kommen and suitable modals in that order. Dienstag = Tuesday.",
    ["Am Dienstag muss ich um acht arbeiten. Um zwölf kann ich kommen."],
    "The message preserves the day/time constraint and states a concrete alternative without extra clauses.",
    [times, front, must, bracket, info],
  ),
];
const enquiry = W + "REQUEST_INFORMATION",
  register = W + "REGISTER",
  request = G + "MODALS.WANTS_REQUESTS",
  frame = V + "FRAME_USE";
const c = lessonAuthor("08", 3);
export const practicalInformationSteps: readonly LessonStep[] = [
  c.explain(
    "scene",
    "Ask only for the missing information",
    "Read a course notice before contacting someone.",
    "Deutschkurs im Büro — Freitag.\nUhrzeit: ?",
    "Deutschkurs = German course; im Büro = in the office. The day and place are given, but the clock time is missing. A useful question asks for that missing detail, not a known fact.",
    [enquiry, frame],
  ),
  c.choice(
    "needed",
    "read",
    "Choose a relevant enquiry",
    "Which question requests the missing fact?",
    ["Wann ist der Kurs?", "Wo ist der Kurs?"],
    "Wann ist der Kurs?",
    "Wann asks for the missing time; the office location is already given.",
    [enquiry],
    "Kurs: Büro, Freitag. Uhrzeit: ?",
  ),
  c.explain(
    "intent",
    "Choose the appropriate intention",
    "Reuse three reviewed frames in their familiar meanings.",
    "Ich will lernen.\nIch möchte eine Fahrkarte kaufen.\nWas soll ich lernen?",
    "will states your intention; möchte makes the taught polite request; soll asks about/reports an instruction. These are different intentions, not interchangeable synonyms. For staff use Sie; for one familiar friend use du.",
    [request, register, frame],
  ),
  c.text(
    "recall",
    "recall",
    "Recall the help frame",
    "Complete Können Sie mir ___? Type only the familiar verb that makes this a request for help.",
    ["helfen"],
    "helfen belongs to the reviewed mir helfen frame; the modal is followed by the final infinitive.",
    [frame, enquiry],
  ),
  c.text(
    "ask",
    "produce",
    "A fresh office enquiry",
    "Ask a member of staff if they can help you on Thursday. Begin Können Sie, then mir, am Donnerstag and final helfen. Write a full question. Donnerstag = Thursday.",
    ["Können Sie mir am Donnerstag helfen?"],
    "The question has the right listener, recipient and requested day.",
    [enquiry, register, frame],
  ),
  c.text(
    "reply",
    "produce",
    "Give the information a colleague needs",
    "A colleague asks where and when the course is. Use the note to write two statements: Der Kurs ist with the place first, then Der Kurs ist with the time.",
    [
      "Der Kurs ist im Büro. Der Kurs ist um siebzehn.",
      "Der Kurs ist im Büro. Der Kurs ist um siebzehn Uhr.",
    ],
    "Both requested facts are explicit; no decorative email wording is necessary.",
    [info, frame],
    "Kurs: Büro, 17 Uhr. im Büro = in the office; siebzehn = seventeen",
  ),
  c.choice(
    "instruction",
    "classify",
    "Request or assigned action?",
    "Which sentence asks what you are supposed to study?",
    ["Was soll ich lernen?", "Ich möchte lernen.", "Ich will lernen."],
    "Was soll ich lernen?",
    "soll asks for an assigned action; the others express desire/intention.",
    [request],
  ),
  c.text(
    "friend",
    "apply",
    "Change only the listener",
    "You are now asking one friend, not staff. Rewrite the full help question with du, preserving the recipient mir.",
    ["Kannst du mir helfen?"],
    "Kannst du is the familiar listener form; mir keeps the help directed to you.",
    [register, enquiry, frame],
    "Draft to Ben: Können Sie mir helfen?",
  ),
  c.text(
    "missing",
    "apply",
    "Ask for the genuinely missing day",
    "You know the course is at nine but not whether you may come Monday. Ask that possibility in one complete question, beginning Kann ich, using am Montag and final kommen.",
    ["Kann ich am Montag kommen?"],
    "The enquiry requests the unknown day/possibility rather than repeating the time.",
    [enquiry, request],
    "Kurs: 9 Uhr. Day not yet confirmed.",
  ),
  c.text(
    "check",
    "check",
    "Respond in a new service context",
    "You address an unfamiliar member of staff. Ask whether they can help you tomorrow at ten. Start Guten Tag!, then one full Sie question with mir, morgen, um zehn and helfen in that order; close Vielen Dank!.",
    ["Guten Tag! Können Sie mir morgen um zehn helfen? Vielen Dank!"],
    "The bounded enquiry supplies both requested time details and a natural polite register; no full model was supplied for this scenario.",
    [enquiry, register, frame],
  ),
];
const note = R + "SHORT_MESSAGE",
  email = R + "SHORT_EMAIL",
  fulfil = W + "TASK_FULFILMENT",
  revision = W + "SELF_REVISION",
  negation = G + "NEGATION.FOCUS";
const d = lessonAuthor("08", 4);
export const revisionSteps: readonly LessonStep[] = [
  d.explain(
    "scene",
    "Read, act, then check one detail",
    "Find the action and both arrangement facts.",
    "Hallo Ada! Bitte am Dienstag um neun ins Büro kommen. Nicht am Montag. Ben",
    "Dienstag = Tuesday; ins Büro = into/to the office. The note asks for an office visit on Tuesday at nine and explicitly excludes Monday. First understand the facts; then write a response and revise only the named problem.",
    [note, email, fulfil],
  ),
  d.choice(
    "purpose",
    "read",
    "Identify the requested action",
    "What does Ben want Ada to do?",
    ["Come to the office on Tuesday.", "Buy a ticket on Monday.", "Report an earlier illness."],
    "Come to the office on Tuesday.",
    "Bitte … kommen is the requested action; the negated Monday is not the new plan.",
    [note],
    "Hallo Ada! Bitte am Dienstag um neun ins Büro kommen. Nicht am Montag. Ben",
  ),
  d.text(
    "constraint",
    "read",
    "Retrieve the excluded day",
    "Copy only the explicitly excluded day phrase, starting am.",
    ["am Montag"],
    "nicht am Montag excludes Monday; it does not cancel Tuesday.",
    [email],
    "Bitte am Dienstag um neun ins Büro kommen. Nicht am Montag.",
  ),
  d.explain(
    "focus",
    "Correct only the intended contrast",
    "Keep all unrelated message details.",
    "Intent: the meeting is Tuesday, not Monday.\nDas Treffen ist nicht am Montag.",
    "Treffen = meeting. nicht stands immediately before the contrasted day phrase here. Do not move it to deny the whole event. This lesson reviews this bounded contrast, not unrestricted proofreading.",
    [negation, revision],
  ),
  d.text(
    "recall",
    "recall",
    "Recall the contrast word",
    "Complete Das Treffen ist ___ am Montag. The meeting is on a different day. Type only the familiar negation word.",
    ["nicht"],
    "nicht excludes the named day; kein would negate a noun phrase differently.",
    [negation],
  ),
  d.text(
    "response",
    "produce",
    "Confirm all arrangement details",
    "Accept the request in one full sentence beginning Ja, ich komme. Include am Dienstag, um neun and ins Büro in that order.",
    ["Ja, ich komme am Dienstag um neun ins Büro."],
    "The reply confirms the actual day, time and destination, not only one detail.",
    [fulfil, note],
  ),
  d.text(
    "revise",
    "apply",
    "Repair just the time fact",
    "The meeting is at eleven, not ten. Correct only the clock-time word; retain every other word and write the whole sentence.",
    ["Ich komme am Freitag um elf ins Büro."],
    "Only zehn changes to elf; the day and destination were already correct.",
    [revision],
    "Draft: Ich komme am Freitag um zehn ins Büro. Update: Friday, office, 11 Uhr. Freitag = Friday",
  ),
  d.text(
    "negative",
    "produce",
    "Preserve the intended exclusion",
    "You can come to the office, but not on Thursday. Write just the excluded-day statement beginning Das Treffen ist and using am Donnerstag; keep nicht directly before that day phrase. Donnerstag = Thursday.",
    ["Das Treffen ist nicht am Donnerstag."],
    "The focused statement excludes Thursday, not the office or the existence of a meeting.",
    [negation, revision],
  ),
  d.text(
    "new-note",
    "apply",
    "Reply to a fresh email",
    "Ben asks you to confirm a Friday visit at twelve to the bank. Write one sentence starting Ja, ich komme, then am Freitag, um zwölf and zur Bank. Freitag = Friday.",
    ["Ja, ich komme am Freitag um zwölf zur Bank."],
    "The reply fulfils all three explicit details, using a familiar destination frame.",
    [email, fulfil],
    "Hallo Ada! Bitte am Freitag um zwölf zur Bank kommen. Bitte die Zeit bestätigen. Ben\nbestätigen = confirm (supplied reading word)",
  ),
  d.text(
    "check",
    "check",
    "Revise a new practical reply",
    "The note requests Thursday, bank, fourteen; Monday is excluded. Correct only the wrong day in the first draft sentence. Keep the second sentence unchanged. Write both complete sentences in the draft order. Donnerstag = Thursday; vierzehn = fourteen.",
    ["Ja, ich komme am Donnerstag um vierzehn zur Bank. Das Treffen ist nicht am Montag."],
    "The targeted revision preserves time/destination and the explicit excluded-day contrast. No other editing is credited.",
    [note, email, fulfil, revision, negation],
    "Note: Bitte am Donnerstag um vierzehn zur Bank kommen. Nicht am Montag.\nDraft: Ja, ich komme am Freitag um vierzehn zur Bank. Das Treffen ist nicht am Montag.",
  ),
];
