import { batchBAuthor } from "./german-a1-batch-b-assessment";
// Original independent prototype families. No lesson-final stimulus is reused.
const { item: i, form: f } = batchBAuthor("CP3", [
  {
    id: "personal",
    label: "Personal information and a simple form",
    scope: "A supplied fictional introduction and independently graded fields.",
  },
  {
    id: "familiar",
    label: "Familiar people, objects and routines",
    scope: "A short description and a routine; neither is inferred from form accuracy.",
  },
  {
    id: "reading",
    label: "Everyday reading and relevant information",
    scope: "Explicit detail and all-constraint relevance selection.",
  },
  {
    id: "practical",
    label: "Time, place, requests and instructions",
    scope: "Supply time/place and a practical instruction or service request.",
  },
  {
    id: "message",
    label: "A practical message with necessary points",
    scope: "A bounded message with day, time, place and response intent.",
  },
  {
    id: "recent",
    label: "A recent event or changed arrangement",
    scope: "Explicit earlier event and a concrete changed plan.",
  },
  {
    id: "transfer",
    label: "Transfer and specific revision",
    scope: "Respond in the relevant frame and revise one named problem.",
  },
]);
export const cp3 = f("A", [
  i(
    "A",
    1,
    "personal",
    "bounded-text",
    "Complete exactly Name: …; Ort: …; Uhrzeit: … .",
    ["Name: Ada; Ort: Bonn; Uhrzeit: 17 Uhr"],
    "Fictional community registration: Ada, Bonn, 17 Uhr.",
  ),
  i(
    "A",
    2,
    "personal",
    "construction",
    "Introduce Ben: his name is Ben and he lives in Berlin. Write two sentences beginning Er, using heißen then wohnen.",
    ["Er heißt Ben. Er wohnt in Berlin."],
  ),
  i(
    "A",
    3,
    "familiar",
    "construction",
    "Describe Ada: she is friendly; her table is small. Write Ada, then Ihr Tisch, in two full sentences. freundlich = friendly; klein = small.",
    ["Ada ist freundlich. Ihr Tisch ist klein."],
  ),
  i(
    "A",
    4,
    "familiar",
    "construction",
    "Ben works Monday and studies Tuesday. Write two sentences beginning Ben with am Montag / am Dienstag.",
    ["Ben arbeitet am Montag. Ben lernt am Dienstag."],
  ),
  i(
    "A",
    5,
    "reading",
    "reading-extraction",
    "Copy only the explicitly excluded clock-time phrase, beginning um.",
    ["um acht"],
    "Bitte um elf kommen, nicht um acht.",
  ),
  i(
    "A",
    6,
    "reading",
    "reading-extraction",
    "You need a Berlin bus on Thursday at fifteen. Copy only the label of the offer fitting all three facts.",
    ["A"],
    "A: Bus, Berlin, Donnerstag, 15 Uhr. B: Zug, Berlin, Donnerstag, 15 Uhr. C: Bus, Bonn, Donnerstag, 15 Uhr. Zug = train; Donnerstag = Thursday",
  ),
  i(
    "A",
    7,
    "practical",
    "construction",
    "Politely ask an unfamiliar visitor to come today at fourteen. Begin Kommen Sie, use bitte heute um vierzehn. vierzehn = fourteen.",
    ["Kommen Sie bitte heute um vierzehn!"],
  ),
  i(
    "A",
    8,
    "practical",
    "construction",
    "The staff asks where and when you will arrive: tomorrow at twelve to the bank. Give one full Ich komme statement.",
    ["Ich komme morgen um zwölf zur Bank."],
  ),
  i(
    "A",
    9,
    "message",
    "bounded-text",
    "New friend message asks whether you can meet. Tell Ben: yes, you can come Saturday at sixteen to the office. Write Hallo Ben!, Ja, ich kann with all three details, and Bis bald!. Samstag = Saturday; sechzehn = sixteen.",
    ["Hallo Ben! Ja, ich kann am Samstag um sechzehn ins Büro kommen. Bis bald!"],
  ),
  i(
    "A",
    10,
    "message",
    "construction",
    "The same friend needs help; ask whether they can come today. Write a complete Kannst du question and then Ich brauche Hilfe.",
    ["Kannst du heute kommen? Ich brauche Hilfe."],
  ),
  i("A", 11, "recent", "construction", "Report yesterday: you had no time. Begin Gestern.", [
    "Gestern hatte ich keine Zeit.",
  ]),
  i(
    "A",
    12,
    "recent",
    "bounded-text",
    "The office visit is now Sunday at thirteen, not Friday. Tell Ada the cancellation and the new plan. Write Ich kann with am Freitag nicht kommen, then Ich komme with am Sonntag um dreizehn ins Büro. Freitag = Friday; Sonntag = Sunday; dreizehn = thirteen.",
    ["Ich kann am Freitag nicht kommen. Ich komme am Sonntag um dreizehn ins Büro."],
  ),
  i(
    "A",
    13,
    "transfer",
    "construction",
    "A friend asks about a completed earlier trip to the bank. Give that fact and then say you can help tomorrow. Write two Ich sentences.",
    ["Ich bin zur Bank gegangen. Ich kann morgen helfen."],
  ),
  i(
    "A",
    14,
    "transfer",
    "bounded-text",
    "Correct ONLY the time to nineteen, preserving the destination and closing. neunzehn = nineteen.",
    ["Ich komme am Dienstag um neunzehn zum Bahnhof. Vielen Dank!"],
    "Draft: Ich komme am Dienstag um neun zum Bahnhof. Vielen Dank!",
  ),
]);
export const cp3B = f("B", [
  i(
    "B",
    1,
    "personal",
    "bounded-text",
    "Repair the values; return exactly Ort: …; Name: …; Uhrzeit: … .",
    ["Ort: Berlin; Name: Ben; Uhrzeit: 12 Uhr"],
    "Fictional course application: Ben, Berlin, 12 Uhr. Draft: Ort: Ben; Name: 12 Uhr; Uhrzeit: Berlin.",
  ),
  i(
    "B",
    2,
    "personal",
    "bounded-text",
    "The note is about Ada, not Ben. Correct the full two-sentence introduction, preserving the supplied city.",
    ["Sie heißt Ada. Sie wohnt in Bonn."],
    "Draft: Er heißt Ben. Er wohnt in Bonn. New person: Ada.",
  ),
  i(
    "B",
    3,
    "familiar",
    "construction",
    "Describe Ben: he is tired; his chair is new. Write Ben, then Sein Stuhl in two full sentences. müde = tired; neu = new; Stuhl = chair.",
    ["Ben ist müde. Sein Stuhl ist neu."],
  ),
  i(
    "B",
    4,
    "familiar",
    "bounded-text",
    "Ada studies Friday; she does not work Friday. Correct ONLY the action in the first sentence, preserving both sentences. Freitag = Friday.",
    ["Ada lernt am Freitag. Ada arbeitet nicht am Freitag."],
    "Draft: Ada arbeitet am Freitag. Ada arbeitet nicht am Freitag.",
  ),
  i(
    "B",
    5,
    "reading",
    "reading-extraction",
    "Copy only the new place, not the old one.",
    ["Büro"],
    "Treffen: jetzt Büro, nicht Bank. Treffen = meeting; jetzt = now",
  ),
  i(
    "B",
    6,
    "reading",
    "reading-extraction",
    "Need: a Bonn course Saturday at eighteen. Copy only the matching label.",
    ["B"],
    "A: Bonn, Samstag, 10 Uhr. B: Bonn, Samstag, 18 Uhr. C: Berlin, Samstag, 18 Uhr. Samstag = Saturday",
  ),
  i(
    "B",
    7,
    "practical",
    "construction",
    "You need permission to wait here. Ask one complete question beginning Darf ich; use hier/warten.",
    ["Darf ich hier warten?"],
  ),
  i(
    "B",
    8,
    "practical",
    "bounded-text",
    "One friend needs a clear instruction to go to the bank at ten tomorrow. Write a du instruction beginning Geh; include bitte morgen um zehn zur Bank.",
    ["Geh bitte morgen um zehn zur Bank!"],
  ),
  i(
    "B",
    9,
    "message",
    "bounded-text",
    "Respond to unfamiliar staff: you cannot come Wednesday; you can come Thursday at twenty to the station. Write Guten Tag!, two Ich kann sentences with these details and Vielen Dank!. Mittwoch = Wednesday; Donnerstag = Thursday; zwanzig = twenty.",
    [
      "Guten Tag! Ich kann am Mittwoch nicht kommen. Ich kann am Donnerstag um zwanzig zum Bahnhof kommen. Vielen Dank!",
    ],
  ),
  i(
    "B",
    10,
    "message",
    "construction",
    "Ask staff when you can come, then say you need a ticket. Write a full Wann question with ich/kommen, then one Ich brauche statement.",
    ["Wann kann ich kommen? Ich brauche eine Fahrkarte."],
  ),
  i(
    "B",
    11,
    "recent",
    "construction",
    "Report your earlier actions: you came by bus, then studied. Write two Ich sentences.",
    ["Ich bin mit dem Bus gekommen. Ich habe gelernt."],
  ),
  i(
    "B",
    12,
    "recent",
    "bounded-text",
    "The meeting moved from bank to station; it remains Monday at fifteen. Change ONLY the destination in this confirmation. fünfzehn = fifteen.",
    ["Ja, ich komme am Montag um fünfzehn zum Bahnhof."],
    "Draft: Ja, ich komme am Montag um fünfzehn zur Bank.",
  ),
  i(
    "B",
    13,
    "transfer",
    "construction",
    "Ben asks whether you can help today; you must work today, but can help tomorrow. Give both facts in two Ich sentences.",
    ["Ich muss heute arbeiten. Ich kann morgen helfen."],
  ),
  i(
    "B",
    14,
    "transfer",
    "bounded-text",
    "The table is not small. Correct ONLY the adjective to groß, preserving the need and both whole sentences. groß = big.",
    ["Der Tisch ist groß. Ich brauche einen Stuhl."],
    "Draft: Der Tisch ist klein. Ich brauche einen Stuhl.",
  ),
]);
export const cp3Forms = [cp3, cp3B] as const;
