import type { ChallengeItem } from "@/lib/curriculum/challenge";
// Original held-out challenge contexts. Server-only keys; no new grading/persistence contract.
const t = (
  id: string,
  outcome: string,
  prompt: string,
  answers: string[],
  stimulus?: string,
): ChallengeItem => ({
  id,
  outcome,
  prompt,
  acceptedAnswers: answers,
  ...(stimulus ? { stimulus } : {}),
});
const c = (
  id: string,
  outcome: string,
  prompt: string,
  options: string[],
  answer: string,
  stimulus?: string,
): ChallengeItem => ({ ...t(id, outcome, prompt, [answer], stimulus), options });
export const batchAChallengeForms: Record<string, Record<"A" | "B", readonly ChallengeItem[]>> = {
  "DE.A1.U04": {
    A: [
      t(
        "time",
        "Time-first plan",
        "State that Ben comes at seven. Start Um sieben and write one complete German sentence.",
        ["Um sieben kommt Ben."],
      ),
      t(
        "changed",
        "Read a changed plan",
        "Copy only the current work start as a time phrase beginning um.",
        ["um acht"],
        "Arbeit: alt 7 Uhr, neu 8 Uhr. Arbeit = work; alt = old; neu = new",
      ),
      t(
        "prefix",
        "Ask about the activity",
        "Ask when a friend gets up. Use wann, du and aufstehen; write the complete wh-question.",
        ["Wann stehst du auf?"],
      ),
      t(
        "can",
        "Possibility",
        "You can shop today. Begin Ich and write one complete sentence using können, heute and einkaufen.",
        ["Ich kann heute einkaufen."],
      ),
      c(
        "intent",
        "Intent versus request",
        "You announce your own intention to work, rather than a service request or an instruction. Select the statement.",
        ["Ich will arbeiten.", "Ich möchte eine Fahrkarte kaufen.", "Ich soll arbeiten."],
        "Ich will arbeiten.",
      ),
      t(
        "question",
        "Modal service question",
        "Ask a member of staff if they can come at twelve. Start Können and address them as Sie. Write the whole question.",
        ["Können Sie um zwölf kommen?"],
      ),
      c(
        "rule",
        "Allowed versus required",
        "What is allowed by this notice? Select the permitted action.",
        ["Eat here.", "Shop at eight.", "Work at nine."],
        "Eat here.",
        "Du darfst hier essen. Du musst um neun arbeiten. Du darfst um acht nicht einkaufen.",
      ),
      t(
        "alternative",
        "Constraint and alternative",
        "You must study on Monday but can come on Tuesday. Write two complete sentences beginning Ich; give the obligation first. Dienstag = Tuesday.",
        ["Ich muss am Montag lernen. Ich kann am Dienstag kommen."],
      ),
    ],
    B: [
      t(
        "time",
        "Repair time-first order",
        "Keep the time first. Repair this work plan and write the whole sentence.",
        ["Um acht arbeitet Ben."],
        "Um acht Ben arbeitet.",
      ),
      c(
        "changed",
        "Interpret a changed plan",
        "Which statement correctly reads the update?",
        ["The new time is later.", "The new time is earlier.", "The time is unchanged."],
        "The new time is later.",
        "Treffen: vorher 8 Uhr, jetzt 11 Uhr. Treffen = meeting; vorher = before; jetzt = now",
      ),
      t(
        "prefix",
        "Preserve a question prefix",
        "Restore only the missing shopping prefix and write the complete place question.",
        ["Wo kauft Ada ein?"],
        "Wo kauft Ada ___? Intended action: einkaufen.",
      ),
      t(
        "can",
        "Read a possibility",
        "Ben has time to study today. Write that possibility about Ben in one full sentence, beginning Ben kann.",
        ["Ben kann heute lernen."],
        "Ben: Heute habe ich Zeit. Zeit = time",
      ),
      c(
        "intent",
        "A polite request",
        "At the ticket desk, which statement is the polite request?",
        [
          "Ich kann eine Fahrkarte kaufen.",
          "Ich soll eine Fahrkarte kaufen.",
          "Ich möchte eine Fahrkarte kaufen.",
        ],
        "Ich möchte eine Fahrkarte kaufen.",
      ),
      t(
        "question",
        "Repair a modal question",
        "Put the action in its final position. Preserve all words and write the corrected whole question.",
        ["Was soll ich lernen?"],
        "Was lernen soll ich? soll reports an instruction",
      ),
      c(
        "rule",
        "Read a prohibition",
        "What does the rule say about coming at eight?",
        ["Required.", "Permitted.", "Forbidden."],
        "Forbidden.",
        "Du darfst um acht nicht kommen. Du musst um neun kommen.",
      ),
      t(
        "alternative",
        "Repair a usable alternative",
        "The first action is required, not just allowed. Correct only its modal; keep the offered alternative. Write both sentences.",
        ["Ich muss heute arbeiten. Ich kann um zehn kommen."],
        "Draft: Ich darf heute arbeiten. Ich kann um zehn kommen.",
      ),
    ],
  },
  "DE.A1.U05": {
    A: [
      t(
        "route",
        "Interpret a route",
        "Copy only the travel destination from the instruction.",
        ["zum Bahnhof"],
        "Bitte von der Bank zum Bahnhof gehen.",
      ),
      t(
        "dative",
        "Use a transport frame",
        "Say Ada travels by bus. Start Ada and write a complete sentence using fahren and the definite transport chunk. fahren: Ada fährt",
        ["Ada fährt mit dem Bus."],
      ),
      t(
        "owner",
        "Name an owner",
        "The particular book is yours. State that it belongs to you. Start Das Buch and use gehören.",
        ["Das Buch gehört mir."],
      ),
      t(
        "help",
        "Polite help request",
        "Ask a member of staff politely whether they can help you tomorrow. Begin Können Sie and write a full question.",
        ["Können Sie mir morgen helfen?"],
      ),
      c(
        "location",
        "Location versus destination",
        "Which statement says that Ben is already at the station?",
        ["Ben geht an den Bahnhof.", "Ben ist am Bahnhof.", "Ben fährt nach Berlin."],
        "Ben ist am Bahnhof.",
      ),
      t(
        "field",
        "Read a form field",
        "Copy only the appointment clock time for Uhrzeit, with digits and Uhr.",
        ["7 Uhr"],
        "Name: Ada. Ort: Büro. Datum: 20. Mai. Termin: 7 Uhr. Uhrzeit = clock time; Termin = appointment",
      ),
      t(
        "register",
        "Polite instruction",
        "Tell an unfamiliar visitor to come to the station. Begin Kommen Sie, then bitte, then the destination. Write the complete instruction.",
        ["Kommen Sie bitte zum Bahnhof!"],
      ),
      t(
        "reply",
        "Accept with both details",
        "Accept the invitation. Start Ja, ich komme and preserve the time and destination in one full sentence.",
        ["Ja, ich komme um neun ins Zentrum."],
        "Ben: Komm bitte um neun ins Zentrum! ins Zentrum = into/to the centre",
      ),
    ],
    B: [
      c(
        "route",
        "Read a starting point",
        "Which phrase gives the starting point, rather than destination or transport?",
        ["zur Bank", "mit dem Bus", "aus dem Büro"],
        "aus dem Büro",
        "Ada kommt aus dem Büro. Ada fährt mit dem Bus zur Bank.",
      ),
      t(
        "dative",
        "Repair accompaniment",
        "Correct both the article and noun form; preserve the complete statement.",
        ["Ben kommt mit den Freunden."],
        "Draft: Ben kommt mit die Freunde.",
      ),
      t(
        "owner",
        "Retrieve a personal frame",
        "You thank someone you address as Sie. Complete Ich danke ___. Type only the receiving pronoun.",
        ["Ihnen"],
      ),
      t(
        "help",
        "Help a group",
        "You ask Ada as du to help you and Ben. Repair the pronoun so the request includes both of you. Write the complete question.",
        ["Kannst du uns helfen?"],
        "Draft: Kannst du mir helfen?",
      ),
      t(
        "location",
        "State a destination",
        "You are travelling to Berlin, not visiting Ada. Write one complete sentence starting Ich fahre with the reviewed city destination.",
        ["Ich fahre nach Berlin."],
      ),
      t(
        "field",
        "Select a place fact",
        "Copy only the place noun for Ort.",
        ["Bank"],
        "Anmeldung: Ben, Bank, 10 Uhr. Anmeldung = registration; Ort = place",
      ),
      t(
        "register",
        "Repair the addressee",
        "You address two friends, not one. Change the instruction to ihr and keep every other word. Write the whole sentence.",
        ["Kommt bitte um acht zur Bank!"],
        "Komm bitte um acht zur Bank!",
      ),
      t(
        "reply",
        "Decline with a workable alternative",
        "You cannot come on Monday. Offer Tuesday at eleven in the centre instead. Write two complete sentences: Am Montag kann ich nicht kommen; then start Am Dienstag kann ich, include um elf before ins Zentrum, and end kommen. Dienstag = Tuesday; ins Zentrum = into/to the centre.",
        ["Am Montag kann ich nicht kommen. Am Dienstag kann ich um elf ins Zentrum kommen."],
      ),
    ],
  },
};
