import type { LessonStep } from "@/lib/curriculum/types";

// Original Karta fictional form/office context; no personal data or external exam items.
const G03 = "DE.A1.GRAMMAR.VERBS.HABEN_PRESENT";
const G50 = "DE.A1.GRAMMAR.ADJECTIVES.PREDICATIVE";
const V04 = "DE.A1.VOCABULARY.NOUN_BUNDLE";
const W03 = "DE.A1.WRITING.FORM_COMPLETION";
const R03 = "DE.A1.READING.EXPLICIT_FACT";
const id = "DE.A1.U01.L04";
export const informationLessonSteps: readonly LessonStep[] = [
  {
    id: `${id}.discover`,
    stage: "discover",
    purpose: "teach",
    kind: "explanation",
    label: "Give a useful detail",
    prompt: "A familiar object, a simple description.",
    example: "Ich habe ein Telefon.\nDas Büro ist klein.",
    explanation:
      "‘I have a telephone.’ ‘The office is small.’ You will read an office note and fill a few fields for a fictional registration. klein means small; groß means large.",
    skillIds: [G03, G50, V04],
  },
  {
    id: `${id}.understand`,
    stage: "understand",
    purpose: "teach",
    kind: "explanation",
    label: "Have and describe",
    prompt: "Use habe for ‘I have’, ist for a description.",
    example:
      "Ich habe ein Telefon.\nNora hat zwei Telefone.\nDas Büro ist klein.\n\ndas Telefon — die Telefone\ndas Büro — die Büros",
    explanation:
      "With ich, use habe. With Nora (she), use hat. For now use the supplied telephone phrases; other object phrases come later.\nAfter ist, klein or groß describes the office without an extra adjective ending. Keep each familiar noun with its article; the plural forms are supplied.",
    skillIds: [G03, G50, V04],
  },
  {
    id: `${id}.recognize`,
    stage: "recognize",
    purpose: "practice",
    kind: "choice",
    label: "Choose a description",
    prompt: "Which sentence says that the office is small?",
    options: ["Das Büro ist klein.", "Das Büro ist groß.", "Ich habe ein Telefon."],
    correctAnswer: "Das Büro ist klein.",
    feedback: "klein means small. Das Büro ist klein describes the office.",
    skillIds: [G50],
  },
  {
    id: `${id}.recall`,
    stage: "recall",
    purpose: "practice",
    kind: "text",
    answerLanguage: "de",
    label: "Recall the verb",
    prompt: "Complete: Ich ___ ein Telefon. Type only the missing verb form.",
    inputLabel: "Missing word for possession",
    acceptedAnswers: ["habe", "Ich habe ein Telefon."],
    feedback: "Use habe with ich: Ich habe ein Telefon.",
    skillIds: [G03],
  },
  {
    id: `${id}.read`,
    stage: "read",
    purpose: "practice",
    kind: "text",
    answerLanguage: "de",
    label: "Read Nora's office note",
    prompt: "How many telephones does Nora have? Write digits.",
    example: "Ich bin Nora. Ich habe zwei Telefone. Das Büro ist klein.",
    inputLabel: "Number of telephones",
    acceptedAnswers: ["2"],
    feedback: "zwei Telefone means two telephones. The note states this directly.",
    skillIds: [R03, V04],
  },
  {
    id: `${id}.produce`,
    stage: "produce",
    purpose: "practice",
    kind: "text",
    answerLanguage: "de",
    label: "Describe a place",
    prompt: "Use all three parts to write ‘The office is large’: Das Büro · groß · ist",
    inputLabel: "Your office description",
    acceptedAnswers: ["Das Büro ist groß."],
    feedback: "Das Büro ist groß. Put ist second and groß after it, without an adjective ending.",
    skillIds: [G50, V04],
  },
  {
    id: `${id}.form-name`,
    stage: "apply",
    purpose: "practice",
    kind: "text",
    answerLanguage: "de",
    label: "Registration · name",
    prompt: "Fill the Name field for this fictional registration.",
    example: "Name: Mira\nDatum: 12.03.\nTelefone: 2",
    explanation:
      "Use the fictional details above. Name = name; Datum = date; Telefone = number of telephones. Fill one field at a time.",
    inputLabel: "Name field",
    acceptedAnswers: ["Mira"],
    feedback: "The Name field takes Mira, not the date or number.",
    skillIds: [W03],
  },
  {
    id: `${id}.form-date`,
    stage: "apply",
    purpose: "practice",
    kind: "text",
    answerLanguage: "de",
    label: "Registration · date",
    prompt: "Fill the Datum field. Use day.month format.",
    example: "Name: Mira\nDatum: 12.03.\nTelefone: 2",
    inputLabel: "Datum field",
    acceptedAnswers: ["12.03.", "12.3."],
    feedback: "Enter 12.03.: 12 March, in the day.month format practiced in Lesson 3.",
    skillIds: [W03],
  },
  {
    id: `${id}.form-count`,
    stage: "apply",
    purpose: "practice",
    kind: "text",
    answerLanguage: "de",
    label: "Registration · objects",
    prompt: "Fill the Telefone field with digits.",
    example: "Name: Mira\nDatum: 12.03.\nTelefone: 2",
    inputLabel: "Telefone field",
    acceptedAnswers: ["2"],
    feedback: "Enter 2. Telefone is the supplied plural of das Telefon.",
    skillIds: [W03, V04],
  },
  {
    id: `${id}.original`,
    stage: "apply",
    purpose: "practice",
    kind: "original",
    label: "Try a short introduction",
    prompt: "Introduce a fictional person, then describe an office in two short German sentences.",
    inputLabel: "Your two sentences",
    maxLength: 160,
    explanation:
      "Reuse Ich bin… and Das Büro ist klein/groß. Choose a fictional name. This open writing stays in this session and is unassessed; it is not part of the graded form fields.",
    skillIds: [G50, V04],
  },
  {
    id: `${id}.check`,
    stage: "check",
    purpose: "formative-check",
    kind: "text",
    answerLanguage: "de",
    label: "One last fact",
    prompt: "Who has a telephone? Write the name from the note.",
    example: "Ich bin Leo. Ich habe ein Telefon. Das Büro ist groß.",
    inputLabel: "Name from the office note",
    acceptedAnswers: ["Leo"],
    feedback:
      "Leo explicitly gives his name and says he has a telephone. This is a practice reading check, not a proficiency assessment.",
    skillIds: [R03, G03],
  },
];
