import { batchBAuthor } from "./german-a1-batch-b-assessment";
// Sixteen bounded tasks fit the existing unchanged persistence contract. The last task
// is an original three-point practical message, graded as ONE message dimension only.
const { item: i, form: f } = batchBAuthor("CP2", [
  {
    id: "personal",
    label: "Personal/basic information",
    scope: "A fictional introduction with name and place.",
  },
  {
    id: "familiar",
    label: "Familiar people, objects and routines",
    scope: "Two bounded observations of plural routine and negated object reference.",
  },
  {
    id: "reading",
    label: "Everyday reading/detail extraction",
    scope: "Two explicit form/date/price facts, not broad reading proficiency.",
  },
  { id: "time", label: "Time and changed plans", scope: "A changed time and a time-first plan." },
  {
    id: "place",
    label: "Place and service interaction",
    scope: "One reviewed location/transport frame and one polite help request.",
  },
  {
    id: "rules",
    label: "Requests, rules and instructions",
    scope: "A permission/prohibition detail and an appropriate instruction.",
  },
  {
    id: "message",
    label: "Practical message fulfilment",
    scope: "One original bounded message with all three requested points; no free-writing claim.",
  },
  {
    id: "recent",
    label: "Recent events and changed arrangements",
    scope: "A reviewed auxiliary frame, an earlier-state chunk and an explicit change purpose.",
  },
  {
    id: "transfer",
    label: "Transfer/revision",
    scope: "Choose relevant concrete information or repair a familiar frame without losing intent.",
  },
]);
export const cp2 = f("A", [
  i(
    "A",
    1,
    "personal",
    "construction",
    "Introduce yourself as Ada and say you live in Berlin. Write two complete sentences, each beginning Ich.",
    ["Ich bin Ada. Ich wohne in Berlin.", "Ich heiße Ada. Ich wohne in Berlin."],
  ),
  i(
    "A",
    2,
    "familiar",
    "construction",
    "Ben and Ada work today. Begin Ben und Ada, include heute and use arbeiten. Write one complete sentence.",
    ["Ben und Ada arbeiten heute."],
  ),
  i(
    "A",
    3,
    "familiar",
    "bounded-text",
    "You do not buy the particular pen. Rewrite Ich kaufe den Stift by replacing the object with its pronoun and adding nicht after that pronoun. Write the whole sentence.",
    ["Ich kaufe ihn nicht."],
  ),
  i(
    "A",
    4,
    "reading",
    "supported-field",
    "Fill the Ort field. Copy only the place noun.",
    ["Büro"],
    "Name: Ben. Termin: 22. Mai, 11 Uhr, Büro. Ort = place; Termin = appointment",
  ),
  i(
    "A",
    5,
    "reading",
    "reading-extraction",
    "Copy only the bag price, with Euro.",
    ["4 Euro"],
    "Buch: 7 Euro. Tasche: 4 Euro. Stift: 2 Euro.",
  ),
  i(
    "A",
    6,
    "time",
    "reading-extraction",
    "Copy only the new meeting time as a phrase beginning um.",
    ["um zehn"],
    "Treffen: vorher 8 Uhr, jetzt 10 Uhr. Treffen = meeting; vorher = before; jetzt = now",
  ),
  i(
    "A",
    7,
    "time",
    "construction",
    "Say Ada works at nine. Begin Um neun and use arbeiten. Write one complete sentence.",
    ["Um neun arbeitet Ada."],
  ),
  i(
    "A",
    8,
    "place",
    "construction",
    "You come from the office by bus. Begin Ich komme and write one sentence with mit dem Bus and aus dem Büro; either phrase order is accepted.",
    ["Ich komme mit dem Bus aus dem Büro.", "Ich komme aus dem Büro mit dem Bus."],
  ),
  i(
    "A",
    9,
    "place",
    "construction",
    "Ask a member of staff politely if they can help you and Ada. Begin Können Sie, use uns and helfen. Write a full question.",
    ["Können Sie uns helfen?"],
  ),
  i(
    "A",
    10,
    "rules",
    "reading-extraction",
    "Copy only the complete sentence that states what is forbidden.",
    ["Du darfst hier nicht essen."],
    "Du musst um acht kommen. Du darfst hier nicht essen. Du darfst um neun einkaufen.",
  ),
  i(
    "A",
    11,
    "rules",
    "construction",
    "Tell two friends to go to the bank. Begin Geht bitte and include zur Bank. Write one complete instruction.",
    ["Geht bitte zur Bank!"],
  ),
  i(
    "A",
    12,
    "recent",
    "construction",
    "Say Ada went to the station yesterday. Begin Ada, include gestern (yesterday), and use zum Bahnhof and gehen in the completed-action frame.",
    ["Ada ist gestern zum Bahnhof gegangen."],
  ),
  i(
    "A",
    13,
    "recent",
    "bounded-text",
    "The lack of time was earlier. Correct only the verb and write the whole statement.",
    ["Sie hatte keine Zeit."],
    "Draft: Sie hat keine Zeit.",
  ),
  i(
    "A",
    14,
    "recent",
    "reading-extraction",
    "Copy the sentence that offers the new possibility, not the cancellation.",
    ["Ich kann am Samstag kommen."],
    "Hallo Ben! Ich kann heute nicht kommen. Ich kann am Samstag kommen. Ada\nSamstag = Saturday",
  ),
  i(
    "A",
    15,
    "transfer",
    "reading-extraction",
    "You need the bank tomorrow at eleven. Copy only the label of the suitable notice.",
    ["B"],
    "A: Bank — heute ab 9 Uhr. B: Bank — morgen ab 10 Uhr. C: Büro — morgen ab 10 Uhr. ab = from",
  ),
  i(
    "A",
    16,
    "message",
    "construction",
    "Write an original practical reply with all three facts, in three independent sentences beginning Ich: you ate earlier; you must work today; you can come tomorrow at twelve. Use essen, heute arbeiten and morgen um zwölf kommen in that order. No greeting is required.",
    ["Ich habe gegessen. Ich muss heute arbeiten. Ich kann morgen um zwölf kommen."],
  ),
]);
export const cp2B = f("B", [
  i(
    "B",
    1,
    "personal",
    "bounded-text",
    "Use the form to correct BOTH personal details. Keep two full sentences beginning Ich.",
    ["Ich bin Ben. Ich wohne in Bonn."],
    "Form: Name Ben, Ort Bonn. Draft: Ich bin Ada. Ich wohne in Berlin. Ort = place",
  ),
  i(
    "B",
    2,
    "familiar",
    "bounded-text",
    "Correct the verb for the two people. Preserve every other word and write the whole sentence.",
    ["Ada und Ben lernen Deutsch."],
    "Draft: Ada und Ben lernt Deutsch.",
  ),
  i(
    "B",
    3,
    "familiar",
    "construction",
    "You do not need any pen, but need a bag. Write two independent sentences beginning Ich brauche, pen first, using Stift and Tasche with the correct indefinite articles.",
    ["Ich brauche keinen Stift. Ich brauche eine Tasche."],
  ),
  i(
    "B",
    4,
    "reading",
    "reading-extraction",
    "Copy only the appointment date in the format shown.",
    ["18.06."],
    "Preis: 5 Euro. Termin: 18.06., 12 Uhr. Ort: Bank. Termin = appointment",
  ),
  i(
    "B",
    5,
    "reading",
    "reading-extraction",
    "How many books does Ben have? Type only the number in digits.",
    ["9"],
    "Ada: Ich habe fünf Bücher. Ben: Ich habe neun Bücher.",
  ),
  i(
    "B",
    6,
    "time",
    "reading-extraction",
    "Which clock time is excluded? Copy only its phrase beginning um.",
    ["um sieben"],
    "Hallo Ada! Bitte um elf kommen, nicht um sieben. Ben",
  ),
  i(
    "B",
    7,
    "time",
    "bounded-text",
    "Repair the order, keeping every word and the time phrase first.",
    ["Am Dienstag kann Ben kommen."],
    "Draft: Am Dienstag Ben kann kommen. Dienstag = Tuesday",
  ),
  i(
    "B",
    8,
    "place",
    "bounded-text",
    "Correct both article and noun form for the accompaniment. Preserve the whole sentence.",
    ["Ich komme mit den Freunden."],
    "Draft: Ich komme mit die Freunde.",
  ),
  i(
    "B",
    9,
    "place",
    "bounded-text",
    "You address one friend as du, not staff. Repair the complete question while keeping the help directed to you.",
    ["Kannst du mir helfen?"],
    "Draft to Ben: Können Sie mir helfen?",
  ),
  i(
    "B",
    10,
    "rules",
    "reading-extraction",
    "Copy the full sentence stating a requirement, not a permission.",
    ["Du musst am Montag arbeiten."],
    "Du darfst heute lernen. Du musst am Montag arbeiten. Du darfst morgen essen.",
  ),
  i(
    "B",
    11,
    "rules",
    "bounded-text",
    "Address an unfamiliar visitor politely. Rewrite the whole instruction with Sie, preserving bitte and the destination.",
    ["Kommen Sie bitte ins Zentrum!"],
    "Draft: Komm bitte ins Zentrum! ins Zentrum = into/to the centre",
  ),
  i(
    "B",
    12,
    "recent",
    "bounded-text",
    "The auxiliary is wrong for seeing. Correct only that word and preserve the full sentence.",
    ["Ben hat Ada gesehen."],
    "Draft: Ben ist Ada gesehen.",
  ),
  i(
    "B",
    13,
    "recent",
    "construction",
    "The person referred to as er was sick earlier. Write one complete sentence starting Er using the reviewed earlier-state chunk. krank = sick.",
    ["Er war krank."],
  ),
  i(
    "B",
    14,
    "recent",
    "reading-extraction",
    "Copy only the label of the message that changes an arrangement and offers another day.",
    ["C"],
    "A: Ich habe eingekauft. B: Ich bin im Büro. C: Morgen kann ich nicht kommen. Am Sonntag kann ich kommen. Sonntag = Sunday",
  ),
  i(
    "B",
    15,
    "transfer",
    "bounded-text",
    "A colleague asks what you already did earlier. Repair this reply to report completed shopping, preserving Ich and heute.",
    ["Ich habe heute eingekauft."],
    "Draft: Ich kann heute einkaufen.",
  ),
  i(
    "B",
    16,
    "message",
    "construction",
    "Write a fresh reply with three separate sentences: first report that you arrived earlier, beginning Ich and using kommen; second say that you have no time tomorrow, beginning Morgen and using ich and keine Zeit; third offer to come to the bank on Sunday, beginning Am Sonntag and using ich, können, zur Bank and final kommen. Sonntag = Sunday.",
    ["Ich bin gekommen. Morgen habe ich keine Zeit. Am Sonntag kann ich zur Bank kommen."],
  ),
]);
export const cp2Forms = [cp2, cp2B] as const;
