import { batchBAuthor } from "./german-a1-batch-b-assessment";
const { item: i, form: f } = batchBAuthor("U08", [
  {
    id: "fields",
    label: "Complete a factual form",
    scope: "Place supplied fictional facts in named fields.",
  },
  {
    id: "relevance",
    label: "Select the suitable course",
    scope: "Match explicit city/day/time constraints; no hidden inference.",
  },
  {
    id: "question",
    label: "Request practical information",
    scope: "One complete wh-question for a missing course fact.",
  },
  { id: "change", label: "Read a schedule change", scope: "Extract one new or excluded time." },
  {
    id: "order",
    label: "Keep a time-first plan",
    scope: "A finite verb after a reviewed fronted time phrase.",
  },
  {
    id: "obligation",
    label: "State a required action",
    scope: "A complete müssen bracket in a supported work/study context.",
  },
  {
    id: "alternative",
    label: "Communicate a constraint and alternative",
    scope: "Two independent clauses preserving both requested times/actions.",
  },
  {
    id: "service",
    label: "Answer or ask the needed service detail",
    scope: "Supply the genuinely missing practical information.",
  },
  {
    id: "register",
    label: "Address the right listener",
    scope: "A reviewed du/Sie help frame appropriate to the supplied relationship.",
  },
  {
    id: "revision",
    label: "Revise a targeted response",
    scope: "Correct one explicit meaning-changing detail while retaining the remaining message.",
  },
]);
export const unit8Check = f("A", [
  i(
    "A",
    1,
    "fields",
    "bounded-text",
    "Complete two fields from the supplied registration. Type exactly Name: …; Ort: … .",
    ["Name: Ben; Ort: Berlin"],
    "Fictional learner: Ben. City: Berlin. Course time: 20 Uhr.",
  ),
  i(
    "A",
    2,
    "relevance",
    "choice",
    "You need a Bonn course on Wednesday at nineteen. Which offer meets all three facts?",
    ["C"],
    "A: Bonn, Mittwoch, 9 Uhr. B: Berlin, Mittwoch, 19 Uhr. C: Bonn, Mittwoch, 19 Uhr. Mittwoch = Wednesday",
    ["A", "B", "C"],
  ),
  i(
    "A",
    3,
    "question",
    "construction",
    "Ask where the course is. Use der Kurs (the course) and begin Wo. Write a full question.",
    ["Wo ist der Kurs?"],
  ),
  i(
    "A",
    4,
    "change",
    "reading-extraction",
    "Copy only the new course time, using digits and Uhr.",
    ["15 Uhr"],
    "Kurs: alt 17 Uhr, neu 15 Uhr. Kurs = course; alt/neu = old/new",
  ),
  i(
    "A",
    5,
    "order",
    "construction",
    "Say Ben comes at eighteen. Begin Um achtzehn and use kommen. Write one full sentence. achtzehn = eighteen.",
    ["Um achtzehn kommt Ben."],
  ),
  i(
    "A",
    6,
    "obligation",
    "construction",
    "You are required to study today. Begin Ich and use heute and lernen in one full statement.",
    ["Ich muss heute lernen."],
  ),
  i(
    "A",
    7,
    "alternative",
    "construction",
    "You must work on Wednesday but can come Thursday. Write two independent sentences beginning Am Mittwoch and Am Donnerstag respectively; use ich and arbeiten/kommen in that order. Mittwoch = Wednesday; Donnerstag = Thursday.",
    ["Am Mittwoch muss ich arbeiten. Am Donnerstag kann ich kommen."],
  ),
  i(
    "A",
    8,
    "service",
    "reading-extraction",
    "A learner asks the course time. Give only the complete German statement beginning Der Kurs ist; use the note's time in words.",
    ["Der Kurs ist um zwanzig.", "Der Kurs ist um zwanzig Uhr."],
    "Kurs: Büro, 20 Uhr. zwanzig = twenty; Büro = office",
  ),
  i(
    "A",
    9,
    "register",
    "construction",
    "Ask an unfamiliar member of staff to help you and Ben. Write Guten Tag!, then a full Sie question with uns, am Freitag and helfen; close Vielen Dank!.",
    ["Guten Tag! Können Sie uns am Freitag helfen? Vielen Dank!"],
  ),
  i(
    "A",
    10,
    "revision",
    "bounded-text",
    "The meeting is on Tuesday, not Wednesday. Correct only the excluded day in the SECOND sentence. Keep the first sentence and every other word; write both complete sentences. Mittwoch = Wednesday.",
    ["Ich komme am Dienstag um zehn ins Büro. Das Treffen ist nicht am Mittwoch."],
    "Draft: Ich komme am Dienstag um zehn ins Büro. Das Treffen ist nicht am Dienstag. Treffen = meeting; ins Büro = into/to the office",
  ),
]);
export const unit8CheckB = f("B", [
  i(
    "B",
    1,
    "fields",
    "bounded-text",
    "The form fields are reversed. Correct only their values and return exactly Name: …; Uhrzeit: … .",
    ["Name: Ada; Uhrzeit: 16 Uhr"],
    "Fictional learner: Ada. Appointment: 16 Uhr. Draft: Name: 16 Uhr; Uhrzeit: Ada.",
  ),
  i(
    "B",
    2,
    "relevance",
    "reading-extraction",
    "You need Berlin on Saturday at ten. Copy only the label of the suitable course.",
    ["B"],
    "A: Berlin, Samstag, 18 Uhr. B: Berlin, Samstag, 10 Uhr. C: Bonn, Samstag, 10 Uhr. Samstag = Saturday",
  ),
  i(
    "B",
    3,
    "question",
    "bounded-text",
    "The course location is already known, but the time is missing. Change only the wh-word and write the whole question.",
    ["Wann ist der Kurs?"],
    "Draft: Wo ist der Kurs? Kurs = course",
  ),
  i(
    "B",
    4,
    "change",
    "reading-extraction",
    "Copy only the explicitly excluded time phrase, starting um.",
    ["um zwölf"],
    "Bitte um vierzehn kommen, nicht um zwölf. vierzehn = fourteen",
  ),
  i(
    "B",
    5,
    "order",
    "bounded-text",
    "Repair the order, preserving all words and the time phrase first.",
    ["Am Freitag arbeitet Ada."],
    "Draft: Am Freitag Ada arbeitet. Freitag = Friday",
  ),
  i(
    "B",
    6,
    "obligation",
    "bounded-text",
    "The note gives a requirement, not permission. Correct only the modal and write the full statement.",
    ["Ich muss am Samstag arbeiten."],
    "Requirement: work Saturday. Draft: Ich darf am Samstag arbeiten. Samstag = Saturday",
  ),
  i(
    "B",
    7,
    "alternative",
    "bounded-text",
    "The first action is required. Repair only its modal; preserve the offered alternative and write both complete sentences.",
    ["Um neun muss ich lernen. Um dreizehn kann ich kommen."],
    "Draft: Um neun darf ich lernen. Um dreizehn kann ich kommen. dreizehn = thirteen",
  ),
  i(
    "B",
    8,
    "service",
    "construction",
    "You need to know whether you may come to the office on Friday. Write a complete possibility question beginning Kann ich, then am Freitag, ins Büro and final kommen. Freitag = Friday; ins Büro = into/to the office.",
    ["Kann ich am Freitag ins Büro kommen?"],
  ),
  i(
    "B",
    9,
    "register",
    "bounded-text",
    "You are asking one close friend, not staff. Correct the complete question for du; keep the help directed to you.",
    ["Kannst du mir helfen?"],
    "Draft to Ada: Können Sie mir helfen?",
  ),
  i(
    "B",
    10,
    "revision",
    "bounded-text",
    "The reply must preserve all requested facts: Sunday, fourteen, bank; Saturday is excluded. Correct only the first sentence's wrong time. Keep the second sentence unchanged and write both sentences. Sonntag = Sunday; Samstag = Saturday; vierzehn = fourteen.",
    ["Ja, ich komme am Sonntag um vierzehn zur Bank. Das Treffen ist nicht am Samstag."],
    "Draft: Ja, ich komme am Sonntag um fünfzehn zur Bank. Das Treffen ist nicht am Samstag. fünfzehn = fifteen; Treffen = meeting",
  ),
]);
export const unit8CheckForms = [unit8Check, unit8CheckB] as const;
