import type { ChallengeItem } from "@/lib/curriculum/challenge";
const t = (
  id: string,
  outcome: string,
  prompt: string,
  answers: string[],
  stimulus?: string,
): ChallengeItem => ({
  id,
  outcome,
  prompt,
  acceptedAnswers: answers,
  ...(stimulus ? { stimulus } : {}),
});
const c = (
  id: string,
  outcome: string,
  prompt: string,
  options: string[],
  answer: string,
  stimulus?: string,
): ChallengeItem => ({ ...t(id, outcome, prompt, [answer], stimulus), options });
// Original held-out contexts. Public views omit keys; no changes to grading, threshold or storage.
export const batchCChallengeForms: Record<string, Record<"A" | "B", readonly ChallengeItem[]>> = {
  "DE.A1.U07": {
    A: [
      t(
        "detail",
        "Travel price",
        "Copy only the bus ticket price, including Euro.",
        ["9 Euro"],
        "Zug: 12 Euro, 15 Uhr. Bus: 9 Euro, 17 Uhr. Zug = train",
      ),
      t(
        "changed",
        "Current departure",
        "Copy only the new departure time, with digits and Uhr.",
        ["18 Uhr"],
        "Abfahrt: alt 16 Uhr, neu 18 Uhr. Abfahrt = departure; alt/neu = old/new",
      ),
      t(
        "ticket",
        "Polite ticket request",
        "Politely ask to buy a ticket to Berlin. Begin Ich, use eine Fahrkarte and nach Berlin, ending kaufen. Write one whole sentence.",
        [
          "Ich möchte eine Fahrkarte nach Berlin kaufen.",
          "Ich möchte nach Berlin eine Fahrkarte kaufen.",
        ],
      ),
      c(
        "room",
        "Availability",
        "Which statement matches the note?",
        ["Es gibt ein Zimmer.", "Es gibt kein Zimmer."],
        "Es gibt kein Zimmer.",
        "Heute: kein Zimmer frei. Zimmer = room; frei = available",
      ),
      t(
        "service",
        "Arrival enquiry",
        "Ask whether you can arrive at nineteen on Sunday. Begin Kann ich, use am Sonntag then um neunzehn and final kommen. Sonntag = Sunday; neunzehn = nineteen.",
        ["Kann ich am Sonntag um neunzehn kommen?", "Kann ich am Sonntag um neunzehn Uhr kommen?"],
      ),
      t(
        "location",
        "Changed location",
        "The new meeting is already taking place at the station, not at the bank. Write only its current location statement, beginning Das Treffen ist with the reviewed station-location chunk. Treffen = meeting.",
        ["Das Treffen ist am Bahnhof."],
        "Treffen: jetzt Bahnhof, nicht Bank. jetzt = now",
      ),
      t(
        "update",
        "Travel update",
        "Give your friend the new plan in two full sentences beginning Ich: you are at the bank now; you can come at twenty. Use bei der Bank first, then um zwanzig with final kommen. zwanzig = twenty.",
        ["Ich bin bei der Bank. Ich kann um zwanzig kommen."],
      ),
      t(
        "transfer",
        "Relevant earlier event",
        "Your friend asks what you did earlier. Say you went to the bank and then studied. Write two independent completed-action sentences, each beginning Ich, using zur Bank/gehen first and lernen second.",
        ["Ich bin zur Bank gegangen. Ich habe gelernt."],
      ),
    ],
    B: [
      t(
        "detail",
        "Travel date",
        "Copy only the date in the note's format.",
        ["27. Juni"],
        "Bus nach Berlin — 27. Juni, 19 Uhr, 5 Euro. Juni = June",
      ),
      c(
        "changed",
        "Interpret an update",
        "How did the departure time change?",
        ["Earlier.", "Later.", "Unchanged."],
        "Earlier.",
        "Abfahrt: vorher 17 Uhr, jetzt 14 Uhr. Abfahrt = departure; vorher/jetzt = before/now",
      ),
      t(
        "ticket",
        "Repair a request bracket",
        "Repair the word order, keeping every word and starting Ich. Write the full polite request.",
        ["Ich möchte eine Fahrkarte kaufen."],
        "Draft: Ich möchte kaufen eine Fahrkarte.",
      ),
      t(
        "room",
        "Retrieve the excluded day",
        "Copy only the day phrase on which no room is available.",
        ["Am Sonntag", "am Sonntag"],
        "Am Samstag gibt es ein Zimmer. Am Sonntag gibt es kein Zimmer. Zimmer = room; Samstag = Saturday; Sonntag = Sunday",
      ),
      t(
        "service",
        "A missing arrival fact",
        "Ask when you can come; the room message gives no time. Begin Wann and use ich and kommen in one full possibility question.",
        ["Wann kann ich kommen?"],
        "Guten Tag! Am Mittwoch gibt es ein Zimmer. Mittwoch = Wednesday; Zimmer = room",
      ),
      t(
        "location",
        "Repair a destination",
        "You are going to the station, not already there. Rewrite the full statement beginning Ich gehe and use the reviewed station destination.",
        ["Ich gehe zum Bahnhof."],
        "Draft: Ich bin am Bahnhof.",
      ),
      t(
        "update",
        "Repair the changed place",
        "The new meeting is at the station at eighteen. Repair ONLY the destination in this reply and preserve every other word.",
        ["Hallo Ben! Ich komme um achtzehn zum Bahnhof."],
        "Draft: Hallo Ben! Ich komme um achtzehn zur Bank. achtzehn = eighteen",
      ),
      t(
        "transfer",
        "Answer a future possibility",
        "Ada wants to know whether Ben can come Friday at seventeen. He can. Write one full statement beginning Am Freitag, using Ben and um siebzehn, ending kommen. Freitag = Friday; siebzehn = seventeen.",
        ["Am Freitag kann Ben um siebzehn kommen."],
      ),
    ],
  },
  "DE.A1.U08": {
    A: [
      t(
        "form",
        "Correct field placement",
        "Complete two fields: Name: …; Uhrzeit: … . Use the supplied fictional facts.",
        ["Name: Ada; Uhrzeit: 19 Uhr"],
        "Learner: Ada. Course: Bonn, 19 Uhr. Uhrzeit = clock time",
      ),
      c(
        "course",
        "Relevant course",
        "You need a Berlin course Monday at twenty. Choose the fitting offer.",
        ["A", "B", "C"],
        "A",
        "A: Berlin, Montag, 20 Uhr. B: Bonn, Montag, 20 Uhr. C: Berlin, Montag, 18 Uhr.",
      ),
      t(
        "change",
        "Current schedule",
        "Copy only the updated clock time, with Uhr.",
        ["12 Uhr"],
        "Treffen: vorher 9 Uhr, jetzt 12 Uhr. Treffen = meeting; vorher/jetzt = before/now",
      ),
      t(
        "obligation",
        "Time-first requirement",
        "You must study on Friday. Begin Am Freitag, use ich and lernen. Write one whole sentence. Freitag = Friday.",
        ["Am Freitag muss ich lernen."],
      ),
      t(
        "enquiry",
        "Relevant service question",
        "You need the course time. Write a full question beginning Wann and using der Kurs (the course).",
        ["Wann ist der Kurs?"],
      ),
      t(
        "reply",
        "Constraint and alternative",
        "You must work at eleven but can come at fifteen. Write two full sentences beginning Ich, using um elf/um fünfzehn and arbeiten/kommen respectively. fünfzehn = fifteen.",
        ["Ich muss um elf arbeiten. Ich kann um fünfzehn kommen."],
      ),
      t(
        "register",
        "Polite group request",
        "Ask an unfamiliar member of staff to help you and Ada tomorrow. Write one full Sie question beginning Können, using uns, morgen and helfen in that order.",
        ["Können Sie uns morgen helfen?"],
      ),
      t(
        "revision",
        "Focused excluded-day correction",
        "The meeting is Saturday, not Friday. Correct ONLY the excluded day in the draft; preserve the whole sentence. Freitag = Friday.",
        ["Das Treffen ist nicht am Freitag."],
        "Draft: Das Treffen ist nicht am Samstag. Treffen = meeting; Samstag = Saturday",
      ),
    ],
    B: [
      t(
        "form",
        "Repair reversed fields",
        "Repair both values and return exactly Ort: …; Name: … .",
        ["Ort: Bonn; Name: Ben"],
        "Fictional registration: Ben, Bonn. Draft: Ort: Ben; Name: Bonn. Ort = place",
      ),
      t(
        "course",
        "Missing course place",
        "Ask the missing course location as one full question beginning Wo, using der Kurs (the course).",
        ["Wo ist der Kurs?"],
        "Course information: Freitag, 18 Uhr. Place: not supplied. Freitag = Friday",
      ),
      t(
        "change",
        "Excluded time",
        "Copy only the excluded clock-time phrase, beginning um.",
        ["um elf"],
        "Bitte um neunzehn kommen, nicht um elf. neunzehn = nineteen",
      ),
      t(
        "obligation",
        "Repair a requirement",
        "The action is required, not merely allowed. Correct ONLY the modal and preserve the full sentence.",
        ["Um vierzehn muss ich arbeiten."],
        "Draft: Um vierzehn darf ich arbeiten. vierzehn = fourteen",
      ),
      t(
        "enquiry",
        "Possibility enquiry",
        "Ask whether you can come Monday at thirteen. Begin Kann ich, then am Montag, um dreizehn and final kommen. dreizehn = thirteen.",
        ["Kann ich am Montag um dreizehn kommen?"],
      ),
      t(
        "reply",
        "Keep an offered alternative",
        "Repair only the order in the second sentence, retaining both sentences and the fronted time.",
        ["Ich muss heute lernen. Um siebzehn kann ich kommen."],
        "Draft: Ich muss heute lernen. Um siebzehn ich kann kommen. siebzehn = seventeen",
      ),
      t(
        "register",
        "Friend enquiry",
        "Ask a close friend to help you at twelve. Rewrite the complete question for du; keep mir and um zwölf.",
        ["Kannst du mir um zwölf helfen?"],
        "Draft to Ben: Können Sie mir um zwölf helfen?",
      ),
      t(
        "revision",
        "Targeted time revision",
        "The confirmed visit is Thursday at eighteen to the office. Correct ONLY the wrong time; preserve every other word and write the full reply. achtzehn = eighteen.",
        ["Ja, ich komme am Donnerstag um achtzehn ins Büro."],
        "Draft: Ja, ich komme am Donnerstag um sechzehn ins Büro. Donnerstag = Thursday; sechzehn = sixteen; ins Büro = into/to the office",
      ),
    ],
  },
};
