import { lessonAuthor } from "./german-a1-batch-a-lesson";
// Original bounded prototype practice; final assessment families are authored separately.
const a1 = lessonAuthor("09", 1);
const skills1 = [
  "DE.A1.WRITING.DESCRIPTION",
  "DE.A1.GRAMMAR.VERBS.HABEN_PRESENT",
  "DE.A1.GRAMMAR.ADJECTIVES.PREDICATIVE",
  "DE.A1.GRAMMAR.PAST.WAR_HATTE",
  "DE.A1.VOCABULARY.NOUN_BUNDLE",
];
export const unit9Lesson1Steps = [
  a1.explain(
    "scene",
    "An everyday need",
    "Read Ada’s message to a friend. What does she need?",
    "Ich bin müde. Ich brauche Hilfe.",
    "müde = tired; Hilfe = help. Describe a need without diagnosing a condition. This is language practice.",
    [skills1[0], skills1[2], skills1[4]],
  ),
  a1.choice(
    "s2",
    "recognize",
    "Read the need",
    "What does Ada ask for?",
    ["Help.", "A ticket.", "A room."],
    "Help.",
    "Hilfe is the concrete need in the message.",
    [skills1[0], skills1[4]],
  ),
  a1.explain(
    "s3",
    "Current and earlier",
    "Compare a current state with a short report about yesterday.",
    "Heute bin ich müde. Gestern war ich müde. Gestern hatte ich keine Zeit.",
    "war / hatte are already reviewed past chunks. müde stays unchanged after bin/war; keine Zeit means no time.",
    [skills1[1], skills1[2], skills1[3]],
  ),
  a1.text(
    "s4",
    "recall",
    "Retrieve a familiar need",
    "From memory: say you need help. Begin Ich and use Hilfe.",
    ["Ich brauche Hilfe."],
    "A full need statement, not a medical conclusion.",
    [skills1[4]],
  ),
  a1.text(
    "s5",
    "produce",
    "Describe today",
    "Say Ben is tired today. Begin Ben; use heute.",
    ["Ben ist heute müde.", "Ben ist heute muede.", "Ben ist müde heute.", "Ben ist muede heute."],
    "Describe Ben’s state using familiar words.",
    [skills1[0], skills1[2]],
  ),
  a1.choice(
    "s6",
    "classify",
    "Choose the time frame",
    "Your friend asks about yesterday. Choose the relevant reply.",
    ["Ich bin müde.", "Ich war müde."],
    "Ich war müde.",
    "war reports the earlier state.",
    [skills1[3]],
  ),
  a1.text(
    "s7",
    "produce",
    "Use a known noun bundle",
    "Say you have no time today. Begin Ich and use heute.",
    ["Ich habe heute keine Zeit."],
    "habe + keine Zeit expresses an ordinary practical problem.",
    [skills1[1], skills1[4]],
  ),
  a1.text(
    "s8",
    "apply",
    "Explain the earlier problem",
    "Say you had no time yesterday. Begin Gestern.",
    ["Gestern hatte ich keine Zeit."],
    "Keep the earlier time and the familiar had-no-time chunk.",
    [skills1[3]],
  ),
  a1.choice(
    "s9",
    "apply",
    "Stay within the facts",
    "A note says Ben needs help. Which statement can you make?",
    ["Ben braucht Hilfe.", "Ben ist krank."],
    "Ben braucht Hilfe.",
    "No illness is stated; do not invent one. krank = ill.",
    [skills1[0], skills1[4]],
  ),
  a1.text(
    "s10",
    "check",
    "A new need message",
    "Tell your friend: you are tired and need time. Write two sentences beginning Ich, using müde then Zeit.",
    ["Ich bin müde. Ich brauche Zeit.", "Ich bin muede. Ich brauche Zeit."],
    "Both supplied points are communicated; no medical knowledge is assessed.",
    [skills1[0], skills1[2], skills1[4]],
  ),
];
const a2 = lessonAuthor("09", 2);
const skills2 = [
  "DE.A1.READING.PERMISSION_NOTICE",
  "DE.A1.READING.SIMPLE_INSTRUCTION",
  "DE.A1.GRAMMAR.MODALS.DUERFEN",
  "DE.A1.GRAMMAR.IMPERATIVE.DU",
  "DE.A1.GRAMMAR.IMPERATIVE.SIE",
];
export const unit9Lesson2Steps = [
  a2.explain(
    "scene",
    "A community notice",
    "Read the instruction at the office.",
    "Bitte warten Sie hier. Sie dürfen jetzt nicht ins Büro gehen.",
    "warten = wait; hier = here. The notice asks you to wait here and forbids entering now. No rule beyond this notice is implied.",
    [skills2[0], skills2[1]],
  ),
  a2.choice(
    "s2",
    "recognize",
    "Required action",
    "What must you do now?",
    ["Wait here.", "Enter the office."],
    "Wait here.",
    "The explicit instruction is to wait here.",
    [skills2[1]],
  ),
  a2.choice(
    "s3",
    "classify",
    "Permission is not requirement",
    "Read the new sign. Is sitting allowed or required?",
    ["Allowed.", "Required."],
    "Allowed.",
    "dürfen expresses permission, not a requirement.",
    [skills2[2]],
    "Sie dürfen hier sitzen. sitzen = sit",
  ),
  a2.text(
    "s4",
    "recall",
    "Retrieve permission",
    "Recall the verb in Ich … hier warten: I may wait here. Type only the missing verb.",
    ["darf"],
    "darf is the familiar permission frame.",
    [skills2[2]],
  ),
  a2.explain(
    "s5",
    "Two listeners",
    "Compare one close friend and an unfamiliar visitor.",
    "Warte hier! / Warten Sie bitte hier!",
    "du instruction: Warte! Polite Sie instruction: Warten Sie … . Both tell someone to wait, not ask about their schedule.",
    [skills2[3], skills2[4]],
  ),
  a2.text(
    "s6",
    "produce",
    "Ask a visitor to wait",
    "Address an unfamiliar visitor. Begin Warten Sie and include bitte hier.",
    ["Warten Sie bitte hier!"],
    "The polite instruction has the action first, then Sie.",
    [skills2[4]],
  ),
  a2.text(
    "s7",
    "produce",
    "One friend",
    "Tell one close friend to come to the station. Begin Komm and include bitte zum Bahnhof.",
    ["Komm bitte zum Bahnhof!"],
    "A practical du instruction using an already reviewed destination.",
    [skills2[3]],
  ),
  a2.choice(
    "s8",
    "apply",
    "Read an access update",
    "Which action is allowed now?",
    ["Enter now.", "Enter tomorrow only."],
    "Enter now.",
    "jetzt gives permission now.",
    [skills2[0], skills2[2]],
    "Sie dürfen jetzt ins Büro gehen. jetzt = now",
  ),
  a2.text(
    "s9",
    "apply",
    "Keep the prohibition",
    "Say you may not go to the office today. Begin Ich and use heute, nicht, ins Büro and gehen.",
    ["Ich darf heute nicht ins Büro gehen.", "Ich darf heute nicht ins Buero gehen."],
    "Keep both the permission frame and explicit prohibition.",
    [skills2[2]],
  ),
  a2.text(
    "s10",
    "check",
    "A fresh practical instruction",
    "The staff asks a visitor to come tomorrow at ten. Write a polite instruction beginning Kommen Sie, with bitte, morgen, um zehn.",
    ["Kommen Sie bitte morgen um zehn!", "Kommen Sie bitte morgen um zehn Uhr!"],
    "A clear action, day and time; not an access or health judgment.",
    [skills2[4]],
  ),
];
const a3 = lessonAuthor("09", 3);
const skills3 = [
  "DE.A1.WRITING.INVITATION_RESPONSE",
  "DE.A1.WRITING.APOLOGY_CHANGE",
  "DE.A1.WRITING.TIME_PLACE",
  "DE.A1.GRAMMAR.CONNECTORS.ABER_ODER",
  "DE.A1.VOCABULARY.TRANSFER_SELECTION",
];
export const unit9Lesson3Steps = [
  a3.explain(
    "scene",
    "Invite a friend",
    "Read an invitation and the response it requests.",
    "Hallo Ben! Komm bitte am Samstag um zehn zum Bahnhof. Kannst du kommen?",
    "Samstag = Saturday. The invitation names day, time and place; the last question asks for a response.",
    [skills3[0], skills3[2]],
  ),
  a3.choice(
    "s2",
    "recognize",
    "Find all details",
    "Where is the meeting?",
    ["At the station.", "At the bank."],
    "At the station.",
    "zum Bahnhof is the station destination.",
    [skills3[2]],
  ),
  a3.explain(
    "s3",
    "A useful change",
    "A decline can include an alternative.",
    "Tut mir leid! Ich muss am Samstag arbeiten. Ich kann am Sonntag kommen.",
    "Tut mir leid! = Sorry! Sonntag = Sunday. Familiar short clauses explain the constraint and offer a next step.",
    [skills3[1], skills3[3]],
  ),
  a3.text(
    "s4",
    "recall",
    "Retrieve the response",
    "Recall how to ask one friend whether they can come. Write a full question.",
    ["Kannst du kommen?"],
    "This asks for the response you need.",
    [skills3[0]],
  ),
  a3.text(
    "s5",
    "produce",
    "Accept with useful details",
    "Accept: you will come Monday at eleven to the bank. Begin Ja, ich komme; use am Montag, um elf, zur Bank.",
    ["Ja, ich komme am Montag um elf zur Bank."],
    "Acceptance retains all three stated details.",
    [skills3[0], skills3[2]],
  ),
  a3.choice(
    "s6",
    "classify",
    "Choose a useful decline",
    "Which reply gives an alternative?",
    ["Nein.", "Ich kann heute nicht kommen, aber morgen kann ich kommen."],
    "Ich kann heute nicht kommen, aber morgen kann ich kommen.",
    "aber connects the constraint to a useful alternative.",
    [skills3[1], skills3[3]],
  ),
  a3.text(
    "s7",
    "produce",
    "Offer a choice",
    "Ask one friend: today or tomorrow? Use Kannst du, heute oder morgen, kommen.",
    ["Kannst du heute oder morgen kommen?"],
    "The familiar question offers two concrete options.",
    [skills3[3], skills3[4]],
  ),
  a3.text(
    "s8",
    "apply",
    "Cancel today’s plan",
    "Say sorry, you cannot come today. Write Tut mir leid!, then Ich with heute nicht and kommen.",
    ["Tut mir leid! Ich kann heute nicht kommen."],
    "The cancellation is explicit and stays within the facts.",
    [skills3[1]],
  ),
  a3.text(
    "s9",
    "apply",
    "Repair the invitation",
    "The meeting moved to the bank. Change only the destination; keep every other word.",
    ["Komm bitte am Dienstag um zwölf zur Bank!", "Komm bitte am Dienstag um zwoelf zur Bank!"],
    "Only the place changes.",
    [skills3[2]],
    "Draft: Komm bitte am Dienstag um zwölf zum Bahnhof!",
  ),
  a3.text(
    "s10",
    "check",
    "A new changed plan",
    "Tell Ada: sorry, you cannot come Friday; you can come Saturday at fourteen to the bank. Write Tut mir leid!, then two Ich sentences. Freitag = Friday; Samstag = Saturday; vierzehn = fourteen.",
    [
      "Tut mir leid! Ich kann am Freitag nicht kommen. Ich kann am Samstag um vierzehn zur Bank kommen.",
    ],
    "The cancellation and the alternative include the necessary time/place.",
    [skills3[0], skills3[1], skills3[2], skills3[4]],
  ),
];
const a4 = lessonAuthor("09", 4);
const skills4 = [
  "DE.A1.WRITING.TASK_FULFILMENT",
  "DE.A1.WRITING.REGISTER",
  "DE.A1.WRITING.SHORT_MESSAGE",
  "DE.A1.WRITING.APOLOGY_CHANGE",
  "DE.A1.READING.MAIN_PURPOSE",
];
export const unit9Lesson4Steps = [
  a4.explain(
    "scene",
    "A fresh service message",
    "Read this new message before deciding what your reply must do.",
    "Guten Tag! Das Treffen ist am Donnerstag um dreizehn bei der Bank, nicht im Büro. Können Sie kommen? Vielen Dank!",
    "Donnerstag = Thursday; dreizehn = thirteen; Treffen = meeting. No model reply is supplied: decide the needed information yourself.",
    [skills4[4]],
  ),
  a4.choice(
    "s2",
    "recognize",
    "Overall purpose",
    "What does the sender need?",
    ["Confirmation of attendance.", "A price.", "A name field."],
    "Confirmation of attendance.",
    "The message asks whether you can attend.",
    [skills4[4]],
  ),
  a4.choice(
    "s3",
    "classify",
    "Keep the correction",
    "Which place is current?",
    ["The bank.", "The office."],
    "The bank.",
    "The office is explicitly excluded.",
    [skills4[4]],
  ),
  a4.text(
    "s4",
    "recall",
    "Retrieve a closing",
    "Recall the familiar two-word polite thanks closing.",
    ["Vielen Dank!"],
    "A service closing, not a full reply template.",
    [skills4[2]],
  ),
  a4.choice(
    "s5",
    "classify",
    "Address the sender",
    "For unfamiliar staff, which address is suitable?",
    ["Sie", "du"],
    "Sie",
    "Use the formal address for this relationship.",
    [skills4[1]],
  ),
  a4.text(
    "s6",
    "produce",
    "Supply the requested confirmation",
    "You can come Thursday at thirteen. Begin Ja, ich kann and give day/time; finish kommen.",
    [
      "Ja, ich kann am Donnerstag um dreizehn kommen.",
      "Ja, ich kann am Donnerstag um dreizehn Uhr kommen.",
    ],
    "This answers the actual attendance question.",
    [skills4[0], skills4[2]],
  ),
  a4.text(
    "s7",
    "apply",
    "State a different constraint",
    "You must work Thursday. State this fact beginning Am Donnerstag.",
    ["Am Donnerstag muss ich arbeiten."],
    "A practical constraint without invented explanation.",
    [skills4[3]],
  ),
  a4.choice(
    "s8",
    "apply",
    "Offer a next step",
    "The sender knows the bank, but no alternative day is given. Which question seeks a useful missing fact?",
    ["Kann ich am Freitag kommen?", "Wo ist die Bank?"],
    "Kann ich am Freitag kommen?",
    "Ask about an alternative rather than repeat the known location.",
    [skills4[0], skills4[3]],
  ),
  a4.text(
    "s9",
    "apply",
    "Correct one misleading day",
    "Only the day is wrong: you can come Friday, not Thursday. Preserve the rest.",
    ["Guten Tag! Ich kann am Freitag kommen. Vielen Dank!"],
    "Targeted revision keeps register and content.",
    [skills4[1], skills4[3]],
    "Draft: Guten Tag! Ich kann am Donnerstag kommen. Vielen Dank!",
  ),
  a4.text(
    "s10",
    "check",
    "Respond to an unfamiliar message",
    "New staff message asks if you can come Sunday at sixteen to the office. You can. Write Guten Tag!, a Ja, ich komme sentence with all three details, and Vielen Dank!. Sonntag = Sunday; sechzehn = sixteen.",
    [
      "Guten Tag! Ja, ich komme am Sonntag um sechzehn ins Büro. Vielen Dank!",
      "Guten Tag! Ja, ich komme am Sonntag um sechzehn ins Buero. Vielen Dank!",
    ],
    "The fresh response gives the needed next action in suitable register.",
    [skills4[0], skills4[1], skills4[2]],
  ),
];
