import type { LessonStep } from "@/lib/curriculum/types";

// Original Karta registration-desk lesson revised to Lesson Standard v2.
// Expert publication review remains deferred.
const G14 = "DE.A1.GRAMMAR.QUESTIONS.YES_NO";
const G15 = "DE.A1.GRAMMAR.QUESTIONS.WH";
const G52 = "DE.A1.GRAMMAR.QUANTITY.NUMBER_NOUN";
const V03 = "DE.A1.VOCABULARY.NUMERIC_TIME";
const R02 = "DE.A1.READING.NUMERIC_DETAILS";
const id = "DE.A1.U01.L03";

export const detailsLessonSteps: readonly LessonStep[] = [
  {
    id: `${id}.context`,
    stage: "discover",
    purpose: "teach",
    kind: "explanation",
    label: "Ask for a detail",
    prompt: "At a registration desk, you sometimes check information and sometimes ask for new information.",
    example: "Bist du Mira?\nWer bist du?",
    explanation:
      "Bist du Mira? checks one idea: ‘Are you Mira?’ Wer bist du? asks for the person's identity: ‘Who are you?’ These two question types use different openings.",
    skillIds: [G14, G15],
  },
  {
    id: `${id}.model`,
    stage: "understand",
    purpose: "teach",
    kind: "explanation",
    label: "Notice the question order",
    prompt: "Compare a statement with two questions.",
    example: "Du bist Mira.\nBist du Mira?\nWer bist du?",
    explanation:
      "A yes/no question starts with the verb: Bist du Mira? A detail question starts with a question word, then the verb: Wer bist du? The verb stays near the front in both patterns.",
    skillIds: [G14, G15],
  },
  {
    id: `${id}.notice`,
    stage: "recognize",
    purpose: "practice",
    kind: "choice",
    label: "Choose the question you need",
    prompt: "You do not know the person's name. Which question asks for it?",
    options: ["Wer bist du?", "Bist du Nora?", "Was ist das?"],
    correctAnswer: "Wer bist du?",
    feedback: "Wer bist du? asks who the person is.",
    skillIds: [G15],
  },
  {
    id: `${id}.controlled-question`,
    stage: "recall",
    purpose: "practice",
    kind: "text",
    answerLanguage: "de",
    label: "Build a yes/no question",
    prompt: "Use all three words to ask ‘Are you Mira?’: du · Mira · bist",
    inputLabel: "German question",
    acceptedAnswers: ["Bist du Mira?"],
    feedback: "Put bist first, then du, then Mira: Bist du Mira?",
    skillIds: [G14],
  },
  {
    id: `${id}.numbers`,
    stage: "understand",
    purpose: "teach",
    kind: "explanation",
    label: "Read a small set of numbers",
    prompt: "Registration cards use numbers and dates.",
    example: "1 — eins · 2 — zwei · 3 — drei · 12 — zwölf\nein Telefon · zwei Telefone\nNummer: 12\nDatum: 12.03.",
    explanation:
      "Nummer means number; Datum means date. In these numeric dates, the day comes before the month. 12.03. means 12 March. The plural Telefone is supplied for this lesson; do not treat it as a general plural rule.",
    skillIds: [G52, V03],
  },
  {
    id: `${id}.read-number`,
    stage: "read",
    purpose: "practice",
    kind: "text",
    answerLanguage: "de",
    label: "Scan the correct field",
    prompt: "What is Mira's registration number? Write digits.",
    example: "Name: Mira\nNummer: 12\nDatum: 12.03.",
    inputLabel: "Registration number",
    acceptedAnswers: ["12"],
    feedback: "The Nummer field says 12. The date is a different field.",
    skillIds: [R02, V03],
  },
  {
    id: `${id}.read-date`,
    stage: "read",
    purpose: "practice",
    kind: "text",
    answerLanguage: "de",
    label: "Read the date field",
    prompt: "Copy Nora's date in day.month format.",
    example: "Name: Nora\nNummer: 3\nDatum: 03.12.",
    inputLabel: "Date",
    acceptedAnswers: ["03.12.", "3.12."],
    feedback: "03.12. is 3 December: day first, month second.",
    skillIds: [R02, V03],
  },
  {
    id: `${id}.supported-count`,
    stage: "produce",
    purpose: "practice",
    kind: "text",
    answerLanguage: "de",
    label: "Use a supplied noun form",
    prompt: "Write ‘two telephones’ using the supplied noun Telefone.",
    inputLabel: "Number and noun",
    acceptedAnswers: ["zwei Telefone"],
    caseSensitive: true,
    feedback: "zwei Telefone names two objects. Keep the capital T.",
    skillIds: [G52, V03],
  },
  {
    id: `${id}.independent-question`,
    stage: "produce",
    purpose: "practice",
    kind: "text",
    answerLanguage: "de",
    label: "Ask without word tiles",
    prompt: "Ask a new person ‘Who are you?’ in German.",
    inputLabel: "German question",
    acceptedAnswers: ["Wer bist du?"],
    feedback: "Wer bist du? uses the question word first and bist second.",
    skillIds: [G15],
  },
  {
    id: `${id}.transfer`,
    stage: "apply",
    purpose: "practice",
    kind: "original",
    label: "Use the desk language",
    prompt: "Write one short German question you could use at this registration desk.",
    inputLabel: "Your question",
    maxLength: 120,
    explanation:
      "Use one of the question patterns from this lesson. This open response is unassessed practice.",
    skillIds: [G14, G15, V03],
  },
  {
    id: `${id}.check`,
    stage: "check",
    purpose: "formative-check",
    kind: "choice",
    label: "Quick lesson check",
    prompt: "Which registration number belongs to Leo?",
    example: "Name: Leo\nNummer: 2\nDatum: 12.03.",
    options: ["12", "3", "2"],
    correctAnswer: "2",
    feedback:
      "Leo's Nummer is 2. This checks one reading detail from the lesson, not proficiency.",
    skillIds: [R02, V03],
  },
];
