import { AlertTriangle, Copy } from "lucide-react";
import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { AuthGate } from "@/components/auth-gate";
import { GrammarDrillRunner } from "@/components/grammar-drill-runner";
import { Button } from "@/components/ui/button";
import { Input, Textarea } from "@/components/ui/input";
import { parseGrammarPasteJson, type GrammarPasteRound } from "@/lib/grammar-paste-import";
import { grammarPastePromptFor, GRAMMAR_PASTE_RULE } from "@/lib/grammar-paste-prompt";
import { numberSample } from "@/lib/german/grammar-drill-sample";
import { useStudyStore } from "@/lib/store";
import { shuffle } from "@/lib/utils";
import type { DrillQuestion } from "@/lib/grammar-drills";

export const Route = createFileRoute("/grammar/paste")({
  component: GrammarPasteRoute,
});

/**
 * Grammar Paste: the grammar-drill version of the vocabulary "Paste"/
 * "Karta JSON" flow (import-dialog.tsx / karta-prompt.ts / karta-import.ts)
 * — a learner types ANY topic (not one of the 26 fixed hub topics), copies
 * a prompt into their OWN AI chat, pastes the JSON it returns, and gets a
 * real 10-question round out of it. Karta's own Gemini path is never
 * involved here; see grammar-paste-prompt.ts's own doc comment.
 *
 * Two things this content is NOT, on purpose:
 * - Not added to the fixed hub or `grammarProgress`: it's unverified,
 *   AI-generated, learner-supplied content, not Karta's own reviewed
 *   material — `GrammarDrillRunner` is passed `trackProgress={false}` so
 *   no `grammarProgress` write happens, and there is no 27th hub tile or
 *   `ModeId` for it. The round exists only in this component's state and
 *   is gone the moment the learner navigates away.
 * - Never silently presented as verified: the warning banner below is
 *   rendered OUTSIDE `GrammarDrillRunner`, as a sibling that stays on
 *   screen for the entire lifetime of this route component — through
 *   loading, every question, and the final score screen alike — not just
 *   on the input screen before the round starts.
 */
function GrammarPasteRoute() {
  return (
    <AuthGate>
      <GrammarPastePage />
    </AuthGate>
  );
}

function GrammarPastePage() {
  const [topic, setTopic] = useState("");
  const [text, setText] = useState("");
  const [errors, setErrors] = useState<string[]>([]);
  const [round, setRound] = useState<GrammarPasteRound | null>(null);

  const explanationLanguage = useStudyStore((s) => s.profile?.explanationLanguage);
  const prompt = useMemo(
    () => `${grammarPastePromptFor(explanationLanguage)}${topic.trim()}`,
    [topic, explanationLanguage],
  );

  function copyPrompt() {
    navigator.clipboard
      .writeText(prompt)
      .then(() => toast.success("Prompt copied."))
      .catch(() => toast.error("Couldn't copy the prompt."));
  }

  function start() {
    setErrors([]);
    const result = parseGrammarPasteJson(text);
    if (!result.ok) {
      setErrors(result.errors);
      return;
    }
    setRound(result.value);
  }

  function reset() {
    setRound(null);
    setText("");
    setErrors([]);
  }

  return (
    <AppShell>
      <div className="mx-auto max-w-md">
        <div className="mb-4 flex items-start gap-2 rounded-card border-2 border-warning bg-surface-2 p-3 text-sm text-fg">
          <AlertTriangle className="mt-0.5 size-4 shrink-0 text-warning" />
          <p>
            This topic and these questions were generated by AI, not Karta&apos;s own verified
            content — accuracy isn&apos;t guaranteed.
          </p>
        </div>

        {round ? (
          <GrammarPasteSession round={round} onRestart={reset} />
        ) : (
          <>
            <h1 className="font-display text-2xl font-medium tracking-tight">
              Practice your own topic
            </h1>
            <p className="mt-2 text-sm text-muted">
              Type any German grammar topic — not just the 26 built into Karta — copy the prompt
              into your own AI chat, then paste back the JSON it returns.
            </p>

            <label htmlFor="grammar-paste-topic" className="mt-6 block text-sm font-medium">
              Topic
            </label>
            <Input
              id="grammar-paste-topic"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="e.g. Kausalsätze, Genitiv-Attribute"
              className="mt-1"
            />

            <details className="mt-4 rounded-card bg-surface-2 p-3 text-sm">
              <summary className="cursor-pointer font-medium text-fg">Grammar Paste prompt</summary>
              <p className="mt-2 text-muted">{GRAMMAR_PASTE_RULE}</p>
              <p className="mt-1 text-muted">
                Paste this prompt into your own AI chat (the TOPIC line is already filled in from
                above), then paste the JSON it returns below.
              </p>
              <pre className="mt-2 max-h-48 overflow-auto rounded-card bg-surface p-3 font-mono text-xs whitespace-pre-wrap text-fg">
                {prompt}
              </pre>
              <Button type="button" variant="outline" size="sm" className="mt-2" onClick={copyPrompt}>
                <Copy />
                Copy prompt
              </Button>
            </details>

            <label htmlFor="grammar-paste-json" className="mt-4 block text-sm font-medium">
              Paste the JSON here
            </label>
            <Textarea
              id="grammar-paste-json"
              value={text}
              onChange={(e) => setText(e.target.value)}
              placeholder='{"topic": "...", "ruleExplanation": "...", "questions": [...]}'
              className="mt-1 min-h-40 font-mono text-sm"
            />
            {errors.length > 0 ? (
              <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-danger">
                {errors.map((message) => (
                  <li key={message}>{message}</li>
                ))}
              </ul>
            ) : null}
            <Button type="button" className="mt-4 w-full" onClick={start} disabled={!text.trim()}>
              Start practice round
            </Button>
          </>
        )}
      </div>
    </AppShell>
  );
}

/** `GrammarDrillRunner`'s generic `T` is just a slot index here — the
 *  round's 10 questions are already fully built from `round`, so
 *  `fetchSample` only needs to hand back an array of the right length
 *  (same `numberSample`-just-for-round-size pattern Modalverben/Pronomen/
 *  Subjektive Modalverben use for their own fixed pools), and `buildRound`
 *  ignores its contents entirely. */
function GrammarPasteSession({
  round,
  onRestart,
}: {
  round: GrammarPasteRound;
  onRestart: () => void;
}) {
  function buildRound(): DrillQuestion[] {
    return round.questions.map((q) => {
      const correctAnswer = q.options[q.correctIndex];
      return {
        prompt: q.prompt,
        options: shuffle(q.options),
        correctAnswer,
      };
    });
  }

  return (
    <>
      <GrammarDrillRunner<number>
        mode={`Grammar Paste: ${round.topic}`}
        trackProgress={false}
        ruleOverride={{ title: round.topic, intro: round.ruleExplanation }}
        fetchSample={() => Promise.resolve(numberSample(round.questions.length))}
        buildRound={buildRound}
      />
      <div className="mx-auto mt-4 max-w-md text-center">
        <Button type="button" variant="ghost" size="sm" onClick={onRestart}>
          Try a different topic
        </Button>
      </div>
    </>
  );
}
