/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CreateRouteImport } from './routes/create'
import { Route as GrammarRouteImport } from './routes/grammar'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as GrammarIndexRouteImport } from './routes/grammar.index'
import { Route as GrammarAdjektivendungenRouteImport } from './routes/grammar.adjektivendungen'
import { Route as GrammarDiktatRouteImport } from './routes/grammar.diktat'
import { Route as GrammarFunktionsverbgefuegeRouteImport } from './routes/grammar.funktionsverbgefuege'
import { Route as GrammarImperativRouteImport } from './routes/grammar.imperativ'
import { Route as GrammarKonjunktivRouteImport } from './routes/grammar.konjunktiv'
import { Route as GrammarKonjunktiv1RouteImport } from './routes/grammar.konjunktiv1'
import { Route as GrammarLesenRouteImport } from './routes/grammar.lesen'
import { Route as GrammarLesenPasteRouteImport } from './routes/grammar.lesen-paste'
import { Route as GrammarModalpartikelnRouteImport } from './routes/grammar.modalpartikeln'
import { Route as GrammarModalverbenRouteImport } from './routes/grammar.modalverben'
import { Route as GrammarNichtKeinRouteImport } from './routes/grammar.nicht-kein'
import { Route as GrammarNominalisierungRouteImport } from './routes/grammar.nominalisierung'
import { Route as GrammarPartizipialRouteImport } from './routes/grammar.partizipial'
import { Route as GrammarPassivRouteImport } from './routes/grammar.passiv'
import { Route as GrammarPassiversatzformenRouteImport } from './routes/grammar.passiversatzformen'
import { Route as GrammarPasteRouteImport } from './routes/grammar.paste'
import { Route as GrammarPluralRouteImport } from './routes/grammar.plural'
import { Route as GrammarPossessiveRouteImport } from './routes/grammar.possessive'
import { Route as GrammarPronomenRouteImport } from './routes/grammar.pronomen'
import { Route as GrammarRelativsaetzeRouteImport } from './routes/grammar.relativsaetze'
import { Route as GrammarRulesRouteImport } from './routes/grammar.rules'
import { Route as GrammarSteigerungRouteImport } from './routes/grammar.steigerung'
import { Route as GrammarSubjektiveModalverbenRouteImport } from './routes/grammar.subjektive-modalverben'
import { Route as GrammarTrennbareVerbenRouteImport } from './routes/grammar.trennbare-verben'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnLessonIdRouteImport } from './routes/learn.$lessonId'
import { Route as SetsSetIdRouteImport } from './routes/sets.$setId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SetsSetIdIndexRouteImport } from './routes/sets.$setId.index'
import { Route as SetsSetIdArticlesRouteImport } from './routes/sets.$setId.articles'
import { Route as SetsSetIdCasesRouteImport } from './routes/sets.$setId.cases'
import { Route as SetsSetIdClozeRouteImport } from './routes/sets.$setId.cloze'
import { Route as SetsSetIdConjugationRouteImport } from './routes/sets.$setId.conjugation'
import { Route as SetsSetIdEditRouteImport } from './routes/sets.$setId.edit'
import { Route as SetsSetIdFlashcardsRouteImport } from './routes/sets.$setId.flashcards'
import { Route as SetsSetIdLearnRouteImport } from './routes/sets.$setId.learn'
import { Route as SetsSetIdMatchRouteImport } from './routes/sets.$setId.match'
import { Route as SetsSetIdSatzbauRouteImport } from './routes/sets.$setId.satzbau'
import { Route as SetsSetIdTestRouteImport } from './routes/sets.$setId.test'
import { Route as SetsSetIdWriteRouteImport } from './routes/sets.$setId.write'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarRoute = GrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarIndexRoute = GrammarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarAdjektivendungenRoute = GrammarAdjektivendungenRouteImport.update({
  id: '/adjektivendungen',
  path: '/adjektivendungen',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarDiktatRoute = GrammarDiktatRouteImport.update({
  id: '/diktat',
  path: '/diktat',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarFunktionsverbgefuegeRoute =
  GrammarFunktionsverbgefuegeRouteImport.update({
    id: '/funktionsverbgefuege',
    path: '/funktionsverbgefuege',
    getParentRoute: () => GrammarRoute,
  } as any)
const GrammarImperativRoute = GrammarImperativRouteImport.update({
  id: '/imperativ',
  path: '/imperativ',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarKonjunktivRoute = GrammarKonjunktivRouteImport.update({
  id: '/konjunktiv',
  path: '/konjunktiv',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarKonjunktiv1Route = GrammarKonjunktiv1RouteImport.update({
  id: '/konjunktiv1',
  path: '/konjunktiv1',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarLesenRoute = GrammarLesenRouteImport.update({
  id: '/lesen',
  path: '/lesen',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarLesenPasteRoute = GrammarLesenPasteRouteImport.update({
  id: '/lesen-paste',
  path: '/lesen-paste',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarModalpartikelnRoute = GrammarModalpartikelnRouteImport.update({
  id: '/modalpartikeln',
  path: '/modalpartikeln',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarModalverbenRoute = GrammarModalverbenRouteImport.update({
  id: '/modalverben',
  path: '/modalverben',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarNichtKeinRoute = GrammarNichtKeinRouteImport.update({
  id: '/nicht-kein',
  path: '/nicht-kein',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarNominalisierungRoute = GrammarNominalisierungRouteImport.update({
  id: '/nominalisierung',
  path: '/nominalisierung',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarPartizipialRoute = GrammarPartizipialRouteImport.update({
  id: '/partizipial',
  path: '/partizipial',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarPassivRoute = GrammarPassivRouteImport.update({
  id: '/passiv',
  path: '/passiv',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarPassiversatzformenRoute =
  GrammarPassiversatzformenRouteImport.update({
    id: '/passiversatzformen',
    path: '/passiversatzformen',
    getParentRoute: () => GrammarRoute,
  } as any)
const GrammarPasteRoute = GrammarPasteRouteImport.update({
  id: '/paste',
  path: '/paste',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarPluralRoute = GrammarPluralRouteImport.update({
  id: '/plural',
  path: '/plural',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarPossessiveRoute = GrammarPossessiveRouteImport.update({
  id: '/possessive',
  path: '/possessive',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarPronomenRoute = GrammarPronomenRouteImport.update({
  id: '/pronomen',
  path: '/pronomen',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarRelativsaetzeRoute = GrammarRelativsaetzeRouteImport.update({
  id: '/relativsaetze',
  path: '/relativsaetze',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarRulesRoute = GrammarRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarSteigerungRoute = GrammarSteigerungRouteImport.update({
  id: '/steigerung',
  path: '/steigerung',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarSubjektiveModalverbenRoute =
  GrammarSubjektiveModalverbenRouteImport.update({
    id: '/subjektive-modalverben',
    path: '/subjektive-modalverben',
    getParentRoute: () => GrammarRoute,
  } as any)
const GrammarTrennbareVerbenRoute = GrammarTrennbareVerbenRouteImport.update({
  id: '/trennbare-verben',
  path: '/trennbare-verben',
  getParentRoute: () => GrammarRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnLessonIdRoute = LearnLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => LearnRoute,
} as any)
const SetsSetIdRoute = SetsSetIdRouteImport.update({
  id: '/sets/$setId',
  path: '/sets/$setId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SetsSetIdIndexRoute = SetsSetIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetsSetIdRoute,
} as any)
const SetsSetIdArticlesRoute = SetsSetIdArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => SetsSetIdRoute,
} as any)
const SetsSetIdCasesRoute = SetsSetIdCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => SetsSetIdRoute,
} as any)
const SetsSetIdClozeRoute = SetsSetIdClozeRouteImport.update({
  id: '/cloze',
  path: '/cloze',
  getParentRoute: () => SetsSetIdRoute,
} as any)
const SetsSetIdConjugationRoute = SetsSetIdConjugationRouteImport.update({
  id: '/conjugation',
  path: '/conjugation',
  getParentRoute: () => SetsSetIdRoute,
} as any)
const SetsSetIdEditRoute = SetsSetIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SetsSetIdRoute,
} as any)
const SetsSetIdFlashcardsRoute = SetsSetIdFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => SetsSetIdRoute,
} as any)
const SetsSetIdLearnRoute = SetsSetIdLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => SetsSetIdRoute,
} as any)
const SetsSetIdMatchRoute = SetsSetIdMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => SetsSetIdRoute,
} as any)
const SetsSetIdSatzbauRoute = SetsSetIdSatzbauRouteImport.update({
  id: '/satzbau',
  path: '/satzbau',
  getParentRoute: () => SetsSetIdRoute,
} as any)
const SetsSetIdTestRoute = SetsSetIdTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => SetsSetIdRoute,
} as any)
const SetsSetIdWriteRoute = SetsSetIdWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => SetsSetIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/create': typeof CreateRoute
  '/grammar': typeof GrammarRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/signup': typeof SignupRoute
  '/grammar/adjektivendungen': typeof GrammarAdjektivendungenRoute
  '/grammar/diktat': typeof GrammarDiktatRoute
  '/grammar/funktionsverbgefuege': typeof GrammarFunktionsverbgefuegeRoute
  '/grammar/imperativ': typeof GrammarImperativRoute
  '/grammar/konjunktiv': typeof GrammarKonjunktivRoute
  '/grammar/konjunktiv1': typeof GrammarKonjunktiv1Route
  '/grammar/lesen': typeof GrammarLesenRoute
  '/grammar/lesen-paste': typeof GrammarLesenPasteRoute
  '/grammar/modalpartikeln': typeof GrammarModalpartikelnRoute
  '/grammar/modalverben': typeof GrammarModalverbenRoute
  '/grammar/nicht-kein': typeof GrammarNichtKeinRoute
  '/grammar/nominalisierung': typeof GrammarNominalisierungRoute
  '/grammar/partizipial': typeof GrammarPartizipialRoute
  '/grammar/passiv': typeof GrammarPassivRoute
  '/grammar/passiversatzformen': typeof GrammarPassiversatzformenRoute
  '/grammar/paste': typeof GrammarPasteRoute
  '/grammar/plural': typeof GrammarPluralRoute
  '/grammar/possessive': typeof GrammarPossessiveRoute
  '/grammar/pronomen': typeof GrammarPronomenRoute
  '/grammar/relativsaetze': typeof GrammarRelativsaetzeRoute
  '/grammar/rules': typeof GrammarRulesRoute
  '/grammar/steigerung': typeof GrammarSteigerungRoute
  '/grammar/subjektive-modalverben': typeof GrammarSubjektiveModalverbenRoute
  '/grammar/trennbare-verben': typeof GrammarTrennbareVerbenRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/sets/$setId': typeof SetsSetIdRouteWithChildren
  '/grammar/': typeof GrammarIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sets/$setId/articles': typeof SetsSetIdArticlesRoute
  '/sets/$setId/cases': typeof SetsSetIdCasesRoute
  '/sets/$setId/cloze': typeof SetsSetIdClozeRoute
  '/sets/$setId/conjugation': typeof SetsSetIdConjugationRoute
  '/sets/$setId/edit': typeof SetsSetIdEditRoute
  '/sets/$setId/flashcards': typeof SetsSetIdFlashcardsRoute
  '/sets/$setId/learn': typeof SetsSetIdLearnRoute
  '/sets/$setId/match': typeof SetsSetIdMatchRoute
  '/sets/$setId/satzbau': typeof SetsSetIdSatzbauRoute
  '/sets/$setId/test': typeof SetsSetIdTestRoute
  '/sets/$setId/write': typeof SetsSetIdWriteRoute
  '/sets/$setId/': typeof SetsSetIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/signup': typeof SignupRoute
  '/grammar/adjektivendungen': typeof GrammarAdjektivendungenRoute
  '/grammar/diktat': typeof GrammarDiktatRoute
  '/grammar/funktionsverbgefuege': typeof GrammarFunktionsverbgefuegeRoute
  '/grammar/imperativ': typeof GrammarImperativRoute
  '/grammar/konjunktiv': typeof GrammarKonjunktivRoute
  '/grammar/konjunktiv1': typeof GrammarKonjunktiv1Route
  '/grammar/lesen': typeof GrammarLesenRoute
  '/grammar/lesen-paste': typeof GrammarLesenPasteRoute
  '/grammar/modalpartikeln': typeof GrammarModalpartikelnRoute
  '/grammar/modalverben': typeof GrammarModalverbenRoute
  '/grammar/nicht-kein': typeof GrammarNichtKeinRoute
  '/grammar/nominalisierung': typeof GrammarNominalisierungRoute
  '/grammar/partizipial': typeof GrammarPartizipialRoute
  '/grammar/passiv': typeof GrammarPassivRoute
  '/grammar/passiversatzformen': typeof GrammarPassiversatzformenRoute
  '/grammar/paste': typeof GrammarPasteRoute
  '/grammar/plural': typeof GrammarPluralRoute
  '/grammar/possessive': typeof GrammarPossessiveRoute
  '/grammar/pronomen': typeof GrammarPronomenRoute
  '/grammar/relativsaetze': typeof GrammarRelativsaetzeRoute
  '/grammar/rules': typeof GrammarRulesRoute
  '/grammar/steigerung': typeof GrammarSteigerungRoute
  '/grammar/subjektive-modalverben': typeof GrammarSubjektiveModalverbenRoute
  '/grammar/trennbare-verben': typeof GrammarTrennbareVerbenRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/grammar': typeof GrammarIndexRoute
  '/learn': typeof LearnIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sets/$setId/articles': typeof SetsSetIdArticlesRoute
  '/sets/$setId/cases': typeof SetsSetIdCasesRoute
  '/sets/$setId/cloze': typeof SetsSetIdClozeRoute
  '/sets/$setId/conjugation': typeof SetsSetIdConjugationRoute
  '/sets/$setId/edit': typeof SetsSetIdEditRoute
  '/sets/$setId/flashcards': typeof SetsSetIdFlashcardsRoute
  '/sets/$setId/learn': typeof SetsSetIdLearnRoute
  '/sets/$setId/match': typeof SetsSetIdMatchRoute
  '/sets/$setId/satzbau': typeof SetsSetIdSatzbauRoute
  '/sets/$setId/test': typeof SetsSetIdTestRoute
  '/sets/$setId/write': typeof SetsSetIdWriteRoute
  '/sets/$setId': typeof SetsSetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/create': typeof CreateRoute
  '/grammar': typeof GrammarRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/signup': typeof SignupRoute
  '/grammar/adjektivendungen': typeof GrammarAdjektivendungenRoute
  '/grammar/diktat': typeof GrammarDiktatRoute
  '/grammar/funktionsverbgefuege': typeof GrammarFunktionsverbgefuegeRoute
  '/grammar/imperativ': typeof GrammarImperativRoute
  '/grammar/konjunktiv': typeof GrammarKonjunktivRoute
  '/grammar/konjunktiv1': typeof GrammarKonjunktiv1Route
  '/grammar/lesen': typeof GrammarLesenRoute
  '/grammar/lesen-paste': typeof GrammarLesenPasteRoute
  '/grammar/modalpartikeln': typeof GrammarModalpartikelnRoute
  '/grammar/modalverben': typeof GrammarModalverbenRoute
  '/grammar/nicht-kein': typeof GrammarNichtKeinRoute
  '/grammar/nominalisierung': typeof GrammarNominalisierungRoute
  '/grammar/partizipial': typeof GrammarPartizipialRoute
  '/grammar/passiv': typeof GrammarPassivRoute
  '/grammar/passiversatzformen': typeof GrammarPassiversatzformenRoute
  '/grammar/paste': typeof GrammarPasteRoute
  '/grammar/plural': typeof GrammarPluralRoute
  '/grammar/possessive': typeof GrammarPossessiveRoute
  '/grammar/pronomen': typeof GrammarPronomenRoute
  '/grammar/relativsaetze': typeof GrammarRelativsaetzeRoute
  '/grammar/rules': typeof GrammarRulesRoute
  '/grammar/steigerung': typeof GrammarSteigerungRoute
  '/grammar/subjektive-modalverben': typeof GrammarSubjektiveModalverbenRoute
  '/grammar/trennbare-verben': typeof GrammarTrennbareVerbenRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/sets/$setId': typeof SetsSetIdRouteWithChildren
  '/grammar/': typeof GrammarIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sets/$setId/articles': typeof SetsSetIdArticlesRoute
  '/sets/$setId/cases': typeof SetsSetIdCasesRoute
  '/sets/$setId/cloze': typeof SetsSetIdClozeRoute
  '/sets/$setId/conjugation': typeof SetsSetIdConjugationRoute
  '/sets/$setId/edit': typeof SetsSetIdEditRoute
  '/sets/$setId/flashcards': typeof SetsSetIdFlashcardsRoute
  '/sets/$setId/learn': typeof SetsSetIdLearnRoute
  '/sets/$setId/match': typeof SetsSetIdMatchRoute
  '/sets/$setId/satzbau': typeof SetsSetIdSatzbauRoute
  '/sets/$setId/test': typeof SetsSetIdTestRoute
  '/sets/$setId/write': typeof SetsSetIdWriteRoute
  '/sets/$setId/': typeof SetsSetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/create'
    | '/grammar'
    | '/learn'
    | '/login'
    | '/review'
    | '/signup'
    | '/grammar/adjektivendungen'
    | '/grammar/diktat'
    | '/grammar/funktionsverbgefuege'
    | '/grammar/imperativ'
    | '/grammar/konjunktiv'
    | '/grammar/konjunktiv1'
    | '/grammar/lesen'
    | '/grammar/lesen-paste'
    | '/grammar/modalpartikeln'
    | '/grammar/modalverben'
    | '/grammar/nicht-kein'
    | '/grammar/nominalisierung'
    | '/grammar/partizipial'
    | '/grammar/passiv'
    | '/grammar/passiversatzformen'
    | '/grammar/paste'
    | '/grammar/plural'
    | '/grammar/possessive'
    | '/grammar/pronomen'
    | '/grammar/relativsaetze'
    | '/grammar/rules'
    | '/grammar/steigerung'
    | '/grammar/subjektive-modalverben'
    | '/grammar/trennbare-verben'
    | '/learn/$lessonId'
    | '/sets/$setId'
    | '/grammar/'
    | '/learn/'
    | '/api/auth/$'
    | '/sets/$setId/articles'
    | '/sets/$setId/cases'
    | '/sets/$setId/cloze'
    | '/sets/$setId/conjugation'
    | '/sets/$setId/edit'
    | '/sets/$setId/flashcards'
    | '/sets/$setId/learn'
    | '/sets/$setId/match'
    | '/sets/$setId/satzbau'
    | '/sets/$setId/test'
    | '/sets/$setId/write'
    | '/sets/$setId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/create'
    | '/login'
    | '/review'
    | '/signup'
    | '/grammar/adjektivendungen'
    | '/grammar/diktat'
    | '/grammar/funktionsverbgefuege'
    | '/grammar/imperativ'
    | '/grammar/konjunktiv'
    | '/grammar/konjunktiv1'
    | '/grammar/lesen'
    | '/grammar/lesen-paste'
    | '/grammar/modalpartikeln'
    | '/grammar/modalverben'
    | '/grammar/nicht-kein'
    | '/grammar/nominalisierung'
    | '/grammar/partizipial'
    | '/grammar/passiv'
    | '/grammar/passiversatzformen'
    | '/grammar/paste'
    | '/grammar/plural'
    | '/grammar/possessive'
    | '/grammar/pronomen'
    | '/grammar/relativsaetze'
    | '/grammar/rules'
    | '/grammar/steigerung'
    | '/grammar/subjektive-modalverben'
    | '/grammar/trennbare-verben'
    | '/learn/$lessonId'
    | '/grammar'
    | '/learn'
    | '/api/auth/$'
    | '/sets/$setId/articles'
    | '/sets/$setId/cases'
    | '/sets/$setId/cloze'
    | '/sets/$setId/conjugation'
    | '/sets/$setId/edit'
    | '/sets/$setId/flashcards'
    | '/sets/$setId/learn'
    | '/sets/$setId/match'
    | '/sets/$setId/satzbau'
    | '/sets/$setId/test'
    | '/sets/$setId/write'
    | '/sets/$setId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/create'
    | '/grammar'
    | '/learn'
    | '/login'
    | '/review'
    | '/signup'
    | '/grammar/adjektivendungen'
    | '/grammar/diktat'
    | '/grammar/funktionsverbgefuege'
    | '/grammar/imperativ'
    | '/grammar/konjunktiv'
    | '/grammar/konjunktiv1'
    | '/grammar/lesen'
    | '/grammar/lesen-paste'
    | '/grammar/modalpartikeln'
    | '/grammar/modalverben'
    | '/grammar/nicht-kein'
    | '/grammar/nominalisierung'
    | '/grammar/partizipial'
    | '/grammar/passiv'
    | '/grammar/passiversatzformen'
    | '/grammar/paste'
    | '/grammar/plural'
    | '/grammar/possessive'
    | '/grammar/pronomen'
    | '/grammar/relativsaetze'
    | '/grammar/rules'
    | '/grammar/steigerung'
    | '/grammar/subjektive-modalverben'
    | '/grammar/trennbare-verben'
    | '/learn/$lessonId'
    | '/sets/$setId'
    | '/grammar/'
    | '/learn/'
    | '/api/auth/$'
    | '/sets/$setId/articles'
    | '/sets/$setId/cases'
    | '/sets/$setId/cloze'
    | '/sets/$setId/conjugation'
    | '/sets/$setId/edit'
    | '/sets/$setId/flashcards'
    | '/sets/$setId/learn'
    | '/sets/$setId/match'
    | '/sets/$setId/satzbau'
    | '/sets/$setId/test'
    | '/sets/$setId/write'
    | '/sets/$setId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CreateRoute: typeof CreateRoute
  GrammarRoute: typeof GrammarRouteWithChildren
  LearnRoute: typeof LearnRouteWithChildren
  LoginRoute: typeof LoginRoute
  ReviewRoute: typeof ReviewRoute
  SignupRoute: typeof SignupRoute
  SetsSetIdRoute: typeof SetsSetIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar': {
      id: '/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof GrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar/': {
      id: '/grammar/'
      path: '/'
      fullPath: '/grammar/'
      preLoaderRoute: typeof GrammarIndexRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/adjektivendungen': {
      id: '/grammar/adjektivendungen'
      path: '/adjektivendungen'
      fullPath: '/grammar/adjektivendungen'
      preLoaderRoute: typeof GrammarAdjektivendungenRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/diktat': {
      id: '/grammar/diktat'
      path: '/diktat'
      fullPath: '/grammar/diktat'
      preLoaderRoute: typeof GrammarDiktatRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/funktionsverbgefuege': {
      id: '/grammar/funktionsverbgefuege'
      path: '/funktionsverbgefuege'
      fullPath: '/grammar/funktionsverbgefuege'
      preLoaderRoute: typeof GrammarFunktionsverbgefuegeRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/imperativ': {
      id: '/grammar/imperativ'
      path: '/imperativ'
      fullPath: '/grammar/imperativ'
      preLoaderRoute: typeof GrammarImperativRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/konjunktiv': {
      id: '/grammar/konjunktiv'
      path: '/konjunktiv'
      fullPath: '/grammar/konjunktiv'
      preLoaderRoute: typeof GrammarKonjunktivRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/konjunktiv1': {
      id: '/grammar/konjunktiv1'
      path: '/konjunktiv1'
      fullPath: '/grammar/konjunktiv1'
      preLoaderRoute: typeof GrammarKonjunktiv1RouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/lesen': {
      id: '/grammar/lesen'
      path: '/lesen'
      fullPath: '/grammar/lesen'
      preLoaderRoute: typeof GrammarLesenRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/lesen-paste': {
      id: '/grammar/lesen-paste'
      path: '/lesen-paste'
      fullPath: '/grammar/lesen-paste'
      preLoaderRoute: typeof GrammarLesenPasteRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/modalpartikeln': {
      id: '/grammar/modalpartikeln'
      path: '/modalpartikeln'
      fullPath: '/grammar/modalpartikeln'
      preLoaderRoute: typeof GrammarModalpartikelnRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/modalverben': {
      id: '/grammar/modalverben'
      path: '/modalverben'
      fullPath: '/grammar/modalverben'
      preLoaderRoute: typeof GrammarModalverbenRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/nicht-kein': {
      id: '/grammar/nicht-kein'
      path: '/nicht-kein'
      fullPath: '/grammar/nicht-kein'
      preLoaderRoute: typeof GrammarNichtKeinRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/nominalisierung': {
      id: '/grammar/nominalisierung'
      path: '/nominalisierung'
      fullPath: '/grammar/nominalisierung'
      preLoaderRoute: typeof GrammarNominalisierungRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/partizipial': {
      id: '/grammar/partizipial'
      path: '/partizipial'
      fullPath: '/grammar/partizipial'
      preLoaderRoute: typeof GrammarPartizipialRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/passiv': {
      id: '/grammar/passiv'
      path: '/passiv'
      fullPath: '/grammar/passiv'
      preLoaderRoute: typeof GrammarPassivRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/passiversatzformen': {
      id: '/grammar/passiversatzformen'
      path: '/passiversatzformen'
      fullPath: '/grammar/passiversatzformen'
      preLoaderRoute: typeof GrammarPassiversatzformenRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/paste': {
      id: '/grammar/paste'
      path: '/paste'
      fullPath: '/grammar/paste'
      preLoaderRoute: typeof GrammarPasteRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/plural': {
      id: '/grammar/plural'
      path: '/plural'
      fullPath: '/grammar/plural'
      preLoaderRoute: typeof GrammarPluralRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/possessive': {
      id: '/grammar/possessive'
      path: '/possessive'
      fullPath: '/grammar/possessive'
      preLoaderRoute: typeof GrammarPossessiveRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/pronomen': {
      id: '/grammar/pronomen'
      path: '/pronomen'
      fullPath: '/grammar/pronomen'
      preLoaderRoute: typeof GrammarPronomenRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/relativsaetze': {
      id: '/grammar/relativsaetze'
      path: '/relativsaetze'
      fullPath: '/grammar/relativsaetze'
      preLoaderRoute: typeof GrammarRelativsaetzeRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/rules': {
      id: '/grammar/rules'
      path: '/rules'
      fullPath: '/grammar/rules'
      preLoaderRoute: typeof GrammarRulesRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/steigerung': {
      id: '/grammar/steigerung'
      path: '/steigerung'
      fullPath: '/grammar/steigerung'
      preLoaderRoute: typeof GrammarSteigerungRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/subjektive-modalverben': {
      id: '/grammar/subjektive-modalverben'
      path: '/subjektive-modalverben'
      fullPath: '/grammar/subjektive-modalverben'
      preLoaderRoute: typeof GrammarSubjektiveModalverbenRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/trennbare-verben': {
      id: '/grammar/trennbare-verben'
      path: '/trennbare-verben'
      fullPath: '/grammar/trennbare-verben'
      preLoaderRoute: typeof GrammarTrennbareVerbenRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/$lessonId': {
      id: '/learn/$lessonId'
      path: '/$lessonId'
      fullPath: '/learn/$lessonId'
      preLoaderRoute: typeof LearnLessonIdRouteImport
      parentRoute: typeof LearnRoute
    }
    '/sets/$setId': {
      id: '/sets/$setId'
      path: '/sets/$setId'
      fullPath: '/sets/$setId'
      preLoaderRoute: typeof SetsSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sets/$setId/': {
      id: '/sets/$setId/'
      path: '/'
      fullPath: '/sets/$setId/'
      preLoaderRoute: typeof SetsSetIdIndexRouteImport
      parentRoute: typeof SetsSetIdRoute
    }
    '/sets/$setId/articles': {
      id: '/sets/$setId/articles'
      path: '/articles'
      fullPath: '/sets/$setId/articles'
      preLoaderRoute: typeof SetsSetIdArticlesRouteImport
      parentRoute: typeof SetsSetIdRoute
    }
    '/sets/$setId/cases': {
      id: '/sets/$setId/cases'
      path: '/cases'
      fullPath: '/sets/$setId/cases'
      preLoaderRoute: typeof SetsSetIdCasesRouteImport
      parentRoute: typeof SetsSetIdRoute
    }
    '/sets/$setId/cloze': {
      id: '/sets/$setId/cloze'
      path: '/cloze'
      fullPath: '/sets/$setId/cloze'
      preLoaderRoute: typeof SetsSetIdClozeRouteImport
      parentRoute: typeof SetsSetIdRoute
    }
    '/sets/$setId/conjugation': {
      id: '/sets/$setId/conjugation'
      path: '/conjugation'
      fullPath: '/sets/$setId/conjugation'
      preLoaderRoute: typeof SetsSetIdConjugationRouteImport
      parentRoute: typeof SetsSetIdRoute
    }
    '/sets/$setId/edit': {
      id: '/sets/$setId/edit'
      path: '/edit'
      fullPath: '/sets/$setId/edit'
      preLoaderRoute: typeof SetsSetIdEditRouteImport
      parentRoute: typeof SetsSetIdRoute
    }
    '/sets/$setId/flashcards': {
      id: '/sets/$setId/flashcards'
      path: '/flashcards'
      fullPath: '/sets/$setId/flashcards'
      preLoaderRoute: typeof SetsSetIdFlashcardsRouteImport
      parentRoute: typeof SetsSetIdRoute
    }
    '/sets/$setId/learn': {
      id: '/sets/$setId/learn'
      path: '/learn'
      fullPath: '/sets/$setId/learn'
      preLoaderRoute: typeof SetsSetIdLearnRouteImport
      parentRoute: typeof SetsSetIdRoute
    }
    '/sets/$setId/match': {
      id: '/sets/$setId/match'
      path: '/match'
      fullPath: '/sets/$setId/match'
      preLoaderRoute: typeof SetsSetIdMatchRouteImport
      parentRoute: typeof SetsSetIdRoute
    }
    '/sets/$setId/satzbau': {
      id: '/sets/$setId/satzbau'
      path: '/satzbau'
      fullPath: '/sets/$setId/satzbau'
      preLoaderRoute: typeof SetsSetIdSatzbauRouteImport
      parentRoute: typeof SetsSetIdRoute
    }
    '/sets/$setId/test': {
      id: '/sets/$setId/test'
      path: '/test'
      fullPath: '/sets/$setId/test'
      preLoaderRoute: typeof SetsSetIdTestRouteImport
      parentRoute: typeof SetsSetIdRoute
    }
    '/sets/$setId/write': {
      id: '/sets/$setId/write'
      path: '/write'
      fullPath: '/sets/$setId/write'
      preLoaderRoute: typeof SetsSetIdWriteRouteImport
      parentRoute: typeof SetsSetIdRoute
    }
  }
}

interface GrammarRouteChildren {
  GrammarAdjektivendungenRoute: typeof GrammarAdjektivendungenRoute
  GrammarDiktatRoute: typeof GrammarDiktatRoute
  GrammarFunktionsverbgefuegeRoute: typeof GrammarFunktionsverbgefuegeRoute
  GrammarImperativRoute: typeof GrammarImperativRoute
  GrammarKonjunktivRoute: typeof GrammarKonjunktivRoute
  GrammarKonjunktiv1Route: typeof GrammarKonjunktiv1Route
  GrammarLesenRoute: typeof GrammarLesenRoute
  GrammarLesenPasteRoute: typeof GrammarLesenPasteRoute
  GrammarModalpartikelnRoute: typeof GrammarModalpartikelnRoute
  GrammarModalverbenRoute: typeof GrammarModalverbenRoute
  GrammarNichtKeinRoute: typeof GrammarNichtKeinRoute
  GrammarNominalisierungRoute: typeof GrammarNominalisierungRoute
  GrammarPartizipialRoute: typeof GrammarPartizipialRoute
  GrammarPassivRoute: typeof GrammarPassivRoute
  GrammarPassiversatzformenRoute: typeof GrammarPassiversatzformenRoute
  GrammarPasteRoute: typeof GrammarPasteRoute
  GrammarPluralRoute: typeof GrammarPluralRoute
  GrammarPossessiveRoute: typeof GrammarPossessiveRoute
  GrammarPronomenRoute: typeof GrammarPronomenRoute
  GrammarRelativsaetzeRoute: typeof GrammarRelativsaetzeRoute
  GrammarRulesRoute: typeof GrammarRulesRoute
  GrammarSteigerungRoute: typeof GrammarSteigerungRoute
  GrammarSubjektiveModalverbenRoute: typeof GrammarSubjektiveModalverbenRoute
  GrammarTrennbareVerbenRoute: typeof GrammarTrennbareVerbenRoute
  GrammarIndexRoute: typeof GrammarIndexRoute
}

const GrammarRouteChildren: GrammarRouteChildren = {
  GrammarAdjektivendungenRoute: GrammarAdjektivendungenRoute,
  GrammarDiktatRoute: GrammarDiktatRoute,
  GrammarFunktionsverbgefuegeRoute: GrammarFunktionsverbgefuegeRoute,
  GrammarImperativRoute: GrammarImperativRoute,
  GrammarKonjunktivRoute: GrammarKonjunktivRoute,
  GrammarKonjunktiv1Route: GrammarKonjunktiv1Route,
  GrammarLesenRoute: GrammarLesenRoute,
  GrammarLesenPasteRoute: GrammarLesenPasteRoute,
  GrammarModalpartikelnRoute: GrammarModalpartikelnRoute,
  GrammarModalverbenRoute: GrammarModalverbenRoute,
  GrammarNichtKeinRoute: GrammarNichtKeinRoute,
  GrammarNominalisierungRoute: GrammarNominalisierungRoute,
  GrammarPartizipialRoute: GrammarPartizipialRoute,
  GrammarPassivRoute: GrammarPassivRoute,
  GrammarPassiversatzformenRoute: GrammarPassiversatzformenRoute,
  GrammarPasteRoute: GrammarPasteRoute,
  GrammarPluralRoute: GrammarPluralRoute,
  GrammarPossessiveRoute: GrammarPossessiveRoute,
  GrammarPronomenRoute: GrammarPronomenRoute,
  GrammarRelativsaetzeRoute: GrammarRelativsaetzeRoute,
  GrammarRulesRoute: GrammarRulesRoute,
  GrammarSteigerungRoute: GrammarSteigerungRoute,
  GrammarSubjektiveModalverbenRoute: GrammarSubjektiveModalverbenRoute,
  GrammarTrennbareVerbenRoute: GrammarTrennbareVerbenRoute,
  GrammarIndexRoute: GrammarIndexRoute,
}

const GrammarRouteWithChildren =
  GrammarRoute._addFileChildren(GrammarRouteChildren)

interface LearnRouteChildren {
  LearnLessonIdRoute: typeof LearnLessonIdRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnLessonIdRoute: LearnLessonIdRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface SetsSetIdRouteChildren {
  SetsSetIdArticlesRoute: typeof SetsSetIdArticlesRoute
  SetsSetIdCasesRoute: typeof SetsSetIdCasesRoute
  SetsSetIdClozeRoute: typeof SetsSetIdClozeRoute
  SetsSetIdConjugationRoute: typeof SetsSetIdConjugationRoute
  SetsSetIdEditRoute: typeof SetsSetIdEditRoute
  SetsSetIdFlashcardsRoute: typeof SetsSetIdFlashcardsRoute
  SetsSetIdLearnRoute: typeof SetsSetIdLearnRoute
  SetsSetIdMatchRoute: typeof SetsSetIdMatchRoute
  SetsSetIdSatzbauRoute: typeof SetsSetIdSatzbauRoute
  SetsSetIdTestRoute: typeof SetsSetIdTestRoute
  SetsSetIdWriteRoute: typeof SetsSetIdWriteRoute
  SetsSetIdIndexRoute: typeof SetsSetIdIndexRoute
}

const SetsSetIdRouteChildren: SetsSetIdRouteChildren = {
  SetsSetIdArticlesRoute: SetsSetIdArticlesRoute,
  SetsSetIdCasesRoute: SetsSetIdCasesRoute,
  SetsSetIdClozeRoute: SetsSetIdClozeRoute,
  SetsSetIdConjugationRoute: SetsSetIdConjugationRoute,
  SetsSetIdEditRoute: SetsSetIdEditRoute,
  SetsSetIdFlashcardsRoute: SetsSetIdFlashcardsRoute,
  SetsSetIdLearnRoute: SetsSetIdLearnRoute,
  SetsSetIdMatchRoute: SetsSetIdMatchRoute,
  SetsSetIdSatzbauRoute: SetsSetIdSatzbauRoute,
  SetsSetIdTestRoute: SetsSetIdTestRoute,
  SetsSetIdWriteRoute: SetsSetIdWriteRoute,
  SetsSetIdIndexRoute: SetsSetIdIndexRoute,
}

const SetsSetIdRouteWithChildren = SetsSetIdRoute._addFileChildren(
  SetsSetIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CreateRoute: CreateRoute,
  GrammarRoute: GrammarRouteWithChildren,
  LearnRoute: LearnRouteWithChildren,
  LoginRoute: LoginRoute,
  ReviewRoute: ReviewRoute,
  SignupRoute: SignupRoute,
  SetsSetIdRoute: SetsSetIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
