/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiDebugFsRouteImport } from './routes/api/debug-fs'
import { Route as SetsSetIdRouteImport } from './routes/sets.$setId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SetsSetIdIndexRouteImport } from './routes/sets.$setId.index'
import { Route as SetsSetIdEditRouteImport } from './routes/sets.$setId.edit'
import { Route as SetsSetIdFlashcardsRouteImport } from './routes/sets.$setId.flashcards'
import { Route as SetsSetIdLearnRouteImport } from './routes/sets.$setId.learn'
import { Route as SetsSetIdMatchRouteImport } from './routes/sets.$setId.match'
import { Route as SetsSetIdTestRouteImport } from './routes/sets.$setId.test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugFsRoute = ApiDebugFsRouteImport.update({
  id: '/api/debug-fs',
  path: '/api/debug-fs',
  getParentRoute: () => rootRouteImport,
} as any)
const SetsSetIdRoute = SetsSetIdRouteImport.update({
  id: '/sets/$setId',
  path: '/sets/$setId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SetsSetIdIndexRoute = SetsSetIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetsSetIdRoute,
} as any)
const SetsSetIdEditRoute = SetsSetIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SetsSetIdRoute,
} as any)
const SetsSetIdFlashcardsRoute = SetsSetIdFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => SetsSetIdRoute,
} as any)
const SetsSetIdLearnRoute = SetsSetIdLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => SetsSetIdRoute,
} as any)
const SetsSetIdMatchRoute = SetsSetIdMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => SetsSetIdRoute,
} as any)
const SetsSetIdTestRoute = SetsSetIdTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => SetsSetIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/api/debug-fs': typeof ApiDebugFsRoute
  '/sets/$setId': typeof SetsSetIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sets/$setId/edit': typeof SetsSetIdEditRoute
  '/sets/$setId/flashcards': typeof SetsSetIdFlashcardsRoute
  '/sets/$setId/learn': typeof SetsSetIdLearnRoute
  '/sets/$setId/match': typeof SetsSetIdMatchRoute
  '/sets/$setId/test': typeof SetsSetIdTestRoute
  '/sets/$setId/': typeof SetsSetIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/api/debug-fs': typeof ApiDebugFsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sets/$setId/edit': typeof SetsSetIdEditRoute
  '/sets/$setId/flashcards': typeof SetsSetIdFlashcardsRoute
  '/sets/$setId/learn': typeof SetsSetIdLearnRoute
  '/sets/$setId/match': typeof SetsSetIdMatchRoute
  '/sets/$setId/test': typeof SetsSetIdTestRoute
  '/sets/$setId': typeof SetsSetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/api/debug-fs': typeof ApiDebugFsRoute
  '/sets/$setId': typeof SetsSetIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sets/$setId/edit': typeof SetsSetIdEditRoute
  '/sets/$setId/flashcards': typeof SetsSetIdFlashcardsRoute
  '/sets/$setId/learn': typeof SetsSetIdLearnRoute
  '/sets/$setId/match': typeof SetsSetIdMatchRoute
  '/sets/$setId/test': typeof SetsSetIdTestRoute
  '/sets/$setId/': typeof SetsSetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/login'
    | '/api/debug-fs'
    | '/sets/$setId'
    | '/api/auth/$'
    | '/sets/$setId/edit'
    | '/sets/$setId/flashcards'
    | '/sets/$setId/learn'
    | '/sets/$setId/match'
    | '/sets/$setId/test'
    | '/sets/$setId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/login'
    | '/api/debug-fs'
    | '/api/auth/$'
    | '/sets/$setId/edit'
    | '/sets/$setId/flashcards'
    | '/sets/$setId/learn'
    | '/sets/$setId/match'
    | '/sets/$setId/test'
    | '/sets/$setId'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/login'
    | '/api/debug-fs'
    | '/sets/$setId'
    | '/api/auth/$'
    | '/sets/$setId/edit'
    | '/sets/$setId/flashcards'
    | '/sets/$setId/learn'
    | '/sets/$setId/match'
    | '/sets/$setId/test'
    | '/sets/$setId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  LoginRoute: typeof LoginRoute
  ApiDebugFsRoute: typeof ApiDebugFsRoute
  SetsSetIdRoute: typeof SetsSetIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug-fs': {
      id: '/api/debug-fs'
      path: '/api/debug-fs'
      fullPath: '/api/debug-fs'
      preLoaderRoute: typeof ApiDebugFsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sets/$setId': {
      id: '/sets/$setId'
      path: '/sets/$setId'
      fullPath: '/sets/$setId'
      preLoaderRoute: typeof SetsSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sets/$setId/': {
      id: '/sets/$setId/'
      path: '/'
      fullPath: '/sets/$setId/'
      preLoaderRoute: typeof SetsSetIdIndexRouteImport
      parentRoute: typeof SetsSetIdRoute
    }
    '/sets/$setId/edit': {
      id: '/sets/$setId/edit'
      path: '/edit'
      fullPath: '/sets/$setId/edit'
      preLoaderRoute: typeof SetsSetIdEditRouteImport
      parentRoute: typeof SetsSetIdRoute
    }
    '/sets/$setId/flashcards': {
      id: '/sets/$setId/flashcards'
      path: '/flashcards'
      fullPath: '/sets/$setId/flashcards'
      preLoaderRoute: typeof SetsSetIdFlashcardsRouteImport
      parentRoute: typeof SetsSetIdRoute
    }
    '/sets/$setId/learn': {
      id: '/sets/$setId/learn'
      path: '/learn'
      fullPath: '/sets/$setId/learn'
      preLoaderRoute: typeof SetsSetIdLearnRouteImport
      parentRoute: typeof SetsSetIdRoute
    }
    '/sets/$setId/match': {
      id: '/sets/$setId/match'
      path: '/match'
      fullPath: '/sets/$setId/match'
      preLoaderRoute: typeof SetsSetIdMatchRouteImport
      parentRoute: typeof SetsSetIdRoute
    }
    '/sets/$setId/test': {
      id: '/sets/$setId/test'
      path: '/test'
      fullPath: '/sets/$setId/test'
      preLoaderRoute: typeof SetsSetIdTestRouteImport
      parentRoute: typeof SetsSetIdRoute
    }
  }
}

interface SetsSetIdRouteChildren {
  SetsSetIdEditRoute: typeof SetsSetIdEditRoute
  SetsSetIdFlashcardsRoute: typeof SetsSetIdFlashcardsRoute
  SetsSetIdLearnRoute: typeof SetsSetIdLearnRoute
  SetsSetIdMatchRoute: typeof SetsSetIdMatchRoute
  SetsSetIdTestRoute: typeof SetsSetIdTestRoute
  SetsSetIdIndexRoute: typeof SetsSetIdIndexRoute
}

const SetsSetIdRouteChildren: SetsSetIdRouteChildren = {
  SetsSetIdEditRoute: SetsSetIdEditRoute,
  SetsSetIdFlashcardsRoute: SetsSetIdFlashcardsRoute,
  SetsSetIdLearnRoute: SetsSetIdLearnRoute,
  SetsSetIdMatchRoute: SetsSetIdMatchRoute,
  SetsSetIdTestRoute: SetsSetIdTestRoute,
  SetsSetIdIndexRoute: SetsSetIdIndexRoute,
}

const SetsSetIdRouteWithChildren = SetsSetIdRoute._addFileChildren(
  SetsSetIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  LoginRoute: LoginRoute,
  ApiDebugFsRoute: ApiDebugFsRoute,
  SetsSetIdRoute: SetsSetIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
